<?php
/**
 * funadmin
 * ============================================================================
 * 版权所有 2018-2027 funadmin，并保留所有权利。
 * 网站地址: https://www.funadmin.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/9/4
 */
namespace addons\wechat\backend\controller;

use app\common\controller\AddonsBackend;
use app\common\traits\Curd;
use think\facade\Db;
use think\facade\Request;
use think\facade\View;
use addons\wechat\backend\model\AddonsWechatAccount;
use addons\wechat\backend\service\WechatService;
use fun\helper\DataHelper;

use addons\wechat\backend\model\AddonsWechatFans;
use addons\wechat\backend\model\AddonsWechatMaterialInfo;
use addons\wechat\backend\model\AddonsWechatMaterial;
use addons\wechat\backend\model\AddonsWechatMenu;
use addons\wechat\backend\model\AddonsWechatReply;
use addons\wechat\backend\model\AddonsWechatTag;

use EasyWeChat\Kernel\Messages\Text;
use EasyWeChat\Kernel\Messages\Article;
use EasyWeChat\Kernel\Messages\Image;
use EasyWeChat\Kernel\Messages\Video;
use EasyWeChat\Kernel\Messages\Voice;
use EasyWeChat\Kernel\Messages\News;
use EasyWeChat\Kernel\Messages\NewsItem;

class Index extends AddonsBackend {
    use Curd;
    //图片（image）: 2M，支持bmp/png/jpeg/jpg/gif格式
    //
    //语音（voice）：2M，播放长度不超过60s，mp3/wma/wav/amr格式
    //
    //视频（video）：10MB，支持MP4格式
    //
    //缩略图（thumb）：64KB，支持JPG格式
    protected $imageValidate = [
        'image' => 'filesize:2048|fileExt:jpg,png,gif,jpeg'

    ];
    protected $videoValidate = [
        'file' => 'filesize:10240|fileExt:avi,rmvb,3gp,flv,mp4,rm'

    ];
    protected $voiceValidate = [
        'file' => 'filesize:2048|fileExt:mp3,wma,wav,amr'

    ];
    protected $thumbValidate = [
        'image' => 'filesize:64|fileExt:jpg'

    ];
    protected $where =[];
    public $wechatApp;
    public $store_id;
    protected $wechatAccount ;
    protected $materialType = ['news','video','voice','image','music'];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated
        $wechatApp  = new WechatApp();
        $this->store_id = $wechatApp->store_id;
        $this->wechatAccount = AddonsWechatAccount::where('status',1)->where('store_id',$this->store_id)->find();

        if($this->wechatAccount){
            $this->wechatApp = cache('wechatapp_'.$this->wechatAccount->id);
            if(!$this->wechatApp){
                $this->wechatApp = $wechatApp->wechatApp;
//                cache('wechatapp_'.$this->wechatAccount->id,$this->wechatApp);
            }
            $this->where= ['store_id'=>$this->store_id,'addons_wechat_aid'=>$this->wechatAccount->id];

        }else{
            $this->wechatAccount = AddonsWechatAccount::where('store_id',$this->store_id)->find();
        }
    }



    /**
     ************************公众号管理****************************
     */
    public function index(){
        if (Request::isPost()) {
            $list = Db::name('addons_wechat_account')->alias('a')
                ->leftJoin('addons_wechat_type t','t.type_id=a.type')
                ->field('a.*,t.name as type_name')->cache(3600)
                ->select()->toArray();

            return $result = ['code' => 0, 'msg' =>lang('get info success'), 'data' => $list,];
        }
        return view();

    }

    public function add(){
        if (Request::isPost()) {
            $data = $this->request->post();
            try{
                $this->validate($data, 'AddonsWechatAccount');
            }catch (\Exception $e){
                $this->error($e->getMeussage());
            }
            $data['weixin'] = $data['wxname'];
            $res = AddonsWechatAccount::create($data);
            if ($res) {
                $this->success(lang('add success'),url('index'));
            } else {
                $this->error(lang('add fail'));
            }
        }
        $view = [
            'info' => '',
            'title' => lang('add'),
        ];
        View::assign($view);
        return view();
    }

    public function edit(){
        if (Request::isPost()) {
            $data = $this->request->post();
            try {
                $this->validate($data, 'AddonsWechatAccount');
            } catch (\Exception $e) {
                $this->error($e->getMessage());
            }
            $res = AddonsWechatAccount::update($data);
            if ($res) {
                $this->success(lang('edit success'), url('index'));
            } else {
                $this->error(lang('edit fail'));
            }
        }
        $info = AddonsWechatAccount::cache(3600)->find($this->request->get('id'));
        $view = [
            'info' => $info,
            'title' => '修改',
        ];
        View::assign($view);
        return view('add');

    }
    public function state(){

        $id = $this->request->post('id');
        if($id){
            $info = AddonsWechatAccount::cache(3600)->find($id);
            $info->status = $info->status==1?0:1;
            if($info->status==1){
                $list = AddonsWechatAccount::where('status',1)->where('id','<>',$info->id)->select();
                if($list){
                    foreach ($list as $k=>$v){
                        $v->status=0;
                        $v->save();
                    }
                }
            }
            $info->save();
            $this->success(lang('edit success'));
        }else{
            $this->error('非法数据');
        }
    }
    public function delete(){
        $id = $this->request->post('id');
        if($id){
            AddonsWechatAccount::destroy($id);
            $this->success(lang('delete success'));

        }else{
            $this->error('非法数据');
        }

    }


    /**
     ************************菜单管理****************************
     */


    public function menu(){
        $baseURL = $this->request->domain();
        $view = [
            'baseURL'=>$baseURL,
        ];
        View::assign($view);
        return view();

    }
    //获取微信账号
    public function getAddonsWechatAccount(){

        $info =  AddonsWechatAccount::cache(3600)->order('status desc')->select();

        return $info;

    }
    //更改app
    public function changeApp(){
        $appid = $this->request->post('app_id');
        $isAPP = AddonsWechatAccount::cache(3600)->where('app_id',$appid)->value('status');
        $button['button']=[];
        if(!$isAPP){
            $this->error('失败','',$button);
        }
        //获取当前菜单
        $menu = cache('addons_wechat_menus');
        if(!$menu){

            $menu = $this->wechatApp->menu->list();
            cache('addons_wechat_menus',$menu);
        }
        if(isset($menu['menu'])){

            $button = $menu['menu'];
            $this->success('成功','',$button);
        }else{
            $this->error('失败','',$button);
        }

    }

    // 添加微信菜单
    public function addWeixinMenu(){
        $data = $this->request->post();
        $app_id = $data['app_id'];
        $isApp = AddonsWechatAccount::where('store_id',$this->store_id)->cache(3600)->where('app_id',$app_id)->value('status');
        if($isApp !=1){
            $this->error(lang('account is not accessed'));
        }
        $menu = $data['menu'];
        if (!empty($menu)) {
            $res = $this->wechatApp->menu->create($menu['button']);
            if($res['errcode']==0){
                $this->success(lang('add success'));
                //AddonsWechatMenu::create($menu['button']);
            }else{
                $this->error(lang('create failed'));
            }
        }
        $this->error(lang('create fai'));
    }

    /**
     * 跟新菜单
     */
    public function updataWechatMenu()
    {
        $menu =  $this->wechatApp->menu->list();
        $this->success(lang('update success'));

    }

    /**
     * 删除菜单
     */
    public function menuDel(){

        $res = $this->wechatApp->menu->delete(); // 全部
        if($res['errcode']==0){
            $this->success(lang('delete success'));
        }else{
            $this->error(lang('delete fai'));
        }
    }

    /**
     ************************粉丝管理***************************
     */
    public function fans(){

        if (Request::isPost()) {
            $addons_wechat_aid = $this->request->post('addons_wechat_aid');
            if(!$addons_wechat_aid){
                $addons_wechat_aid =  $this->wechatAccount->id;
            }
            if(!$addons_wechat_aid){
                return $result = ['code' => 0,'msg' => lang('account is not accessed'),];
            }
            $keys = $this->request->post('keys','','trim');
            $page = $this->request->post('page') ? $this->request->post('page') : 1;
            $list=AddonsWechatFans::where('nickname','like','%'.$keys.'%')
                ->where('addons_wechat_aid',$addons_wechat_aid)
                ->order('fans_id desc')->cache(3600)
                ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                ->toArray();
            $tag = AddonsWechatTag::where('store_id',$this->store_id)->where('addons_wechat_aid',$addons_wechat_aid)
                ->select()->toArray();

            foreach ($list['data'] as $k=>$v){
                $list['data'][$k]['tag_list'] = $tag;
            }
            return $result = ['code' => 0, 'msg' =>lang('get info success'), 'data' => $list['data'],'count'=>$list['total'],'tag'=>$tag];
        }
        $AddonsWechatAccount = AddonsWechatAccount:: where('store_id',$this->store_id)->select();
        $view = [
            'title'=>'粉丝',
            'info'=>'',
            'AddonsWechatAccount'=>$AddonsWechatAccount,
        ];
        View::assign($view);
        return view();
    }


    public function fansAysn(){
        $addons_wechat_aid = $this->request->post('addons_wechat_aid');
        if(!$addons_wechat_aid){
            $this->error('请求错误');
        }
        $AddonsWechatAccount = $this->wechatAccount;
        if(!$AddonsWechatAccount){
            $this->error(lang('account is not accessed'));
        }
        $usersOpenidList = $this->wechatApp->user->list();
        $users = [];
        if($usersOpenidList['total']>0){
            foreach ($usersOpenidList['data']['openid'] as $k=>$v){
                $users[$k] =  $this->wechatApp->user->get($v);
            }
        }
        $AddonsWechatFansModel = new AddonsWechatFans();
//        Db::startTrans();
//        try {
        foreach ($users as $k=>$v){
            $v['addons_wechat_aid'] = $addons_wechat_aid;
            $v['tagid_list'] = json_encode($v['tagid_list']);

            $fans = $AddonsWechatFansModel::where($this->where)
                ->cache(3600)
                ->where('openid',$v['openid'])
                ->find();
            if($fans){
                $v['update_time'] = time();
                $res = $fans->force()->save($v);
            }else{
                $v['store_id'] = $this->store_id;
                $v['update_time'] = time();
                $v['nickname_encode'] = json_encode($v['nickname']);
                $res = $AddonsWechatFansModel::create($v);
            }
        }

//          // 提交事务
//          Db::commit();
        $this->success('同步成功');
//        } catch (\Exception $e) {
//             //回滚事务
//            Db::rollback();
//            $this->error('同步失败');
//        }

//        $this->success('同步成功');

    }
    //粉丝标签
    public function fansTagGroup(){
        if(Request::isPost()){
            $id = $this->request->post('id');
            $tag = $this->request->post('tag');
            $AddonsWechatFans = AddonsWechatFans::where('fans_id',$id)->cache(3600)->find();
            $tags = AddonsWechatTag::where('store_id',$this->store_id)
                ->where('addons_wechat_aid',$AddonsWechatFans->addons_wechat_aid)->cache(3600)->find();
            $AddonsWechatFans->tag = $tag;
            $res = $this->wechatApp->user_tag->tagUsers([$AddonsWechatFans->openid],$tags['tag_id']);
            if($res){
                $AddonsWechatFans->save();
                $this->success(lang('update success'));
            }else{
                $this->error(lang('update fail'));

            }
        }

    }
    //粉丝标签管理
    public function tag(){
        if (Request::isPost()) {
            $addons_wechat_aid = $this->request->post('addons_wechat_aid');
            if(!$addons_wechat_aid){
                $addons_wechat_aid =  $this->wechatAccount->id;
            }
            if(!$addons_wechat_aid){
                return $result = ['code' => 0,'msg' => lang('account is not accessed'),];

            }
            $keys = $this->request->post('keys','','trim');
            $page = $this->request->post('page') ? $this->request->post('page') : 1;
            $list=Db::name('addons_wechat_tag')
                ->where('name','like','%'.$keys.'%')
                ->where('addons_wechat_aid',$addons_wechat_aid)
                ->order('id desc')
                ->cache(3600)
                ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                ->toArray();

            return $result = ['code' => 0, 'msg' =>lang('get info success'), 'data' => $list['data'],'count'=>$list['total']];
        }


        $AddonsWechatAccount = AddonsWechatAccount::where('store_id',$this->store_id)->cache(3600)->select();

        $view = ['title'=>lang('tag'), 'info'=>'', 'AddonsWechatAccount'=>$AddonsWechatAccount];
        View::assign($view);
        return view();

    }
    public function tagState(){

        if (Request::isPost()) {
            $id = $this->request->post('id');
            if (empty($id)) {
                $this->error('id'.lang('not exist'));
            }
            $adv = AddonsWechatTag::find($id);
            $status = $adv['status'] == 1 ? 0 : 1;
            $adv->status = $status;
            $adv->save();
            $this->success(lang('edit success'));
        }

    }
    public function tagAysn()
    {
        if(Request::isPost()){
            $addons_wechat_aid = $this->wechatAccount->id;
            $tags = $this->wechatApp->user_tag->list();

            foreach($tags['tags'] as $k=>$v){
                $info = AddonsWechatTag::where('name',$v['name'])->find();
                $v['tag_id'] = $v['id'];

                if(!$info){
                    $v['store_id'] = $this->store_id;
                    $v['addons_wechat_aid'] = $this->request->post('addons_wechat_aid')?$this->request->post('addons_wechat_aid'):$addons_wechat_aid;
                    unset($v['id']);
                    AddonsWechatTag::create($v);
                }else{
                    $v['id'] = $info['id'];
                    AddonsWechatTag::update($v);

                }

            }
            $this->success(lang('aysn success'));

        }

        $this->error(lang('invalid options'));

    }

    public function tagAdd()
    {
        if(Request::isPost()){
            $data  = $this->request->post();
            if($data){
                $data['store_id'] = $this->store_id;
                $this->validate($data,'AddonsWechatTag');

                $res = $this->wechatApp->user_tag->create($data['name']);
                $data['tag_id'] = $res['tag']['id'];
                if($res){
                    AddonsWechatTag::create($data);
                    $this->success(lang('add success'));
                }else{
                    $this->error(lang('add fail'));
                }

            }else{
                $this->error(lang('add fail'));
            }


        }
        $addons_wechat_aid = $this->request->get('addons_wechat_aid');
        $view = [
            'title'=>lang('add'),
            'info'=>['addons_wechat_aid'=>$addons_wechat_aid],
        ];

        View::assign($view);
        return view('tag_add');
    }

    public function tagEdit()
    {
        if(Request::isPost()){
            $data  = $this->request->post();
            if($data){
                $data['store_id'] = $this->store_id;
                $tag = AddonsWechatTag::find($data['id']);

                $res = $this->wechatApp->user_tag->update($tag['tag_id'],$data['name']);
                if($res['errcode']==0){
                    AddonsWechatTag::update($data);
                    $this->success(lang('edit success'));
                }else{
                    $this->error(lang('edit fail'));
                }

            }else{
                $this->error(lang('edit fail'));
            }
        }
        $id = $this->request->get('id');
        $info  = AddonsWechatTag::find($id);

        $view = [
            'title'=>'修改',
            'info'=>$info,
            'addons_wechat_aid'=>$info['addons_wechat_aid'],
        ];

        View::assign($view);
        return view('tag_add');

//        $this->wechatApp->user_tag->update($tagId, $name);
    }

    public function tagDel()
    {
        $id = $this->request->post('id');
        $info = AddonsWechatTag::find($id);
        $res = $this->wechatApp->user_tag->delete($info['tag_id']);
        if($res['errcode']==0){
            AddonsWechatTag::destroy($id);
        }else{
            $this->error(lang('delete fai'));
        }
        $this->success(lang('delete success'));

    }

    /**
     ************************历史消息管理***************************
     */

    public function message()
    {
        if(Request::isPost()){
            $keys = $this->request->post('keys','','trim');
            $page = $this->request->post('page') ? $this->request->post('page') : 1;
            $list=Db::name('addons_wechat_msg_history')
                ->where('store_id',$this->store_id)
                ->where('addons_wechat_aid',$this->wechatAccount->id)
                ->where('nickname','like','%'.$keys.'%')
                ->order('id desc')
                ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                ->toArray();

            return $result = ['code'=>0,'msg'=>'获取成功!','data'=>$list['data'],'count'=>$list['total']];
        }

        return view();
    }

    public function messageDel()
    {
        if(Request::isPost()){
            $id = $this->request->post('id');
            WxMsgHistory::destroy($id);
            $this->success(lang('delete success'));
        }

    }
    public function messageReply()
    {
        if(Request::isPost()){
            $material_id = $this->request->post('material_id');
            $openid = $this->request->post('openid');
            $msg_type = $this->request->post('msg_type');
            $material = AddonsWechatMaterial::find($material_id);
            if($material){
                $media_id = $material->media_id;

            }else{
                $media_id = '';
            }
            $message = AddonsWechatReply::where($this->where)->where('type','default')->value('data');

            switch ($msg_type) {
                case 'text':
                    $data = $this->request->post('data');
                    $message = new Text($data);
                    break;

                case 'image':
                    if(AddonsWechatMaterial::where('media_id',$media_id)->find()){

                        $message =  new Image($media_id);
                    }
                    break;

                case 'news':
                    $new = AddonsWechatMaterialInfo::where($this->where)->where('material_id', $material_id)->find();
                    if ($new) {
                        $newsList[] = new NewsItem([
                            'title' => $new->title,
                            'description' => $new->digest,
                            'url' => $new->url,
                            'image' => $new->cover,
                        ]);
                        $message = new News($newsList);
                    }else{
                        $message = AddonsWechatReply::where($this->where)->where('type','default')->value('data');

                    }
                    break;
                case 'video':
                    if(AddonsWechatMaterial::where('media_id',$media_id)->find()) {
                        $message =  new Video($media_id, $material->file_name, $material->des);
                    }
                    break;
                case 'voice':
                    if(AddonsWechatMaterial::where('media_id',$media_id)->find()) {

                        $message =  new Voice($media_id);
                    }
                    break;
                default:
                    break;
            }

            $result = $this->wechatApp->customer_service->message($message)->to($openid)->send();

            if ($result['errcode'] == 0) {
                $this->success(lang('send success'));
            } else {
                $this->error(lang('send fail'));

            }
        }else{
            $addons_wechat_aid  = $this->request->get('addons_wechat_aid');
            $id  = $this->request->get('id');
            $info = WxMsgHistory::where('store_id',$this->store_id)->find($id);
            $user = $this->wechatApp->user->get($info->openid);
            $materialGroup = $this->getMaterialGroup();
            $view = ['title'=>lang('reply'),'user'=>$user,'info'=>$info,'materialGroup'=>$materialGroup];
            View::assign($view);
            return view();
        }

    }

    /**
     ************************素材管理***************************
     */
    public function material(){

        if (Request::isPost()) {
            $addons_wechat_aid = $this->request->post('addons_wechat_aid');
            if(!$addons_wechat_aid){
                $addons_wechat_aid = $this->wechatAccount->id;
            }
            if(!$addons_wechat_aid){
                return $result = ['code' => 0,'msg' => lang('account is not accessed'),];

            }
            $keys = $this->request->post('keys','','trim');
            $page = $this->request->post('page') ? $this->request->post('page') : 1;
            $list=Db::name('addons_wechat_material')
                ->where('nickname','like','%'.$keys.'%')
                ->where('addons_wechat_aid',$addons_wechat_aid)
                ->order('fans_id desc')
                ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                ->toArray();
            return $result = ['code' => 0, 'msg' =>lang('get info success'), 'data' => $list['data'],'count'=>$list['total']];
        }
        $materialGroup = $this->getMaterialGroup();
        $view = [
            'title'=>lang('material'),
            'info'=>'',
            'materialGroup'=>$materialGroup,
        ];
        View::assign($view);
        return view();


    }
    //添加图文素材
    public function materialAdd(){
        if(Request::isPost()){
            $data = $this->request->post('content');

            foreach ($data as $k => $v) {
                $article= new Article($data[$k]);
                $articles[$k] = $article;
            }
            $res = $this->wechatApp->material->uploadArticle($articles);
            $this->showError($res);
            $AddonsWechatMaterialData = [
                'store_id'=>$this->store_id,
                'addons_wechat_aid'=>$this->wechatAccount->id,
                'type'=>'news',
                'media_id'=>$res['media_id'],
            ];

            $material =    $this->getMaterialByMediaId($res['media_id']);

            // 启动事务
            Db::startTrans();
            try {
                $mat= AddonsWechatMaterial::create($AddonsWechatMaterialData);
//                if(isset($data[0])){
                //多图文
                foreach ($data as $k=>$v) {

                    $data[$k]['cover'] = AddonsWechatMaterial::where('media_id', $data[$k]['thumb_media_id'])->value('media_url');
                    $data[$k]['local_cover'] = AddonsWechatMaterial::where('media_id', $data[$k]['thumb_media_id'])->value('local_cover');
                    $data[$k]['store_id'] = $this->store_id;
                    $data[$k]['addons_wechat_aid'] = $this->wechatAccount->id;
                    $data[$k]['url'] = $material['news_item'][$k]['url'];
                    $data[$k]['material_id'] = $mat->id;
                    $matinfo=  Db::name('AddonsWechatMaterialInfo')->save($data[$k]);

                }

                // 提交事务
                Db::commit();
                $this->success('成功');

            } catch (\Exception $e) {
                // 回滚事务
                Db::rollback();
                $this->error($e->getMessage());

            }
        }
        $params['name'] = 'container';
        $params['content'] = '';
        $view = [
            'info' => [],
            'title' => lang('add'),
            'ueditor'=>build_ueditor($params),
        ];
        View::assign($view);
        return view();
    }

    public function materialEdit(){
        if(Request::isPost()){
            $data = $this->request->post('content');
            $id = $this->request->post('mediaId');
            $mediaId = AddonsWechatMaterial::where('id', $id)->value('media_id');

            foreach ($data as $k => $v) {

                $article = new Article($data[$k]);

                $res = $this->wechatApp->material->updateArticle($mediaId, $article, $k);

            }

            $this->showError($res);

            $material =  $this->getMaterialByMediaId($mediaId);

            // 启动事务
            Db::startTrans();
            try {
//
                foreach ($data as $k=>$v) {
                    $data[$k]['id'] = AddonsWechatMaterialInfo::where($this->where)->where('thumb_media_id', $v['thumb_media_id'])->value('id');
                    $data[$k]['cover'] = AddonsWechatMaterial::where('media_id', $data[$k]['thumb_media_id'])->value('media_url');
                    $data[$k]['store_id'] = $this->store_id;
                    $data[$k]['addons_wechat_aid'] = $this->wechatAccount->id;
                    $data[$k]['url'] = $material['news_item'][$k]['url'];
                    $data[$k]['material_id'] = $id;
                    $data[$k]['update_time'] = time();
                    $AddonsWechatMaterialInfoModel = AddonsWechatMaterialInfo::find($data[$k]['id']);
                    $r[$k] = $AddonsWechatMaterialInfoModel->force()->save($data[$k]);
                }

                // 提交事务
                Db::commit();
                $this->success('成功');

            } catch (\Exception $e) {
                // 回滚事务
                Db::rollback();
                $this->error($e->getMessage());
            }
        }
        $id = $this->request->get('id');
        $info = AddonsWechatMaterialInfo::where('material_id',$id)->select()->toArray();
        $params['name'] = 'container';
        $params['content'] = '';
        $view = [
            'title'=>lang('edit'),
            'info'=>$info,
            'ueditor'=>build_ueditor($params),
        ];
        View::assign($view);

        return view('material_add');
    }

    //素材同步
    public function materialAysn(){
        if(Request::isPost()){
            $res = cache('materialList');
            if(!$res){
                $res = $this->wechatApp->material->list('news', 0, 50);
                cache('materialList',$res,3600);
            }
            $this->showError($res);
            foreach ($res['item'] as $k=>$v){
                $material = AddonsWechatMaterial::where('media_id',$v['media_id'])->find();
                if(!$material){
                    $material = ['store_id'=>$this->store_id,
                        'addons_wechat_aid'=>$this->wechatAccount->id,
                        'media_id'=>$v['media_id'],
                        'media_url'=>$v['content']['news_item'][0]['thumb_url'],
                        'type'=>"news",
                    ];
                    $wxmater = AddonsWechatMaterial::create($material);
                    foreach ($v['content']['news_item'] as $kk=>$vv){
                        $info = ['store_id'=>$this->store_id,
                            'addons_wechat_aid'=>$this->wechatAccount->addons_wechat_aid,
                            'material_id'=>$wxmater->id,
                            'thumb_media_id'=>$vv['thumb_media_id'],
                            'local_cover'=>$vv['thumb_url'],
                            'cover'=>$vv['thumb_url'],
                            'title'=>$vv['title'],
                            'author'=>$vv['author'],
                            'show_cover'=>$vv['show_cover_pic'],
                            'digest'=>$vv['digest'],
                            'content'=>$vv['content'],
                            'url'=>$vv['url'],
                            'content_source_url'=>$vv['content_source_url'],
                            'need_open_comment'=>$vv['need_open_comment'],
                            'only_fans_can_comment'=>$vv['only_fans_can_comment'],
                        ];
                        AddonsWechatMaterialInfo::create($info);

                    }
                }
            }
            $this->success(lang('aysn success'));

        }else{

            $this->error(lang('invalid request'));
        }


    }
    public function materialDel(){

        $id = $this->request->post('id');
        $material = AddonsWechatMaterial::find($id);
        //删除微信媒体库
        $this->wechatApp->material->delete($material->media_id);

        if($material['type']=='news'){
            $info = AddonsWechatMaterialInfo::where($this->where)->where('material_id',$id)->delete();
            if($info && $material->delete()){
                $this->success(lang('delete success'));
            }else{
                $this->error(lang('delete fail'));

            }
        }else{
            if($material->delete()){

                $this->success(lang('delete success'));
            }else{
                $this->error(lang('delete fail'));

            }
        }

    }
    // 发送消息
    public function materialSend(){
        if (Request::isPost()) {
            $id = $this->request->post('id');
            $info = AddonsWechatMaterial::find($id);
            $res = $this->sendAll($info);
            $this->showError($res);
            $this->success(lang('send success'));
        } else {
            $this->error(lang('send fail'));

        }

    }
    //预览消息

    public function materialPreview(){
        if(Request::isPost()){
            $wxname = $this->request->post('wxname');
            $id = $this->request->post('id');
            $info = AddonsWechatMaterial::find($id);
            $res = $this->preview($info,$wxname);

            $this->showError($res);
            $this->success(lang('send success'));

        }else{
            $this->error(lang('send fail'));

        }


    }

    protected function preview($info,$wxname){

        // 发送预览群发消息给指定的 openId 用户
        //$this->wechatApp->broadcasting->previewText($text, $openId);
        //$this->wechatApp->broadcasting->previewNews($mediaId, $openId);
        //$this->wechatApp->broadcasting->previewVoice($mediaId, $openId);
        //$this->wechatApp->broadcasting->previewImage($mediaId, $openId);
        //$this->wechatApp->broadcasting->previewVideo($message, $openId);
        //$this->wechatApp->broadcasting->previewCard($cardId, $openId);
        //发送预览群发消息给指定的微信号用户
        //$wxanme 是用户的微信号，比如：notovertrue
        //
        //$this->wechatApp->broadcasting->previewTextByName($text, $wxname);
        //$this->wechatApp->broadcasting->previewNewsByName($mediaId, $wxname);
        //$this->wechatApp->broadcasting->previewVoiceByName($mediaId, $wxname);
        //$this->wechatApp->broadcasting->previewImageByName($mediaId, $wxname);
        //$this->wechatApp->broadcasting->previewVideoByName($message, $wxname);
        //$this->wechatApp->broadcasting->previewCardByName($cardId, $wxname);

        $type = $info->type;
        switch ($type){
            case 'text':
                $res = $this->wechatApp->broadcasting->previewTextByName($info->media_id,$wxname);
                break;

            case 'image':

                $res = $this->wechatApp->broadcasting->previewImageByName($info->media_id, $wxname);

                break;

            case 'news':
                $res = $this->wechatApp->broadcasting->previewNewsByName($info->media_id, $wxname);

                break;
            case 'video':
                $res = $this->wechatApp->broadcasting->previewVideoByName($info->media_id, $wxname);


                break;
            case 'voice':
                $res = $this->wechatApp->broadcasting->previewVoiceByName($info->media_id, $wxname);
                break;
            case 'card':
                $res = $this->wechatApp->broadcasting->previewCardByName($info->media_id, $wxname);
                break;
            default:
                $res = $this->wechatApp->broadcasting->previewTextByName($info->media_id,$wxname);

                break;
        }

        return $res;

    }

    protected function sendAll($info){


        $type = $info->type;
        switch ($type){

            case 'image':

                $res = $this->wechatApp->broadcasting->sendImage($info->media_id);

                break;

            case 'news':
                $res = $this->wechatApp->broadcasting->sendNews($info->media_id);

                break;
            case 'video':
                $res = $this->wechatApp->broadcasting->sendVideo($info->media_id);


                break;
            case 'voice':
                $res = $this->wechatApp->broadcasting->sendVoice($info->media_id);
                break;
            case 'card':
                $res = $this->wechatApp->broadcasting->sendCard($info->media_id);
                break;
            default:
                $res = $this->wechatApp->broadcasting->image($info->media_id);

                break;
        }
        return $res;

    }


    /**
     ************************二维码设置**************************
     */
    public function qrcode(){
        if (Request::isPost()) {
            $list = Db::name('addons_wechat_qrcode')->select()->toArray();
            return $result = ['code' => 0, 'msg' =>lang('get info success'), 'data' => $list,];
        }
        return view();
    }

    public function qrcodeAdd(){
        if(Request::isPost()){
            $data = Request::param();
            if($data['type']==0){
                $data['expire_seconds'] = $data['expire_seconds']?$data['expire_seconds']:2592000;
                $res = $this->wechatApp->qrcode->temporary('foo',$data['expire_seconds']);
            }else{
                $res = $this->wechatApp->qrcode->forever('foo');// 或者 $app->qrcode->forever(56);
            }
            $this->showError($res);
            $data['store_id'] = $this->wechatAccount->id;
            $data['addons_wechat_aid'] = $this->store_id;
            $data['ticket'] = $res['ticket'];
            $data['url'] = $res['url'];
            $data['qrcode'] = $url = $this->wechatApp->qrcode->url($res['ticket']);
            if(Db::name('addons_wechat_qrcode')->insert($data)){
                $this->success(lang('add success'));
            }else{
                $this->error(lang('add fail'));
            }

        }
        $view = ['title'=>lang('add'),
            'info'=>''];
        View::assign($view);
        return view();
    }


    public function qrcodeState(){
        if(Request::isPost()){
            $id = Request::param('id');
            $qr = Db::name('addons_wechat_qrcode')->find($id);
            $status = $qr['status']==1?0:1;

            $res = Db::name('addons_wechat_qrcode')->where('id',$qr['id'])->update(['status'=>$status]);
            if($res){
                $this->success(lang('edit success'));
            }else{
                $this->error(lang('edit fail'));
            }
        }
        $view = ['title'=>lang('add'),
            'info'=>''];
        View::assign($view);
        return view();
    }

    public function qrcodeDel(){
        if(Request::isPost()) {
            $id = Request::param('id');
            $res = Db::name('addons_wechat_qrcode')->delete($id);
            if($res){
                $this->success(lang('delete success'));
            }else{
                $this->error(lang('delete fail'));
            }
        }
    }


    /**
     ************************回复设置***************************
     */
    public function reply(){

        $type = $this->request->get('type','default');
        $typeList = [
            [
                'url' => url('reply',['type'=>'default']),
                'item' => "默认回复",
                "type" => 'default'
            ],
            [    'url' => url('reply',['type'=>'subscribe']),
                'item' => "关注回复",
                "type" => 'subscribe'
            ],

            [ 'url' => url('reply',['type'=>'keyword']),
                'item' => "关键字回复",
                "type" =>'keyword'
            ],

        ];


        if ($type == 'default') {

            $info = Db::name('addons_wechat_reply')
                ->where($this->where)
                ->where('type', $type)
                ->select();
        } elseif ($type == 'subscribe') {
            $info = Db::name('addons_wechat_reply')
                ->where($this->where)
                ->where('type' ,$type)
                ->select
                ();

        } elseif($type == 'keyword') {
            $info = Db::name('addons_wechat_reply') ->where($this->where)
                ->where('type' ,$type)
                ->select();
        }
        $view = [
            'title'=>'粉丝',
            'type'=>$type,
            'info' =>$info,
            'typeList'=>$typeList,
        ];
        View::assign($view);
        return view();


    }

    public function replyAdd(){

        if(Request::isPost()){
            $data = $this->request->post();
            $data['store_id'] = $this->store_id;
            $data['addons_wechat_aid'] = $this->wechatAccount->id;
            if(!$data['type']){
                $data['type']='keyword';
            }
            if($data['data']){
                $data['msg_type'] ='text';
            }
            $res = AddonsWechatReply::create($data);
            if ($res) {
                $this->success(lang('add success'),url('index'));
            } else {
                $this->error(lang('add fail'));
            }
        }

        $view = [
            'info' => [],
            'title' => lang('add'),
            'materialGroup' => $this->getMaterialGroup(),

        ];
        View::assign($view);
        return view();

    }

    public function replyEdit(){
        if (Request::isPost()) {
            $data = $this->request->post();
            $data['store_id'] = $this->store_id;
            $data['addons_wechat_aid'] = $this->wechatAccount->id;
            $res = AddonsWechatReply::update($data);
            if ($res) {
                $this->success(lang('edit success'),url('index'));
            } else {
                $this->error(lang('edit fail'));
            }
        }
        $info = AddonsWechatReply::find($this->request->get('id'));
        $view = [
            'info' => $info,
            'title' => lang('edit'),
            'materialGroup' => $this->getMaterialGroup(),
        ];
        View::assign($view);
        return view('reply_add');

    }
    public function replyDel(){

        $id = $this->request->post('id');
        AddonsWechatReply::destroy($id);
        $this->success(lang('delete success'));

    }



    /**
     ************************接口返回***************************
     */

    //获取素材
    public function getMaterialByType(){
        $type = $this->request->post('type');
//      $type text 素材的类型，图片（image）、视频（video）、语音 （voice）、图文（news）

//      $res = $this->wechatApp->material->list($type,0,100);
        $res =  AddonsWechatMaterial::where($this->where)->where('type',$type)
            ->where($this->where)->select()->toArray();
        if($type=='news'){
            foreach ($res as $k=>$v){
                $res[$k]['groupList'] = AddonsWechatMaterialInfo::where($this->where)->where('material_id',$v['id'])->select()->toArray();
            }
        }
        $this->success(lang('get info success'),'',$res);


    }

    /**
     * @param $type
     * @param int $id
     * @return array|\think\Collection|\think\Model|null
     * 获取素材
     */
    protected function getMaterialGroup(){
        $materialGroup = [];
        foreach ($this->materialType as $k=>$v){
            if($v=='news'){

                $weixin_material_info = Db::name('addons_wechat_material')->where('type','news')->select()->toArray();
                if (!empty($weixin_material_info)) {
                    foreach($weixin_material_info as $key=>$value){

                        $item_info = Db::name('addons_wechat_material_info')->where('material_id' , $value['id'])->select()->toArray();
                        $weixin_material_info[$key]['item_info'] = $item_info;
                    }
                }
                $materialGroup[$v] = $weixin_material_info;

            }else{

                $weixin_material_info = Db::name('addons_wechat_material')->where('type',$v)->select()->toArray();

                $materialGroup[$v] = $weixin_material_info;

            }
        }
        return $materialGroup;

    }

    /**
     ********************************上传素材接口***************************************
     */

    protected function uploads($type,$uploadPath='uploads'){

        //获取上传文件表单字段名
        $fileKey = array_keys(request()->file());
        for ($i = 0; $i < count($fileKey); $i++) {
            //获取表单上传文件
            $file = request()->file($fileKey[$i]);
            try {
                validate($type)->check(DataHelper::objToArray($file));
//                validate(syscfg('upload','upload_type'))->check($file);
                $savename = \think\facade\Filesystem::disk('public')->putFile($uploadPath, $file);
                $path[] = '/storage/' . $savename;
            } catch (\think\exception\ValidateException $e) {
                $path = '';
                $error = $e->getMessage();
            }
        }
        if (!empty($path)) {
            $result['code'] = 1;
            //分辨是否截图上传，截图上传只能上传一个，非截图上传可以上传多个
            if (Request::param('responseType') == 'json') {
                $result["url"] = $path[0];
            } else {
                $result["url"] = $path[0];
            }
            $result['msg'] = lang('upload success');
            return $result;
        } else {
            //上传失败获取错误信息
            $result['url'] = '';
            $result['msg'] = $error;
            $result['code'] = 0;
            return $result;
        }


    }
    public function imageUpload(){

        $res = $this->uploads($this->imageValidate);
        if($res['code']>0){
            //路劲用相对路径
            $result = $this->wechatApp->material->uploadImage('./'.$res['url']);
            $this->showError($result);
            $data  = [
                'store_id'=> $this->store_id,
                'wechat_aid'=> $this->wechatAccount->id,
                'media_id'=> $result['media_id'],
                'media_url'=> $result['url'],
                'local_cover'=> $res['url'],
                'type'=> 'image',
            ];

            $r = AddonsWechatMaterial::create($data);
            if($r){
                $this->success(lang('upload success'),'',$result);
            }else{
                $this->error('上传失败');

            }
        }else{
            $this->error('上传失败');

        }
    }

    public function videoUpload(){
        $data = $this->request->post();
        if(!$data['url'] || !$data['file_name'] || !$data['des']){
            $this->error('数据不能为空');
        }
        $result = $this->wechatApp->material->uploadVideo('.'.$data['url'],$data['file_name'],$data['des']);
        $this->showError($result);
        $resource = $this->wechatApp->material->get($result['media_id']);
        $datas  = [
            'store_id'=> $this->store_id,
            'addons_wechat_aid'=> $this->wechatAccount->id,
            'media_id'=> $result['media_id'],
            'media_url'=> $resource['down_url'],
            'local_cover'=> $data['url'],
            'type'=> 'video',
            'file_name'=> $data['file_name'],
            'des'=> $data['des'],
        ];
        $result['url'] = $resource['down_url'];

        $r = AddonsWechatMaterial::create($datas);
        if($r){
            $this->success(lang('upload success'),'',$result);
        }else{
            $this->error('上传失败');

        }


    }

    public function voiceUpload(){
        $res = $this->uploads($this->voiceValidate);
        if($res['code']>0){
            //路劲用相对路径
            $result = $this->wechatApp->material->uploadVoice('./'.$res['url']);
            $this->showError($result);
            $resource = $this->wechatApp->material->get($result['media_id']);

            $data  = [
                'store_id'=> $this->store_id,
                'addons_wechat_aid'=> $this->wechatAccount->id,
                'media_id'=> $result['media_id'],
                'media_url'=> $resource['down_url'],
                'local_cover'=> $res['url'],

                'type'=> 'image',
            ];
            $result['url'] = $resource['down_url'];
            $r = AddonsWechatMaterial::create($data);
            if($r){
                $this->success(lang('upload success'),'',$result);
            }else{
                $this->error('上传失败');

            }
        }else{
            $this->error('上传失败');

        }

    }


    public function thumbUpload(){
        $res = $this->uploads($this->thumbValidate);
        if($res['code']>0){
            //路劲用相对路径
            $result = $this->wechatApp->material->uploadThumb('./'.$res['url']);
            $this->showError($result);
            $data  = [
                'store_id'=> $this->store_id,
                'addons_wechat_aid'=> $this->wechatAccount->id,
                'media_id'=> $result['media_id'],
                'media_url'=> $result['url'],
                'local_cover'=> $res['url'],
                'type'=> 'image',
            ];

            $r = AddonsWechatMaterial::create($data);
            if($r){
                $this->success(lang('upload success'),$result['url']);
            }else{
                $this->error(lang('upload fail'));

            }
        }else{
            $this->error(lang('upload fail'));

        }


    }

    public function UeditUploadImage(){

        $res = $this->uploads($this->imageValidate);
        if($res['code']>0){
            //路劲用相对路径
            $result = $this->wechatApp->material->uploadImage('./'.$res['url']);
            $this->showError($result);
            $data  = [
                'store_id'=> $this->store_id,
                'addons_wechat_aid'=> $this->wechatAccount->id,
                'media_id'=> $result['media_id'],
                'media_url'=> $result['url'],
                'local_cover'=> $res['url'],
                'type'=> 'image',
            ];

            $r = AddonsWechatMaterial::create($data);
            $data = ['state'=>'SUCCESS','url'=>$data['media_url']];

        }else{
            $data = ['state'=>'SUCCESS','url'=>''];

        }
        return json($data);

    }

    public function UeditUploadVideo(){
        $res = $this->uploads($this->videoValidate);

        if($res['code']>0){
            //路劲用相对路径
            $result = $this->wechatApp->material->uploadVideo('./'.$res['url'],$res['url'],$res['url']);
            $this->showError($result);
            $resource = $this->wechatApp->material->get($result['media_id']);

            $data  = [
                'store_id'=> $this->store_id,
                'addons_wechat_aid'=> $this->wechatAccount->id,
                'media_id'=> $result['media_id'],
                'media_url'=> $resource['down_url'],
                'local_cover'=> $res['url'],
                'type'=> 'video',
                'file_name'=> $res['url'],
                'des'=> $res['url'],
            ];
            $result['url'] = $resource['down_url'];
            $r = AddonsWechatMaterial::create($data);

            $data = ['state'=>'SUCCESS','url'=>$resource['down_url']];
        }else{
            $data = ['state'=>'SUCCESS','url'=>''];

        }
        return json_encode($data);

    }

    public function UeditUploaVoice(){

        $res = $this->uploads($this->voiceValidate);

        if($res['code']>0){
            //路劲用相对路径
            $result = $this->wechatApp->material->uploadVoice('./'.$res['url']);
            $this->showError($result);
            $resource = $this->wechatApp->material->get($result['media_id']);

            $data  = [
                'store_id'=> $this->store_id,
                'addons_wechat_aid'=> $this->wechatAccount->id,
                'media_id'=> $result['media_id'],
                'media_url'=> $resource['down_url'],
                'local_cover'=> $res['url'],
                'type'=> 'image',
            ];
            $result['url'] = $resource['down_url'];
            $r = AddonsWechatMaterial::create($data);

            $data = ['state'=>'SUCCESS','url'=>$resource['down_url']];
        }else{
            $data = ['state'=>'SUCCESS','url'=>''];

        }
        return json_encode($data);
    }
    public function getListImage(){
        $list = AddonsWechatMaterial::where($this->where)->where('type','image')->select();
        $data = ['state'=>'SUCCESS','start'=>0,'total'=>count($list),'list'=>[]];
        if($list){
            foreach ($list as $k=>$v) {
                $data['list'][$k]['url'] = $v['media_url'];
                $data['list'][$k]['mtime'] = time();
            }
        }

        return json_encode($data);

    }
    // 微信返回数据
    protected  function showError($res){
        if(isset($res['errcode']) && $res['errcode']>0){
            $this->error($res['errmsg']);
        }

    }

    //获取媒体素材
    protected function getMaterialByMediaId($mediaId){
        $resource = $this->wechatApp->material->get($mediaId);
        $this->showError($resource);
        return $resource;

    }
}