<?php
/**
 * SpeedAdmin
 * ============================================================================
 * 版权所有 2018-2027 SpeedAdmin，并保留所有权利。
 * 网站地址: https://www.SpeedAdmin.cn
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/9/21
 */

namespace app\common\controller;

use app\BaseController;
use app\common\traits\Jump;
use think\captcha\facade\Captcha;
use think\facade\Request;
use think\facade\Cookie;
use think\Validate;

class Base extends BaseController
{
    use Jump;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

    }

    public function enlang()
    {
        $lang = Request::get('lang');
        switch ($lang) {
            case 'zh-cn':
                Cookie::set('think_lang', 'zh-cn');
                break;
            case 'en-us':
                Cookie::set('think_lang', 'en-us');
                break;
            default:
                Cookie::set('think_lang', 'zh-cn');
                break;
        }
        $this->success('切换成功');
    }

    /**
     * @return \think\Response
     */
    public function verify()
    {

        return Captcha::create();
    }

    protected function validate(array $data, $validate, array $message = [], bool $batch = false)
    {
        try {
            parent::validate($data, $validate, $message, $batch);
            $this->checkToken();
        } catch (\Exception $e) {
            $this->error($e->getMessage());
        }
        return true;
    }

    /**
     * 检测token 并刷新
     *
     */
    protected function checkToken(){
        $check = $this->request->checkToken('__token__', $this->request->param());
        if(false === $check) {
            $this->error(lang('Token verify error'),'',['__token__'=>$this->request->buildToken('__token__', 'sha1')]);
        }
    }
}