<?php
/**
 * SpeedAdmin
 * ============================================================================
 * 版权所有 2018-2027 SpeedAdmin，并保留所有权利。
 * 网站地址: https://www.SpeedAdmin.cn
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/9/21
 */


namespace app\common\controller;

use app\BaseController;
use think\facade\Request;
use think\facade\Cookie;
class Frontend extends CommonController
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }




}