<?php
/**
 * lemocms
 * ============================================================================
 * 版权所有 2018-2027 lemocms，并保留所有权利。
 * 网站地址: https://www.lemocms.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/8/2
 */
namespace app\cms\controller;
use app\common\controller\Frontend;
use app\common\model\Addon;
use think\facade\View;

class Error extends Frontend {

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $config = Addon::where('name','cms')->cache(3600)->find();
        $this->cmsConfig = $cmsConfig = unserialize($config->config);
        $seo  = $cmsConfig['seo']['value'];
        $logo  = $cmsConfig['logo']['value'];
        View::assign('seo',$seo);
        View::assign('logo',$logo);
    }

    public function err()
    {
        return view('404');
    }

    public function notice()
    {
        return view();
    }


}