<?php
/**
 * lemocms
 * ============================================================================
 * 版权所有 2018-2027 lemocms，并保留所有权利。
 * 网站地址: https://www.lemocms.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/11/27
 */
namespace app\bbs\controller;

use app\common\model\User as UserModel;
use app\common\model\BbsMessage as MessModel;
class Message extends Comm {

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    public function remove()
    {
        if (input('all')) {
            $res = MessModel::where('receive_id', session('user.id'))->delete();
            if ($res) {
                $this->success('清空成功');
            } else {
                $this->error('清空失败');
            }

        } else {
            $id = input('id');
            $res = MessModel::destroy($id);
            if ($res) {
                $this->success('删除成功');
            } else {
                $this->error('删除失败');
            }
        }
    }
}