-- 独立 maintenance contract；普通 MigrationService 不扫描本目录。
-- 本文件由 MaintenanceContractService 解析受控 CONTRACT 声明，并逐表执行实际 DROP COLUMN。
-- 每项同时保留 information_schema 守卫与可审计 DDL；执行前服务会校验 Laravel 对应列及数据一致性。
SET @schema_name = DATABASE();

-- CONTRACT table=fun_admin legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_admin` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_admin legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_admin` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_admin legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_admin` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_admin_log legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_admin_log` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_admin_log legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_admin_log` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_admin_log legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_admin_log` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_admin_menu legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_menu' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_menu' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_admin_menu` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_admin_menu legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_menu' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_menu' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_admin_menu` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_admin_menu legacy=sort modern=sort_order
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_menu' AND COLUMN_NAME='sort') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_menu' AND COLUMN_NAME='sort_order'),'ALTER TABLE `fun_admin_menu` DROP COLUMN `sort`','DO 0');
-- CONTRACT table=fun_attach legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_attach` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_attach legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_attach` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_attach legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_attach` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_attach legacy=sort modern=sort_order
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach' AND COLUMN_NAME='sort') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach' AND COLUMN_NAME='sort_order'),'ALTER TABLE `fun_attach` DROP COLUMN `sort`','DO 0');
-- CONTRACT table=fun_attach_group legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach_group' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach_group' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_attach_group` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_attach_group legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach_group' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach_group' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_attach_group` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_attach_group legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach_group' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach_group' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_attach_group` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_attach_group legacy=sort modern=sort_order
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach_group' AND COLUMN_NAME='sort') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach_group' AND COLUMN_NAME='sort_order'),'ALTER TABLE `fun_attach_group` DROP COLUMN `sort`','DO 0');
-- CONTRACT table=fun_auth_group legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_auth_group` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_auth_group legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_auth_group` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_auth_group legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_auth_group` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_auth_group_department legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group_department' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group_department' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_auth_group_department` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_auth_group_inherit legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group_inherit' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group_inherit' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_auth_group_inherit` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_member_group_relation legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_group_relation' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_group_relation' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_member_group_relation` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_blacklist legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_blacklist' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_blacklist' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_blacklist` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_blacklist legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_blacklist' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_blacklist' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_blacklist` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_blacklist legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_blacklist' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_blacklist' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_blacklist` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_config legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_config` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_config legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_config` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_config legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_config` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_config_group legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config_group' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config_group' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_config_group` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_config_group legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config_group' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config_group' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_config_group` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_config_group legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config_group' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config_group' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_config_group` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_department legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_department' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_department' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_department` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_department legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_department' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_department' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_department` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_department legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_department' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_department' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_department` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_department legacy=sort modern=sort_order
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_department' AND COLUMN_NAME='sort') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_department' AND COLUMN_NAME='sort_order'),'ALTER TABLE `fun_department` DROP COLUMN `sort`','DO 0');
-- CONTRACT table=fun_dict_item legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_item' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_item' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_dict_item` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_dict_item legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_item' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_item' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_dict_item` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_dict_item legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_item' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_item' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_dict_item` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_dict_item legacy=sort modern=sort_order
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_item' AND COLUMN_NAME='sort') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_item' AND COLUMN_NAME='sort_order'),'ALTER TABLE `fun_dict_item` DROP COLUMN `sort`','DO 0');
-- CONTRACT table=fun_dict_type legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_type' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_type' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_dict_type` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_dict_type legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_type' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_type' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_dict_type` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_dict_type legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_type' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_type' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_dict_type` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_dict_type legacy=sort modern=sort_order
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_type' AND COLUMN_NAME='sort') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_type' AND COLUMN_NAME='sort_order'),'ALTER TABLE `fun_dict_type` DROP COLUMN `sort`','DO 0');
-- CONTRACT table=fun_field_type legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_field_type' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_field_type' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_field_type` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_field_type legacy=sort modern=sort_order
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_field_type' AND COLUMN_NAME='sort') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_field_type' AND COLUMN_NAME='sort_order'),'ALTER TABLE `fun_field_type` DROP COLUMN `sort`','DO 0');
-- CONTRACT table=fun_field_verify legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_field_verify' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_field_verify' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_field_verify` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_languages legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_languages' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_languages' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_languages` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_languages legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_languages' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_languages' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_languages` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_languages legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_languages' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_languages' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_languages` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_member legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_member` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_member legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_member` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_member legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_member` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_member_group legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_group' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_group' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_member_group` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_member_group legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_group' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_group' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_member_group` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_member_group legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_group' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_group' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_member_group` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_member_level legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_level' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_level' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_member_level` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_member_level legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_level' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_level' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_member_level` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_member_level legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_level' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_level' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_member_level` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_member_level legacy=sort modern=sort_order
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_level' AND COLUMN_NAME='sort') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_level' AND COLUMN_NAME='sort_order'),'ALTER TABLE `fun_member_level` DROP COLUMN `sort`','DO 0');
-- CONTRACT table=fun_permission legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_permission' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_permission' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_permission` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_permission legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_permission' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_permission' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_permission` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_permission legacy=sort modern=sort_order
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_permission' AND COLUMN_NAME='sort') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_permission' AND COLUMN_NAME='sort_order'),'ALTER TABLE `fun_permission` DROP COLUMN `sort`','DO 0');
-- CONTRACT table=fun_plugin legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_plugin` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_plugin legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_plugin` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_plugin legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_plugin` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_plugin_operation legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_operation' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_operation' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_plugin_operation` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_plugin_operation legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_operation' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_operation' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_plugin_operation` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_plugin_version_history legacy=create_time modern=created_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_version_history' AND COLUMN_NAME='create_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_version_history' AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_plugin_version_history` DROP COLUMN `create_time`','DO 0');
-- CONTRACT table=fun_plugin_version_history legacy=update_time modern=updated_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_version_history' AND COLUMN_NAME='update_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_version_history' AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_plugin_version_history` DROP COLUMN `update_time`','DO 0');
-- CONTRACT table=fun_provinces legacy=delete_time modern=deleted_at
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_provinces' AND COLUMN_NAME='delete_time') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_provinces' AND COLUMN_NAME='deleted_at'),'ALTER TABLE `fun_provinces` DROP COLUMN `delete_time`','DO 0');
-- CONTRACT table=fun_provinces legacy=sort modern=sort_order
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_provinces' AND COLUMN_NAME='sort') AND EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_provinces' AND COLUMN_NAME='sort_order'),'ALTER TABLE `fun_provinces` DROP COLUMN `sort`','DO 0');
