#define _POSIX_C_SOURCE 200809L
#include <errno.h>
#include <fcntl.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/stat.h>
#include <unistd.h>

#ifndef O_DIRECTORY
#error "O_DIRECTORY is required for fail-closed safe commit"
#endif
#ifndef O_NOFOLLOW
#error "O_NOFOLLOW is required for fail-closed safe commit"
#endif

typedef struct { uint32_t h[8]; uint64_t bits; unsigned char block[64]; size_t used; } sha256_ctx;
static const uint32_t k[64] = {
    0x428a2f98,0x71374491,0xb5c0fbcf,0xe9b5dba5,0x3956c25b,0x59f111f1,0x923f82a4,0xab1c5ed5,
    0xd807aa98,0x12835b01,0x243185be,0x550c7dc3,0x72be5d74,0x80deb1fe,0x9bdc06a7,0xc19bf174,
    0xe49b69c1,0xefbe4786,0x0fc19dc6,0x240ca1cc,0x2de92c6f,0x4a7484aa,0x5cb0a9dc,0x76f988da,
    0x983e5152,0xa831c66d,0xb00327c8,0xbf597fc7,0xc6e00bf3,0xd5a79147,0x06ca6351,0x14292967,
    0x27b70a85,0x2e1b2138,0x4d2c6dfc,0x53380d13,0x650a7354,0x766a0abb,0x81c2c92e,0x92722c85,0xa2bfe8a1,
    0xa81a664b,0xc24b8b70,0xc76c51a3,0xd192e819,0xd6990624,0xf40e3585,0x106aa070,0x19a4c116,
    0x1e376c08,0x2748774c,0x34b0bcb5,0x391c0cb3,0x4ed8aa4a,0x5b9cca4f,0x682e6ff3,0x748f82ee,
    0x78a5636f,0x84c87814,0x8cc70208,0x90befffa,0xa4506ceb,0xbef9a3f7,0xc67178f2
};
static uint32_t rr(uint32_t x,unsigned n){return(x>>n)|(x<<(32-n));}
static void sha_block(sha256_ctx*c,const unsigned char*p){uint32_t w[64],a,b,d,e,f,g,h,t1,t2,cc;for(int i=0;i<16;i++)w[i]=((uint32_t)p[i*4]<<24)|((uint32_t)p[i*4+1]<<16)|((uint32_t)p[i*4+2]<<8)|p[i*4+3];for(int i=16;i<64;i++){uint32_t x=w[i-15],y=w[i-2];w[i]=(rr(x,7)^rr(x,18)^(x>>3))+w[i-16]+(rr(y,17)^rr(y,19)^(y>>10))+w[i-7];}a=c->h[0];b=c->h[1];cc=c->h[2];d=c->h[3];e=c->h[4];f=c->h[5];g=c->h[6];h=c->h[7];for(int i=0;i<64;i++){t1=h+(rr(e,6)^rr(e,11)^rr(e,25))+((e&f)^((~e)&g))+k[i]+w[i];t2=(rr(a,2)^rr(a,13)^rr(a,22))+((a&b)^(a&cc)^(b&cc));h=g;g=f;f=e;e=d+t1;d=cc;cc=b;b=a;a=t1+t2;}c->h[0]+=a;c->h[1]+=b;c->h[2]+=cc;c->h[3]+=d;c->h[4]+=e;c->h[5]+=f;c->h[6]+=g;c->h[7]+=h;}
static void sha_init(sha256_ctx*c){uint32_t x[8]={0x6a09e667,0xbb67ae85,0x3c6ef372,0xa54ff53a,0x510e527f,0x9b05688c,0x1f83d9ab,0x5be0cd19};memcpy(c->h,x,sizeof x);c->bits=0;c->used=0;}
static void sha_update(sha256_ctx*c,const unsigned char*p,size_t n){c->bits+=(uint64_t)n*8;while(n){size_t z=64-c->used;if(z>n)z=n;memcpy(c->block+c->used,p,z);c->used+=z;p+=z;n-=z;if(c->used==64){sha_block(c,c->block);c->used=0;}}}
static void sha_final(sha256_ctx*c,unsigned char out[32]){c->block[c->used++]=0x80;if(c->used>56){while(c->used<64)c->block[c->used++]=0;sha_block(c,c->block);c->used=0;}while(c->used<56)c->block[c->used++]=0;for(int i=7;i>=0;i--)c->block[c->used++]=(unsigned char)(c->bits>>(i*8));sha_block(c,c->block);for(int i=0;i<8;i++){out[i*4]=c->h[i]>>24;out[i*4+1]=c->h[i]>>16;out[i*4+2]=c->h[i]>>8;out[i*4+3]=c->h[i];}}
static int hash_fd(int fd,char hex[65]){sha256_ctx c;unsigned char b[8192],d[32];ssize_t n;sha_init(&c);if(lseek(fd,0,SEEK_SET)<0)return-1;while((n=read(fd,b,sizeof b))>0)sha_update(&c,b,(size_t)n);if(n<0)return-1;sha_final(&c,d);for(int i=0;i<32;i++)sprintf(hex+i*2,"%02x",d[i]);hex[64]=0;return 0;}

static int valid_relative(const char*p){if(!p||!*p||*p=='/'||strstr(p,"//"))return 0;char*copy=strdup(p),*save=NULL,*part;if(!copy)return 0;for(part=strtok_r(copy,"/",&save);part;part=strtok_r(NULL,"/",&save)){if(!strcmp(part,".")||!strcmp(part,"..")||!*part){free(copy);return 0;}}free(copy);return 1;}
static int open_absolute_dir(const char*path){if(!path||*path!='/')return-1;int fd=open("/",O_RDONLY|O_DIRECTORY|O_NOFOLLOW);char*copy=strdup(path),*save=NULL,*part;if(fd<0||!copy){if(fd>=0)close(fd);free(copy);return-1;}for(part=strtok_r(copy,"/",&save);part;part=strtok_r(NULL,"/",&save)){int next=openat(fd,part,O_RDONLY|O_DIRECTORY|O_NOFOLLOW);close(fd);if(next<0){free(copy);return-1;}fd=next;}free(copy);return fd;}
static int open_parent(int root,const char*path,char**leaf){char*copy=strdup(path),*slash;if(!copy)return-1;slash=strrchr(copy,'/');*leaf=strdup(slash?slash+1:copy);if(!*leaf){free(copy);return-1;}if(!slash){free(copy);return dup(root);}*slash=0;int fd=dup(root);char*save=NULL,*part;for(part=strtok_r(copy,"/",&save);part;part=strtok_r(NULL,"/",&save)){int next=openat(fd,part,O_RDONLY|O_DIRECTORY|O_NOFOLLOW);close(fd);if(next<0){free(copy);return-1;}fd=next;}free(copy);return fd;}
static int same_parent_binding(int root,const char*path,int held){char*leaf=NULL;int reopened=open_parent(root,path,&leaf);free(leaf);if(reopened<0)return 0;struct stat a,b;int ok=fstat(held,&a)==0&&fstat(reopened,&b)==0&&a.st_dev==b.st_dev&&a.st_ino==b.st_ino;close(reopened);return ok;}
static int binding(int fd,char out[96]){struct stat st;if(fstat(fd,&st)<0)return-1;snprintf(out,96,"%llu:%llu",(unsigned long long)st.st_dev,(unsigned long long)st.st_ino);return 0;}
static int regular_hash_at(int dir,const char*name,char out[65]){struct stat st;int fd=openat(dir,name,O_RDONLY|O_NOFOLLOW);if(fd<0)return-1;int ok=fstat(fd,&st)==0&&S_ISREG(st.st_mode)&&hash_fd(fd,out)==0;close(fd);return ok?0:-1;}
static void result(int ok,const char*code,const char*message,const char*phase,int renamed,const char*hash,const char*parent){printf("{\"ok\":%s,\"code\":\"%s\",\"message\":\"%s\",\"phase\":\"%s\",\"renamed\":%s",ok?"true":"false",code,message,phase,renamed?"true":"false");if(hash)printf(",\"hash\":\"%s\"",hash);if(parent)printf(",\"target_parent\":\"%s\"",parent);printf("}\n");}
#ifdef FUNADMIN_CRUD_HELPER_TEST_BUILD
static void test_swap(int root){const char*spec=getenv("FUNADMIN_CRUD_HELPER_TEST_SWAP_PARENT");if(!spec)return;char*copy=strdup(spec),*sep=copy?strchr(copy,':'):NULL;if(!sep){free(copy);return;}*sep=0;char hold[96];snprintf(hold,sizeof hold,".crud-helper-swap-%ld",(long)getpid());if(renameat(root,copy,root,hold)==0&&renameat(root,sep+1,root,copy)<0)renameat(root,hold,root,copy);free(copy);}
static int fail_after(const char*point){const char*value=getenv("FUNADMIN_CRUD_HELPER_TEST_FAIL_AFTER_RENAME");return value&&strcmp(value,point)==0;}
#else
static void test_swap(int root){(void)root;}
static int fail_after(const char*point){(void)point;return 0;}
#endif

static int commit_op(int root,const char*source,const char*target,const char*backup,const char*old_hash,const char*new_hash){int srcdir=-1,dstdir=-1,bakdir=-1,srcfd=-1,dstfd=-1;char*srcname=NULL,*dstname=NULL,*bakname=NULL;char hash[65],parent[96];struct stat st;int backed=0,renamed=0;srcdir=open_parent(root,source,&srcname);dstdir=open_parent(root,target,&dstname);if(srcdir<0||dstdir<0){result(0,"PARENT_UNSAFE","无法以 nofollow 打开提交父目录","pre_rename",0,NULL,NULL);goto fail;}if(binding(dstdir,parent)<0){result(0,"PARENT_UNSAFE","无法绑定目标父目录","pre_rename",0,NULL,NULL);goto fail;}if(strcmp(backup,"-")){bakdir=open_parent(root,backup,&bakname);if(bakdir<0){result(0,"BACKUP_PARENT_UNSAFE","无法安全打开备份父目录","pre_rename",0,NULL,parent);goto fail;}}dstfd=openat(dstdir,dstname,O_RDONLY|O_NOFOLLOW);if(dstfd>=0){if(fstat(dstfd,&st)<0||!S_ISREG(st.st_mode)||hash_fd(dstfd,hash)<0||!strcmp(old_hash,"-")||strcmp(hash,old_hash)){result(0,"OLD_HASH_MISMATCH","目标文件 hash 已变化","pre_rename",0,NULL,parent);goto fail;}}else if(errno!=ENOENT||strcmp(old_hash,"-")){result(0,"OLD_HASH_MISMATCH","目标文件状态与计划不符","pre_rename",0,NULL,parent);goto fail;}srcfd=openat(srcdir,srcname,O_RDONLY|O_NOFOLLOW);if(srcfd<0||fstat(srcfd,&st)<0||!S_ISREG(st.st_mode)||hash_fd(srcfd,hash)<0||strcmp(hash,new_hash)){result(0,"STAGE_HASH_MISMATCH","暂存文件 hash 不匹配","pre_rename",0,NULL,parent);goto fail;}if(fsync(srcfd)<0){result(0,"FSYNC_FAILED","暂存文件 fsync 失败","pre_rename",0,NULL,parent);goto fail;}test_swap(root);if(!same_parent_binding(root,target,dstdir)){result(0,"PARENT_CHANGED","父目录绑定已变化","pre_rename",0,NULL,parent);goto fail;}if(dstfd>=0){if(renameat(dstdir,dstname,bakdir,bakname)<0){result(0,"BACKUP_RENAME_FAILED","无法将旧文件移入安全 staging","pre_rename",0,NULL,parent);goto fail;}backed=1;if(fsync(bakdir)<0||fsync(dstdir)<0){if(renameat(bakdir,bakname,dstdir,dstname)<0)result(0,"BACKUP_AND_RESTORE_FAILED","备份落盘失败且旧文件恢复失败","pre_rename",0,NULL,parent);else{fsync(dstdir);result(0,"BACKUP_FSYNC_FAILED","安全 staging 备份落盘失败","pre_rename",0,NULL,parent);}goto fail;}}if(renameat(srcdir,srcname,dstdir,dstname)<0){if(backed&&renameat(bakdir,bakname,dstdir,dstname)<0)result(0,"COMMIT_AND_RESTORE_FAILED","提交失败且旧文件恢复失败","pre_rename",0,NULL,parent);else{fsync(dstdir);result(0,"RENAME_FAILED","renameat 安全提交失败","pre_rename",0,NULL,parent);}goto fail;}renamed=1;if(fail_after("fsync")||fsync(dstdir)<0){result(0,"FSYNC_FAILED","提交后目标目录 fsync 失败","post_rename",1,NULL,parent);goto fail;}if(fail_after("verify")||regular_hash_at(dstdir,dstname,hash)<0||strcmp(hash,new_hash)){result(0,"VERIFY_FAILED","提交后 hash 校验失败","post_rename",1,NULL,parent);goto fail;}result(1,"COMMITTED","安全提交完成","committed",1,hash,parent);
fail:if(dstfd>=0)close(dstfd);if(srcfd>=0)close(srcfd);if(srcdir>=0)close(srcdir);if(dstdir>=0)close(dstdir);if(bakdir>=0)close(bakdir);free(srcname);free(dstname);free(bakname);return renamed?5:4;}
static int restore_op(int root,const char*backup,const char*target,const char*current_hash,const char*restore_hash,const char*expected_parent){int bakdir=-1,dstdir=-1;char*bakname=NULL,*dstname=NULL;char hash[65],parent[96];bakdir=open_parent(root,backup,&bakname);dstdir=open_parent(root,target,&dstname);if(bakdir<0||dstdir<0||binding(dstdir,parent)<0){result(0,"PARENT_UNSAFE","无法安全打开恢复父目录","pre_rename",0,NULL,NULL);goto fail;}if(strcmp(parent,expected_parent)||!same_parent_binding(root,target,dstdir)){result(0,"PARENT_CHANGED","恢复时目标父目录绑定已变化","pre_rename",0,NULL,parent);goto fail;}if(regular_hash_at(dstdir,dstname,hash)<0||strcmp(hash,current_hash)){result(0,"CURRENT_HASH_MISMATCH","恢复前目标 hash 已变化或类型不安全","pre_rename",0,NULL,parent);goto fail;}if(regular_hash_at(bakdir,bakname,hash)<0||strcmp(hash,restore_hash)){result(0,"BACKUP_HASH_MISMATCH","安全 staging 备份 hash 不匹配","pre_rename",0,NULL,parent);goto fail;}if(renameat(bakdir,bakname,dstdir,dstname)<0){result(0,"RESTORE_RENAME_FAILED","renameat 原子恢复失败","pre_rename",0,NULL,parent);goto fail;}if(fsync(dstdir)<0){result(0,"FSYNC_FAILED","恢复后目标目录 fsync 失败","post_rename",1,NULL,parent);goto fail;}if(regular_hash_at(dstdir,dstname,hash)<0||strcmp(hash,restore_hash)){result(0,"VERIFY_FAILED","恢复后 hash 校验失败","post_rename",1,NULL,parent);goto fail;}result(1,"RESTORED","原子恢复完成","restored",1,hash,parent);free(bakname);free(dstname);close(bakdir);close(dstdir);return 0;
fail:if(bakdir>=0)close(bakdir);if(dstdir>=0)close(dstdir);free(bakname);free(dstname);return 4;}
static int remove_op(int root,const char*target,const char*current_hash,const char*expected_parent){int dstdir=-1;char*dstname=NULL;char hash[65],parent[96];dstdir=open_parent(root,target,&dstname);if(dstdir<0||binding(dstdir,parent)<0){result(0,"PARENT_UNSAFE","无法安全打开删除父目录","pre_unlink",0,NULL,NULL);goto fail;}if(strcmp(parent,expected_parent)||!same_parent_binding(root,target,dstdir)){result(0,"PARENT_CHANGED","删除时目标父目录绑定已变化","pre_unlink",0,NULL,parent);goto fail;}if(regular_hash_at(dstdir,dstname,hash)<0||strcmp(hash,current_hash)){result(0,"CURRENT_HASH_MISMATCH","删除前目标 hash 已变化或类型不安全","pre_unlink",0,NULL,parent);goto fail;}if(unlinkat(dstdir,dstname,0)<0){result(0,"UNLINK_FAILED","unlinkat 安全删除失败","pre_unlink",0,NULL,parent);goto fail;}if(fsync(dstdir)<0){result(0,"FSYNC_FAILED","删除后目标目录 fsync 失败","post_unlink",1,NULL,parent);goto fail;}if(fstatat(dstdir,dstname,&(struct stat){0},AT_SYMLINK_NOFOLLOW)==0||errno!=ENOENT){result(0,"VERIFY_FAILED","删除后目标仍存在","post_unlink",1,NULL,parent);goto fail;}result(1,"REMOVED","安全删除完成","removed",1,current_hash,parent);free(dstname);close(dstdir);return 0;
fail:if(dstdir>=0)close(dstdir);free(dstname);return 4;}
int main(int argc,char**argv){int root;if(argc<2){result(0,"INVALID_ARGUMENT","缺少安全文件操作参数","argument",0,NULL,NULL);return 2;}if((!strcmp(argv[1],"commit")&&argc!=8)||(!strcmp(argv[1],"restore")&&argc!=8)||(!strcmp(argv[1],"remove")&&argc!=6)){result(0,"INVALID_ARGUMENT","安全文件操作参数不合法","argument",0,NULL,NULL);return 2;}int path_end=argc==6?4:6;for(int i=3;i<path_end;i++)if(strcmp(argv[i],"-")&&!valid_relative(argv[i])){result(0,"INVALID_ARGUMENT","路径参数不合法","argument",0,NULL,NULL);return 2;}root=open_absolute_dir(argv[2]);if(root<0){result(0,"ROOT_UNSAFE","无法逐级安全打开项目根","argument",0,NULL,NULL);return 3;}int rc;if(!strcmp(argv[1],"commit"))rc=commit_op(root,argv[3],argv[4],argv[5],argv[6],argv[7]);else if(!strcmp(argv[1],"restore"))rc=restore_op(root,argv[3],argv[4],argv[5],argv[6],argv[7]);else rc=remove_op(root,argv[3],argv[4],argv[5]);close(root);return rc;}
