<?php
/**
 * SpeedAdmin
 * ============================================================================
 * 版权所有 2018-2027 SpeedAdmin，并保留所有权利。
 * 网站地址: https://www.SpeedAdmin.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/8/2
 */
namespace app\backend\controller\bbs;

use app\common\controller\Backend;
use app\common\traits\Curd;
use think\facade\Request;
use app\common\model\BbsComment as CommentModel;

class BbsComment extends Backend
{
    use Curd;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        if (Request::isPost()) {
            $keys = $this->request->post('keys', '', 'trim');
            $page = $this->request->post('page') ? $this->request->post('page') : 1;
            $list = CommentModel::where('content', 'like', '%' . $keys . '%')
                ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                ->toArray();

            return $result = ['code' => 0, 'msg' => lang('get info success'), 'data' => $list['data'], 'count' => $list['total']];
        }

        return view();

    }


    public function delete()
    {
        $ids = $this->request->post('ids');
        if ($ids) {
            $model = new CommentModel();
            $res = $model->del($ids);
            $this->success(lang('delete success'));
        } else {
            $this->error(lang('delete fail'));

        }
    }

    public function state()
    {
        $id = $this->request->post('id');
        $data = $this->request->post();
        if ($id and isset($data['field'])) {
            $model = new CommentModel();
            $res = $model->state($data);
            $this->success(lang('edit success'));

        } else {
            $this->error(lang('edit fail'));

        }


    }
}