<?php
/**
 * SpeedAdmin
 * ============================================================================
 * 版权所有 2018-2027 SpeedAdmin，并保留所有权利。
 * 网站地址: https://www.SpeedAdmin.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/8/2
 */
namespace app\backend\controller\bbs;
use app\common\controller\Backend;
use app\common\traits\Curd;
use think\facade\Request;
use think\facade\View;
use app\common\model\BbsLink as BbsLinkModel;
use think\Validate;

class BbsLink extends Backend
{
    use Curd;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        if (Request::isPost()) {
            $keys = $this->request->post('keys', '', 'trim');
            $page = $this->request->post('page') ? $this->request->post('page') : 1;
            $list = BbsLinkModel::where('name', 'like', '%' . $keys . '%')
                ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                ->toArray();

            return $result = ['code' => 0, 'msg' => lang('get info success'), 'data' => $list['data'], 'count' => $list['total']];
        }

        return view();

    }

    public function add()
    {
        if (Request::isPost()) {
            $data = $this->request->post();
            try{
                $this->validate($data, 'BbsLink');
            }catch (\Exception $e){
                $this->error($e->getMessage());
            }
            $model = new BbsLinkModel();
            $res = $model->add($data);
            if ($res) {
                $this->success(lang('add success'),url('index'));
            } else {
                $this->error(lang('add fail'));
            }
        }
        $view = [
            'info' => '',
            'title' => lang('add'),
        ];
        View::assign($view);
        return view();
    }

    public function edit()
    {
        if (Request::isPost()) {
            $data = $this->request->post();
            try {
                $this->validate($data, 'BbsLink');
            } catch (\Exception $e) {
                $this->error($e->getMessage());
            }
            $model = new BbsLinkModel();
            $res = $model->edit($data);
            if ($res) {
                $this->success(lang('edit success'), url('index'));
            } else {
                $this->error(lang('edit fail'));
            }
        }
        $info = BbsLinkModel::find(Request::get('id'));
        $view = [
            'info' => $info,
            'title' => lang('edit'),
        ];
        View::assign($view);
        return view('add');

    }
    public function delete()
    {
        $ids = $this->request->post('ids');
        if ($ids) {

            $model = new BbsLinkModel();
            $res = $model->del($ids);
            $this->success(lang('delete success'));

        } else {
            $this->error(lang('delete fail'));

        }
    }

    public function state()
    {
        $id = $this->request->post('id');
        $data = $this->request->post();
        if ($id and isset($data['field'])) {
            $model = new BbsLinkModel();
            $res = $model->state($data);
            $this->success(lang('edit success'));
        } else {
            $this->error(lang('edit fail'));

        }


    }
}