<template><el-drawer v-model="visible" :title="t('crud.test.detail.title', '详情')"><el-descriptions v-if="row" :column="1"><el-descriptions-item :label="t('crud.test.field.id', 'ID')"><span>{{ presentField('id', { ...row }) }}</span></el-descriptions-item><el-descriptions-item :label="t('crud.test.field.field_1', '单行输入')"><span>{{ presentField('field1', { ...row }) }}</span></el-descriptions-item><el-descriptions-item :label="t('crud.test.field.field_2', '提及输入')"><span>{{ presentField('field2', { ...row }) }}</span></el-descriptions-item><el-descriptions-item :label="t('crud.test.field.field_3', '虚拟化选择')"><span>{{ presentField('field3', { ...row }) }}</span></el-descriptions-item><el-descriptions-item :label="t('crud.test.field.created_at', 'CREATED_AT')"><span>{{ presentField('createdAt', { ...row }) }}</span></el-descriptions-item><el-descriptions-item :label="t('crud.test.field.updated_at', 'UPDATED_AT')"><span>{{ presentField('updatedAt', { ...row }) }}</span></el-descriptions-item><el-descriptions-item :label="t('crud.test.field.deleted_at', 'DELETED_AT')"><span>{{ presentField('deletedAt', { ...row }) }}</span></el-descriptions-item></el-descriptions></el-drawer></template>
<script setup lang="ts">import { computed, watch } from 'vue'; import { useI18n } from 'vue-i18n'; import { formatFieldValue, resolveFieldOptions } from '@/views/form/runtime/fieldPresentation';
import { useSuppliedFieldOptions } from '@/views/form/runtime/fieldPresentation';  import type { TestModel } from '../api'; const { t } = useI18n(); const props=defineProps<{modelValue:boolean;row:TestModel|null}>(); const emit=defineEmits<{ 'update:modelValue':[boolean] }>(); const visible=computed({get:()=>props.modelValue,set:value=>emit('update:modelValue',value)});
const presentationValues = (values: Record<string, unknown>) => ({ "id": values["id"], "field_1": values["field1"], "field_2": values["field2"], "field_3": values["field3"], "created_at": values["createdAt"], "updated_at": values["updatedAt"], "deleted_at": values["deletedAt"] });
const fieldOptions = useSuppliedFieldOptions(() => (props.modelValue && props.row ? [props.row] : []).map(row => presentationValues({ ...row })));
const presentationSources: Record<string, string> = {};
void fieldOptions.load("test", [{"id":"id","field":"id","dataSource":{"kind":"static","options":[]}},{"id":"field1","field":"field_1","dataSource":{"kind":"static","options":[]}},{"id":"field2","field":"field_2","dataSource":{"kind":"static","mode":"static","options":[{"label":"张三","value":1},{"label":"李四","value":2}]}},{"id":"field3","field":"field_3","dataSource":{"kind":"static","mode":"static","options":[{"label":"选项一","value":1},{"label":"选项二","value":2}]}},{"id":"createdAt","field":"created_at","dataSource":{"kind":"static","options":[]}},{"id":"updatedAt","field":"updated_at","dataSource":{"kind":"static","options":[]}},{"id":"deletedAt","field":"deleted_at","dataSource":{"kind":"static","options":[]}}]);
const fieldPresentations = { "id": { node: {"id":"id","field":"id","dataSource":{"kind":"static","options":[]}}, formatter: "" }, "field1": { node: {"id":"field1","field":"field_1","dataSource":{"kind":"static","options":[]}}, formatter: "" }, "field2": { node: {"id":"field2","field":"field_2","dataSource":{"kind":"static","mode":"static","options":[{"label":"张三","value":1},{"label":"李四","value":2}]}}, formatter: "" }, "field3": { node: {"id":"field3","field":"field_3","dataSource":{"kind":"static","mode":"static","options":[{"label":"选项一","value":1},{"label":"选项二","value":2}]}}, formatter: "" }, "createdAt": { node: {"id":"createdAt","field":"created_at","dataSource":{"kind":"static","options":[]}}, formatter: "" }, "updatedAt": { node: {"id":"updatedAt","field":"updated_at","dataSource":{"kind":"static","options":[]}}, formatter: "" }, "deletedAt": { node: {"id":"deletedAt","field":"deleted_at","dataSource":{"kind":"static","options":[]}}, formatter: "" } };
const presentField = (field: keyof typeof fieldPresentations, row: Record<string, unknown>) => { const values = presentationValues(row); const item = fieldPresentations[field]; return fieldOptions.placeholder(field, values) || formatFieldValue(row[field], resolveFieldOptions(item.node, fieldOptions.forContext(values)), item.formatter, 'published'); };
</script>
