<?php
/**
 * lemocms
 * ============================================================================
 * 版权所有 2018-2027 lemocms，并保留所有权利。
 * 网站地址: https://www.lemocms.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/8/2
 */
namespace app\bbs\controller;

use app\common\model\BbsAdv;
use app\common\model\Bbs;
use app\common\model\BbsCate;
use think\facade\View;

class Index extends Comm {
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }


    public function index(){
        $this->getTop();
        $this->all();
        $this->getHots();
        $this->adv();
        $cate = BbsCate::where('status',1)->select();
        View::assign('cate',$cate);
        return view();
    }
    //轮播图
    protected function adv(){
        $adv = BbsAdv::where('pid',1)->order('id desc')->select();
        View::assign('adv',$adv);
    }
    //首页所有
    protected function all(){
        $all = Bbs::where('status', 1)
            ->withCount('comment')
            ->with([  'cate' => function($query){
                    $query->where('status',1)->field('id,title');
                },
                'user' => function($query){
                    $query->field('id,username,avatar,level_id');
                }])
            ->cache(600)
            ->limit(10)
            ->order('id desc')
            ->paginate($this->pageSize,false,['query'=>$this->request->param()]);
        View::assign('all',$all);
    }


}