<?php
/**
 * ============================================================================
 * Created by SpeedAdmin.
 * 版权所有 2018-2027 SpeedAdmin，并保留所有权利。
 * 网站地址: https://www.SpeedAdmin.cn
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * User: yuege
 * Date: 2020/2/10
 * Time: 18:51
 */
namespace app\backend\controller\sys;

use app\common\controller\Backend;
use app\common\traits\Curd;
use app\common\model\Attach as AttachModel;
use think\App;

class  Attach extends Backend{
    use Curd;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function __construct(App $app)
    {
        parent::__construct($app);
        $this->modelClass = new AttachModel();

    }

    public function index(){
        if ($this->request->isAjax()) {
            list($this->page, $this->pageSize,$sort,$where) = $this->buildParames();
            $count = $this->modelClass
                ->where($where)
                ->count();
            $list =$this->modelClass
                ->where($where)
                ->order($sort)
                ->page($this->page  ,$this->pageSize)
                ->select();
            $result = ['code' => 0, 'msg' => lang('Get info success'), 'data' =>$list, 'count' => $count];
            return json($result);
        }
        return view();
    }

//    /*** 选择附件*/
//    public function select()
//    {
//        if ($this->request->isAjax()) {
//            list($this->page, $this->pageSize,$sort,$where) = $this->buildParames();
//            $count = $this->modelClass
//                ->where($where)
//                ->order($sort)
//                ->count();
//            $list =$this->modelClass->where($where)
//                ->where($where)
//                ->order($sort)
//                ->page($this->page  ,$this->pageSize)
//                ->select();
//            $result = ['code' => 0, 'msg' => lang('get info success'), 'data' => $list['data'], 'count' => $list['total']];
//            return json($result);
//        }
//        $view = ['mime'=>$mime];
//        return view('',$view);
//    }

    public function delete()
    {
        $ids = input('ids')?input('ids'):input('id');
        $list = $this->modelClass->whereIn('id', $ids)->select();
        if(empty($list))$this->error('Data is not exist');
        try {
            foreach ($list as $v) {
                @unlink(app()->getRootPath().'public'.$v->path);
                $save = $v->delete();
            }
            $save = $list->delete();
        } catch (\Exception $e) {
            $this->error(lang("Delete success"));
        }

        $save ? $this->success(lang('Delete success')) :  $this->error(lang("Delete fail"));
    }

}

