<?php
/**
 * SpeedAdmin
 * ============================================================================
 * 版权所有 2018-2027 SpeedAdmin，并保留所有权利。
 * 网站地址: https://www.SpeedAdmin.cn
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/8/2
 */
namespace app\backend\controller\sys;
use app\common\controller\Backend;
use app\common\model\Config as ConfigModel;
use app\common\model\ConfigGroup as ConfigGroupModel;
use app\common\model\FieldType;
use app\common\traits\Curd;
use think\facade\Request;
use think\facade\Db;
use think\facade\View;
class System extends Backend {
    use Curd;
    public $rules = [
        ['name'=>'email','title'=>'邮件'],
        ['name'=>'url','title'=>'网址'],
        ['name'=>'number','title'=>'有效的数值'],
        ['name'=>'ip','title'=>'IP'],
        ['name'=>'date','title'=>'日期'],
        ['name'=>'phone','title'=>'手机号'],
        ['name'=>'qq','title'=>'QQ'],
        ['name'=>'identity','title'=>'身份证号'],

    ];
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index(){
        if ($this->request->isPost()) {
            $data = input();
            foreach ($data as $k=>$v){
                $res =  Db::name('config')->where('code',$k)->update(['value'=>$v]);
            }
            $this->success(lang('Save Success'));
        }
        $group =  ['site','email','upload','sms'];
        $list = Db::name('config')
            ->where('type','in',$group)
            ->field('code,value')
            ->column('value','code');
        View::assign('formData',$list);
        return view();

    }
//    配置列表
    public function configlist(){

        if ($this->request->isAjax()) {
            list($this->page, $this->pageSize,$where) = $this->buildParames();
            $keys = input('keys', '', 'trim');
            $page = input('page') ? input('page') : 1;
            $list = Db::name('config')
                     ->where($where)
                     ->paginate(['list_rows' => $this->pageSize, 'page' => $this->page])
                     ->toArray();
            return $result = ['code' => 0, 'msg' => lang('get info success'), 'data' => $list['data'], 'count' => $list['total']];
        }

        return view();

    }
    //添加配置
    public function configAdd(){
        if($this->request->isPost()){
            $data = input();
            $list = ConfigModel::where('code',$data['code'])->find();
            if($list){
                $this->error(lang('field already exist'));

            }else{
                $model = new ConfigModel();
                if($model->add($data)){
                    $this->success(lang('edit success'));
                }else{
                    $this->error(lang('edit fail'));
                }
            }


        }
        $list = '';
        $configGroup = Db::name('config_group')->select();
        $fieldType = FieldType::select();

        $view = ['title'=>lang('Add'),'formData'=>$list,'configGroup'=>$configGroup,'fieldType'=>$fieldType,'rules'=>$this->rules];
        View::assign($view);

        return view('add');
    }
//    编辑配置
    public function configEdit(){
        $id = $this->request->param('id');
        if($this->request->isPost()){
            $list = ConfigModel::find($id);
            $data = input();
            $model = new ConfigModel();
            if($model->edit($data)){
                $this->success(lang('edit success'));
            }else{
                $this->error(lang('edit fail'));
            }
        }
        $configGroup = Db::name('config_group')->select();
        $list = ConfigModel::find($id);
        $fieldType = FieldType::select();

        $view = ['title'=>lang('edit'),'formData'=>$list,'configGroup'=>$configGroup,'fieldType'=>$fieldType,'rules'=>$this->rules];
        View::assign($view);
        return view('add');
    }
//    删除配置
    public function configDel()
    {
        if ($this->request->isPost()) {
            $ids = input('ids') ? input('ids') : input('id');
            $model = new ConfigModel();
            if (($model->del($ids))) {
                $this->success('delete success');
            } else {

                $this->error('delete fail');
            }

        } else {
            $this->error('invalid options');
        }

    }
//    配置状态
    public function configState(){
        $id = input('id');
        $data = input();

        if (empty($id)) {
            $this->error('data not exist');
        }
        $model = new ConfigModel();
        $model->state($data);
        $this->success(lang('edit success'));
    }

    public function configGroup(){
        $keys = input('keys', '', 'trim');
        $page = input('page') ? input('page') : 1;
        $list = Db::name('config_group')
            ->where('name', 'like', '%' . $keys . '%')
            ->select();
        $view = ['title'=>lang('config group'),'formData'=>$list];
        View::assign($view);
        return view();


    }
//    配置分组
    public function configGroupAdd(){
        if($this->request->isPost()){
            $data = input();
            $list = ConfigGroupModel::where('name',$data['name'])->find();
            if($list){
                $this->error(lang('field already exist'));

            }else {
                $model = new ConfigGroupModel();
                if ($model->add($data)) {
                    $this->success(lang('edit success'));
                } else {
                    $this->error(lang('edit fail'));
                }
            }

        }
        $view = ['title'=>lang('config group'),'formData'=>''];
        View::assign($view);
        return view('groupadd');

    }

    public function configGroupDel(){
        $id = input('id');
        $list = ConfigGroupModel::find($id);
        if(!$list){
            $this->error(lang('id is not exist'));
        }
        $config = ConfigModel::where('type',$list->name)->find();
        if($config){
            $this->error(lang('group has config').lang('delete fail'));

        }
        $model = new ConfigGroupModel();
        if ($model->del($id)) {
            $this->success(lang('delete success'));
        }else{
            $this->error(lang('delete fail'));

        }

    }

//
}