-- 全新 RBAC：菜单、权限资源、Casbin 授权关系职责分离。

CREATE TABLE IF NOT EXISTS `fun_permission` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `pid` int unsigned NOT NULL DEFAULT 0,
  `module` varchar(50) NOT NULL DEFAULT 'backend',
  `code` varchar(255) DEFAULT NULL,
  `obj` varchar(190) NOT NULL DEFAULT '',
  `act` varchar(100) NOT NULL DEFAULT '',
  `title` varchar(100) NOT NULL DEFAULT '',
  `resource_type` enum('group','route') NOT NULL DEFAULT 'route',
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `is_public` tinyint(1) NOT NULL DEFAULT 0,
  `sort` int NOT NULL DEFAULT 999,
  `source_type` varchar(20) NOT NULL DEFAULT 'system',
  `source_name` varchar(100) NOT NULL DEFAULT '',
  `create_time` int NOT NULL DEFAULT 0,
  `update_time` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_permission_code` (`code`),
  KEY `idx_permission_tree` (`pid`,`status`,`sort`),
  KEY `idx_permission_resource` (`obj`,`act`),
  KEY `idx_permission_source` (`source_type`,`source_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='权限资源目录';

CREATE TABLE IF NOT EXISTS `fun_admin_menu` (
  `id` int unsigned NOT NULL AUTO_INCREMENT,
  `pid` int unsigned NOT NULL DEFAULT 0,
  `permission_id` int unsigned NOT NULL DEFAULT 0,
  `module` varchar(50) NOT NULL DEFAULT 'backend',
  `title` varchar(100) NOT NULL DEFAULT '',
  `href` varchar(255) NOT NULL DEFAULT '',
  `query` varchar(250) NOT NULL DEFAULT '',
  `target` varchar(20) NOT NULL DEFAULT '_self',
  `icon` varchar(100) NOT NULL DEFAULT '',
  `status` tinyint(1) NOT NULL DEFAULT 1,
  `sort` int NOT NULL DEFAULT 999,
  `source_type` varchar(20) NOT NULL DEFAULT 'system',
  `source_name` varchar(100) NOT NULL DEFAULT '',
  `create_time` int NOT NULL DEFAULT 0,
  `update_time` int DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_menu_location` (`module`,`href`,`query`),
  KEY `idx_menu_tree` (`pid`,`status`,`sort`),
  KEY `idx_menu_permission` (`permission_id`),
  KEY `idx_menu_source` (`source_type`,`source_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='后台菜单';

CREATE TABLE IF NOT EXISTS `fun_casbin_rule` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `ptype` varchar(10) NOT NULL,
  `v0` varchar(190) NOT NULL DEFAULT '',
  `v1` varchar(190) NOT NULL DEFAULT '',
  `v2` varchar(190) NOT NULL DEFAULT '',
  `v3` varchar(190) NOT NULL DEFAULT '',
  `v4` varchar(190) NOT NULL DEFAULT '',
  `v5` varchar(190) NOT NULL DEFAULT '',
  `rule_hash` char(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_rule_hash` (`rule_hash`),
  KEY `idx_subject_domain` (`ptype`,`v0`,`v1`),
  KEY `idx_object_action` (`ptype`,`v2`,`v3`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Casbin授权策略';

INSERT IGNORE INTO `fun_permission` (`id`,`pid`,`module`,`code`,`obj`,`act`,`title`,`resource_type`,`status`,`is_public`,`sort`,`source_type`,`source_name`,`create_time`,`update_time`) VALUES
(1, 0, 'backend', NULL, '', '', 'Sys', 'group', 1, 0, 0, 'system', 'core', 0, NULL),
(2, 0, 'backend', NULL, '', '', 'AuthBoard', 'group', 1, 0, 1, 'system', 'core', 0, NULL),
(3, 2, 'backend', NULL, '', '', 'Auth', 'group', 1, 0, 50, 'system', 'core', 0, NULL),
(4, 3, 'backend', 'backend/auth.auth:index', 'backend/auth.auth', 'index', 'List', 'route', 1, 0, 2, 'system', 'core', 0, NULL),
(5, 3, 'backend', 'backend/auth.auth:edit', 'backend/auth.auth', 'edit', 'Edit', 'route', 1, 0, 1, 'system', 'core', 0, NULL),
(6, 3, 'backend', 'backend/auth.auth:modify', 'backend/auth.auth', 'modify', 'Modify', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(7, 3, 'backend', 'backend/auth.auth:delete', 'backend/auth.auth', 'delete', 'Delete', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(8, 3, 'backend', 'backend/auth.auth:add', 'backend/auth.auth', 'add', 'Add', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(9, 2, 'backend', NULL, '', '', 'Role', 'group', 1, 0, 0, 'system', 'core', 0, NULL),
(10, 9, 'backend', 'backend/auth.authgroup:delete', 'backend/auth.authgroup', 'delete', 'Delete', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(11, 9, 'backend', 'backend/auth.authgroup:add', 'backend/auth.authgroup', 'add', 'Add', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(12, 9, 'backend', 'backend/auth.authgroup:edit', 'backend/auth.authgroup', 'edit', 'Edit', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(13, 9, 'backend', 'backend/auth.authgroup:modify', 'backend/auth.authgroup', 'modify', 'Modify', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(14, 9, 'backend', 'backend/auth.authgroup:access', 'backend/auth.authgroup', 'access', 'Access', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(15, 9, 'backend', 'backend/auth.authgroup:index', 'backend/auth.authgroup', 'index', 'List', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(16, 2, 'backend', NULL, '', '', 'Admin', 'group', 1, 0, 1, 'system', 'core', 0, NULL),
(17, 16, 'backend', 'backend/auth.admin:index', 'backend/auth.admin', 'index', 'List', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(18, 16, 'backend', 'backend/auth.admin:add', 'backend/auth.admin', 'add', 'Add', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(19, 16, 'backend', 'backend/auth.admin:delete', 'backend/auth.admin', 'delete', 'Delete', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(20, 16, 'backend', 'backend/auth.admin:modify', 'backend/auth.admin', 'modify', 'Modify', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(21, 16, 'backend', 'backend/auth.admin:password', 'backend/auth.admin', 'password', 'Password', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(22, 3, 'backend', 'backend/auth.auth:child', 'backend/auth.auth', 'child', 'AddChild', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(23, 16, 'backend', 'backend/auth.admin:edit', 'backend/auth.admin', 'edit', 'Edit', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(24, 1, 'backend', NULL, '', '', 'Log', 'group', 1, 0, 35, 'system', 'core', 0, NULL),
(25, 24, 'backend', 'backend/sys.adminlog:delete', 'backend/sys.adminlog', 'delete', 'Delete', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(26, 41, 'backend', 'backend/sys.config:index', 'backend/sys.config', 'index', 'List', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(27, 41, 'backend', 'backend/sys.config:add', 'backend/sys.config', 'add', 'Add', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(28, 41, 'backend', 'backend/sys.config:edit', 'backend/sys.config', 'edit', 'Edit', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(29, 41, 'backend', 'backend/sys.config:delete', 'backend/sys.config', 'delete', 'Delete', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(30, 41, 'backend', 'backend/sys.config:modify', 'backend/sys.config', 'modify', 'Modify', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(31, 42, 'backend', 'backend/sys.configgroup:index', 'backend/sys.configgroup', 'index', 'list', 'route', 1, 0, 5, 'system', 'core', 0, NULL),
(32, 42, 'backend', 'backend/sys.configgroup:add', 'backend/sys.configgroup', 'add', 'Add', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(33, 42, 'backend', 'backend/sys.configgroup:delete', 'backend/sys.configgroup', 'delete', 'Delete', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(34, 42, 'backend', 'backend/sys.configgroup:edit', 'backend/sys.configgroup', 'edit', 'Edit', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(35, 42, 'backend', 'backend/sys.configgroup:modify', 'backend/sys.configgroup', 'modify', 'Modify', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(36, 1, 'backend', 'backend/sys.config:set', 'backend/sys.config', 'set', 'SysSet', 'route', 1, 0, 5, 'system', 'core', 0, NULL),
(37, 1, 'backend', NULL, '', '', 'Attach', 'group', 1, 0, 50, 'system', 'core', 0, NULL),
(38, 37, 'backend', 'backend/sys.attach:index', 'backend/sys.attach', 'index', 'List', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(39, 37, 'backend', 'backend/sys.attach:add', 'backend/sys.attach', 'add', 'Add', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(40, 37, 'backend', 'backend/sys.attach:delete', 'backend/sys.attach', 'delete', 'Delete', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(41, 1, 'backend', NULL, '', '', 'Config', 'group', 1, 0, 50, 'system', 'core', 0, NULL),
(42, 1, 'backend', NULL, '', '', 'configGroup', 'group', 1, 0, 50, 'system', 'core', 0, NULL),
(43, 24, 'backend', 'backend/sys.adminlog:index', 'backend/sys.adminlog', 'index', 'List', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(44, 1, 'backend', 'backend/ajax:uploads', 'backend/ajax', 'uploads', 'Uploads', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(45, 0, 'backend', NULL, '', '', 'Member', 'group', 1, 0, 100, 'system', 'core', 0, NULL),
(46, 45, 'backend', NULL, '', '', 'Member', 'group', 1, 0, 1, 'system', 'core', 0, NULL),
(47, 46, 'backend', 'backend/member.member:index', 'backend/member.member', 'index', 'List', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(48, 46, 'backend', 'backend/member.member:add', 'backend/member.member', 'add', 'Add', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(49, 46, 'backend', 'backend/member.member:delete', 'backend/member.member', 'delete', 'Delete', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(50, 46, 'backend', 'backend/member.member:edit', 'backend/member.member', 'edit', 'Edit', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(51, 46, 'backend', 'backend/member.member:modify', 'backend/member.member', 'modify', 'Modify', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(52, 45, 'backend', NULL, '', '', 'MemberLevel', 'group', 1, 0, 50, 'system', 'core', 0, NULL),
(53, 52, 'backend', 'backend/member.memberlevel:index', 'backend/member.memberlevel', 'index', 'List', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(54, 52, 'backend', 'backend/member.memberlevel:modify', 'backend/member.memberlevel', 'modify', 'Modify', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(55, 52, 'backend', 'backend/member.memberlevel:delete', 'backend/member.memberlevel', 'delete', 'Delete', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(56, 52, 'backend', 'backend/member.memberlevel:add', 'backend/member.memberlevel', 'add', 'Add', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(57, 52, 'backend', 'backend/member.memberlevel:edit', 'backend/member.memberlevel', 'edit', 'Edit', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(58, 45, 'backend', NULL, '', '', 'memberGroup', 'group', 1, 0, 50, 'system', 'core', 0, NULL),
(59, 58, 'backend', 'backend/member.membergroup:index', 'backend/member.membergroup', 'index', 'List', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(60, 58, 'backend', 'backend/member.membergroup:modify', 'backend/member.membergroup', 'modify', 'Modify', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(61, 58, 'backend', 'backend/member.membergroup:delete', 'backend/member.membergroup', 'delete', 'Delete', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(62, 58, 'backend', 'backend/member.membergroup:add', 'backend/member.membergroup', 'add', 'Add', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(63, 58, 'backend', 'backend/member.membergroup:edit', 'backend/member.membergroup', 'edit', 'Edit', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(64, 0, 'backend', NULL, '', '', 'Addon', 'group', 1, 0, 501, 'system', 'core', 0, NULL),
(65, 64, 'backend', 'backend/addon:index', 'backend/addon', 'index', 'List', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(66, 1, 'backend', NULL, '', '', 'languages', 'group', 1, 0, 50, 'system', 'core', 0, NULL),
(67, 66, 'backend', 'backend/sys.languages:index', 'backend/sys.languages', 'index', 'List', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(68, 66, 'backend', 'backend/sys.languages:delete', 'backend/sys.languages', 'delete', 'delete', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(69, 66, 'backend', 'backend/sys.languages:modify', 'backend/sys.languages', 'modify', 'Modify', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(70, 66, 'backend', 'backend/sys.languages:add', 'backend/sys.languages', 'add', 'Add', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(71, 66, 'backend', 'backend/sys.languages:edit', 'backend/sys.languages', 'edit', 'Edit', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(72, 64, 'backend', 'backend/addon:install', 'backend/addon', 'install', 'Install', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(73, 64, 'backend', 'backend/addon:modify', 'backend/addon', 'modify', 'modify', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(74, 64, 'backend', 'backend/addon:config', 'backend/addon', 'config', 'Config', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(76, 1, 'backend', NULL, '', '', 'upgrade', 'group', 1, 0, 50, 'system', 'core', 0, NULL),
(77, 76, 'backend', 'backend/sys.upgrade:index', 'backend/sys.upgrade', 'index', 'list', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(78, 76, 'backend', 'backend/sys.upgrade:check', 'backend/sys.upgrade', 'check', 'check', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(79, 76, 'backend', 'backend/sys.upgrade:backup', 'backend/sys.upgrade', 'backup', 'backup', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(80, 76, 'backend', 'backend/sys.upgrade:install', 'backend/sys.upgrade', 'install', 'install', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(81, 46, 'backend', 'backend/member.member:import', 'backend/member.member', 'import', 'Import', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(82, 46, 'backend', 'backend/member.member:export', 'backend/member.member', 'export', 'Export', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(83, 46, 'backend', 'backend/member.member:recycle', 'backend/member.member', 'recycle', 'Recycle', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(84, 46, 'backend', 'backend/member.member:restore', 'backend/member.member', 'restore', 'Restore', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(85, 46, 'backend', 'backend/member.member:destroy', 'backend/member.member', 'destroy', 'Destroy', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(86, 52, 'backend', 'backend/member.memberlevel:recycle', 'backend/member.memberlevel', 'recycle', 'recycle', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(87, 52, 'backend', 'backend/member.memberlevel:destroy', 'backend/member.memberlevel', 'destroy', 'destroy', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(88, 52, 'backend', 'backend/member.memberlevel:restore', 'backend/member.memberlevel', 'restore', 'restore', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(89, 52, 'backend', 'backend/member.memberlevel:import', 'backend/member.memberlevel', 'import', 'import', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(90, 52, 'backend', 'backend/member.memberlevel:export', 'backend/member.memberlevel', 'export', 'export', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(91, 58, 'backend', 'backend/member.membergroup:recycle', 'backend/member.membergroup', 'recycle', 'recycle', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(92, 58, 'backend', 'backend/member.membergroup:restore', 'backend/member.membergroup', 'restore', 'restore', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(93, 58, 'backend', 'backend/member.membergroup:destroy', 'backend/member.membergroup', 'destroy', 'destroy', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(94, 58, 'backend', 'backend/member.membergroup:import', 'backend/member.membergroup', 'import', 'import', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(95, 58, 'backend', 'backend/member.membergroup:export', 'backend/member.membergroup', 'export', 'export', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(96, 41, 'backend', 'backend/sys.config:setvalue', 'backend/sys.config', 'setvalue', 'setValue', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(97, 46, 'backend', 'backend/member.member:upme', 'backend/member.member', 'upme', 'upme', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(98, 46, 'backend', 'backend/member.member:copy', 'backend/member.member', 'copy', 'copy', 'route', 1, 0, 0, 'system', 'core', 0, NULL),
(156, 1, 'backend', NULL, '', '', 'blacklist', 'group', 1, 0, 50, 'system', 'core', 0, NULL),
(157, 156, 'backend', 'backend/sys.blacklist:index', 'backend/sys.blacklist', 'index', 'List', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(158, 156, 'backend', 'backend/sys.blacklist:add', 'backend/sys.blacklist', 'add', 'add', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(159, 156, 'backend', 'backend/sys.blacklist:delete', 'backend/sys.blacklist', 'delete', 'delete', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(160, 156, 'backend', 'backend/sys.blacklist:edit', 'backend/sys.blacklist', 'edit', 'edit', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(161, 156, 'backend', 'backend/sys.blacklist:destory', 'backend/sys.blacklist', 'destory', 'destory', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(162, 156, 'backend', 'backend/sys.blacklist:modify', 'backend/sys.blacklist', 'modify', 'modify', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(163, 42, 'backend', 'backend/sys.configgroup:destroy', 'backend/sys.configgroup', 'destroy', 'destroy', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(164, 156, 'backend', 'backend/sys.blacklist:export', 'backend/sys.blacklist', 'export', 'export', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(165, 156, 'backend', 'backend/sys.blacklist:recycle', 'backend/sys.blacklist', 'recycle', 'recycle', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(166, 156, 'backend', 'backend/sys.blacklist:restore', 'backend/sys.blacklist', 'restore', 'restore', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(167, 156, 'backend', 'backend/sys.blacklist:destroy', 'backend/sys.blacklist', 'destroy', 'destroy', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(168, 156, 'backend', 'backend/sys.blacklist:import', 'backend/sys.blacklist', 'import', 'import', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(169, 37, 'backend', 'backend/sys.attach:edit', 'backend/sys.attach', 'edit', 'Edit', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(170, 37, 'backend', 'backend/sys.attach:move', 'backend/sys.attach', 'move', 'Move', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(171, 37, 'backend', 'backend/sys.attach:selectfiles', 'backend/sys.attach', 'selectfiles', 'selectfiles', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(172, 176, 'backend', 'backend/sys.attachgroup:add', 'backend/sys.attachgroup', 'add', 'add', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(173, 176, 'backend', 'backend/sys.attachgroup:edit', 'backend/sys.attachgroup', 'edit', 'edit', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(174, 176, 'backend', 'backend/sys.attachgroup:delete', 'backend/sys.attachgroup', 'delete', 'delete', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(175, 64, 'backend', 'backend/addon:add', 'backend/addon', 'add', 'Install', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(176, 1, 'backend', NULL, '', '', 'attachGroup', 'group', 1, 0, 99, 'system', 'core', 0, NULL),
(177, 176, 'backend', 'backend/sys.attachgroup:destroy', 'backend/sys.attachgroup', 'destroy', 'destroy', 'route', 1, 0, 50, 'system', 'core', 0, NULL),
(178, 176, 'backend', 'backend/sys.attachgroup:recycle', 'backend/sys.attachgroup', 'recycle', 'recycle', 'route', 1, 0, 50, 'system', 'core', 0, NULL);

INSERT IGNORE INTO `fun_admin_menu` (`id`,`pid`,`permission_id`,`module`,`title`,`href`,`query`,`target`,`icon`,`status`,`sort`,`source_type`,`source_name`,`create_time`,`update_time`) VALUES
(1, 0, 1, 'backend', 'Sys', 'sys', '', '_self', 'layui-icon layui-icon-home', 1, 0, 'system', 'core', 0, NULL),
(2, 0, 2, 'backend', 'AuthBoard', 'auth', '', '_self', 'layui-icon layui-icon-auz', 1, 1, 'system', 'core', 0, NULL),
(3, 2, 3, 'backend', 'Auth', 'auth.auth', '', '_self', 'layui-icon layui-icon-component', 1, 50, 'system', 'core', 0, NULL),
(4, 2, 9, 'backend', 'Role', 'auth.authgroup', '', '_self', 'layui-icon layui-icon-circle-dot', 1, 0, 'system', 'core', 0, NULL),
(5, 2, 16, 'backend', 'Admin', 'auth.admin', '', '_self', 'layui-icon layui-icon-user', 1, 1, 'system', 'core', 0, NULL),
(6, 1, 24, 'backend', 'Log', 'sys.adminlog', '', '_self', 'layui-icon layui-icon-log', 1, 35, 'system', 'core', 0, NULL),
(7, 1, 36, 'backend', 'SysSet', 'sys.config/set', '', '_self', 'layui-icon layui-icon-set-sm', 1, 5, 'system', 'core', 0, NULL),
(8, 1, 37, 'backend', 'Attach', 'sys.attach', '', '_self', 'layui-icon layui-icon-picture-fine', 1, 50, 'system', 'core', 0, NULL),
(9, 1, 41, 'backend', 'Config', 'sys.config', '', '_self', 'layui-icon layui-icon-component', 1, 50, 'system', 'core', 0, NULL),
(10, 1, 42, 'backend', 'configGroup', 'sys.configgroup', '', '_self', 'layui-icon layui-icon-component', 1, 50, 'system', 'core', 0, NULL),
(11, 0, 45, 'backend', 'Member', 'member', '', '_self', 'layui-icon layui-icon-user', 1, 100, 'system', 'core', 0, NULL),
(12, 11, 46, 'backend', 'Member', 'member.member', '', '_self', 'layui-icon layui-icon-username', 1, 1, 'system', 'core', 0, NULL),
(13, 11, 52, 'backend', 'MemberLevel', 'member.memberlevel', '', '_self', 'layui-icon layui-icon-diamond', 1, 50, 'system', 'core', 0, NULL),
(14, 11, 58, 'backend', 'memberGroup', 'member.membergroup', '', '_self', 'layui-icon layui-icon-component', 1, 50, 'system', 'core', 0, NULL),
(15, 0, 64, 'backend', 'Addon', 'addon', '', '_self', 'layui-icon layui-icon-app', 1, 501, 'system', 'core', 0, NULL),
(16, 1, 66, 'backend', 'languages', 'sys.languages', '', '_self', 'layui-icon layui-icon-app', 1, 50, 'system', 'core', 0, NULL),
(17, 1, 76, 'backend', 'upgrade', 'sys.upgrade', '', '_self', 'layui-icon layui-icon-refresh-1', 1, 50, 'system', 'core', 0, NULL),
(18, 1, 156, 'backend', 'blacklist', 'sys.blacklist', '', '_self', 'layui-icon layui-icon-app', 1, 50, 'system', 'core', 0, NULL),
(19, 1, 176, 'backend', 'attachGroup', 'sys.attachgroup/index', '', '_self', 'layui-icon layui-icon-diamond', 1, 99, 'system', 'core', 0, NULL);

INSERT IGNORE INTO `fun_casbin_rule` (`ptype`,`v0`,`v1`,`v2`,`v3`,`v4`,`v5`,`rule_hash`) VALUES
('g','admin:1','role:1','default','','','', '19ce2ecadf0a1cf41bc4247609cb7af71f96ad6e0db663c9ba65a4bb501eabed');
