-- 多语言后端链路：译文条目表 + en-US 种子（数据源 admin-web/src/locales/en-US.ts，前端运行时合并覆盖静态包）。
CREATE TABLE `fun_language_line` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `locale` varchar(10) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '语言标识，如 zh-cn/en-us',
  `key` varchar(190) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT 'i18n key（点分路径）',
  `value` text COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '译文',
  `created_at` datetime DEFAULT NULL,
  `updated_at` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_language_line_locale_key` (`locale`,`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='多语言译文条目';

INSERT INTO `fun_language_line` (`locale`, `key`, `value`) VALUES
('en-us', 'aiComposer.approval', 'Approval mode'),
('en-us', 'aiComposer.attach', 'Attach files'),
('en-us', 'aiComposer.attachment', 'Private attachment'),
('en-us', 'aiComposer.retry', 'Retry'),
('en-us', 'aiComposer.remove', 'Remove'),
('en-us', 'aiComposer.download', 'Download safely'),
('en-us', 'aiComposer.privacy', 'Sensitive material in messages and attachments will be sent to the profile Provider. PNG/JPEG/WebP: 5MiB each; UTF-8 code/text: 128KiB each. Up to 4 files and 12MiB total.'),
('en-us', 'aiComposer.invalid', 'File type, name, size or count exceeds the supported limits. The file was rejected.'),
('en-us', 'aiComposer.uploadFailed', 'Upload failed or the file is not valid UTF-8 text. Retry or remove it; failed attachments are never silently skipped.'),
('en-us', 'aiComposer.removeFailed', 'Could not remove attachment. Please retry.'),
('en-us', 'aiComposer.sendFailed', 'Sending failed. Retry keeps the created message and task idempotency key to avoid duplicates.'),
('en-us', 'aiComposer.incompatible', 'The current or fallback model has not declared support for these images. Update capabilities or remove the images before sending.'),
('en-us', 'aiComposer.downloadFailed', 'Could not read private attachment. Check access and retry.'),
('en-us', 'aiComposer.imageInput', 'Image input (administrator declaration)'),
('en-us', 'aiComposer.maxImages', 'Maximum images'),
('en-us', 'aiComposer.imageTokens', 'Fixed tokens per image'),
('en-us', 'menu.Home', 'Home'),
('en-us', 'menu.Dashboard', 'Dashboard'),
('en-us', 'menu.Profile', 'Profile'),
('en-us', 'menu.Login', 'Sign in'),
('en-us', 'menu.Forbidden', 'Forbidden'),
('en-us', 'menu.ServerError', 'Server error'),
('en-us', 'menu.NotFound', 'Page not found'),
('en-us', 'menu.System', 'System'),
('en-us', 'menu.SystemManagement', 'System'),
('en-us', 'menu.UserManagement', 'User Management'),
('en-us', 'menu.Development', 'Dev Tools'),
('en-us', 'menu.SystemUser', 'Administrators'),
('en-us', 'menu.SystemRole', 'Roles'),
('en-us', 'menu.SystemMenu', 'Menus'),
('en-us', 'menu.SystemDept', 'Departments'),
('en-us', 'menu.SystemDict', 'Dictionaries'),
('en-us', 'menu.SystemLog', 'Logs'),
('en-us', 'menu.SystemLogOperation', 'Operation logs'),
('en-us', 'menu.SystemPermission', 'Permissions'),
('en-us', 'menu.SystemConfig', 'Settings'),
('en-us', 'menu.SystemAttachment', 'Attachments'),
('en-us', 'menu.SystemLanguage', 'Languages'),
('en-us', 'menu.SystemBlacklist', 'Blacklist'),
('en-us', 'menu.SystemUpgrade', 'System Upgrade'),
('en-us', 'menu.SystemPlugin', 'Plugin Center'),
('en-us', 'menu.SystemMember', 'Members'),
('en-us', 'menu.SystemMemberGroup', 'Member Groups'),
('en-us', 'menu.SystemMemberLevel', 'Member Levels'),
('en-us', 'menu.EnterpriseApplications', 'Enterprise Application Center'),
('en-us', 'menu.EnterpriseApplicationCenter', 'Application Center'),
('en-us', 'menu.ApplicationList', 'Applications'),
('en-us', 'menu.DomainManagement', 'Domains'),
('en-us', 'menu.SsoConfiguration', 'Single Sign-On'),
('en-us', 'menu.OAuthClientManagement', 'OAuth Clients'),
('en-us', 'menu.ScopeClaimManagement', 'Scopes & Claims'),
('en-us', 'menu.IdentityUsers', 'Identity Users'),
('en-us', 'menu.IdentitySessions', 'Sessions & Authorizations'),
('en-us', 'menu.SigningKeys', 'Signing Keys'),
('en-us', 'menu.IdentityAudit', 'Login Audit'),
('en-us', 'menu.ApplicationPortal', 'Application Portal'),
('en-us', 'menu.BusinessDevelopment', 'Business Development'),
('en-us', 'menu.BusinessMine', 'Business Development'),
('en-us', 'menu.BusinessVisual', 'Visual Creation'),
('en-us', 'menu.BusinessDatabase', 'Adopt from Database'),
('en-us', 'menu.BusinessRecords', 'Generation Records'),
('en-us', 'menu.FormDesigner', 'Form Designer'),
('en-us', 'menu.FormList', 'Forms'),
('en-us', 'menu.DevelopmentCrud', 'CRUD Generator'),
('en-us', 'menu.AiDevelopment', 'AI Development Assistant'),
('en-us', 'aiDevelopment.title', 'AI Development Assistant'),
('en-us', 'aiDevelopment.subtitle', 'Conversations, tool approvals, and workspace changes'),
('en-us', 'aiDevelopment.reasoning.profile', 'Reasoning mode'),
('en-us', 'aiDevelopment.reasoning.conversation', 'Conversation reasoning effort'),
('en-us', 'aiDevelopment.reasoning.levels', 'Reasoning efforts'),
('en-us', 'aiDevelopment.reasoning.default', 'Default'),
('en-us', 'aiDevelopment.reasoning.defaultOption', 'Default (omit reasoning_effort)'),
('en-us', 'aiDevelopment.reasoning.inherit', 'Inherit profile'),
('en-us', 'aiDevelopment.reasoning.override', 'Conversation override'),
('en-us', 'aiDevelopment.reasoning.noProfile', 'No profile selected'),
('en-us', 'aiDevelopment.reasoning.capabilityHint', 'Capabilities are declared per model by an administrator, not officially verified or inferred from names or catalogs. Allowed declarations: low, medium, high, xhigh, max, ultra. Only openai-chat currently passes reasoning_effort unchanged; no level conversion or upstream support is guaranteed.'),
('en-us', 'aiDevelopment.modelSelection.current', 'Current conversation model'),
('en-us', 'aiDevelopment.modelSelection.unset', 'Not set'),
('en-us', 'aiDevelopment.modelSelection.id', 'Model ID'),
('en-us', 'aiDevelopment.modelSelection.save', 'Save model'),
('en-us', 'aiDevelopment.modelSelection.hint', 'Only the currently configured provider is supported. Enter a model ID it supports. Changes affect only tasks created after saving; the current task keeps its original model.'),
('en-us', 'aiDevelopment.modelSelection.failed', 'Could not save the model. Check the model ID or retry'),
('en-us', 'aiDevelopment.provider', 'Provider'),
('en-us', 'aiDevelopment.fields.base', 'Base'),
('en-us', 'aiDevelopment.fields.local', 'Local'),
('en-us', 'aiDevelopment.fields.remote', 'Remote'),
('en-us', 'aiDevelopment.fields.baseUrl', 'Base URL'),
('en-us', 'aiDevelopment.fields.model', 'Model'),
('en-us', 'aiDevelopment.fields.apiKey', 'API key'),
('en-us', 'aiDevelopment.task', 'Task'),
('en-us', 'aiDevelopment.workspace', 'Workspace'),
('en-us', 'aiDevelopment.conversations', 'Conversations'),
('en-us', 'aiDevelopment.management.createGroup', 'New group'),
('en-us', 'aiDevelopment.management.deleteGroup', 'Delete group'),
('en-us', 'aiDevelopment.management.groupName', 'Group name'),
('en-us', 'aiDevelopment.management.ungrouped', 'Ungrouped'),
('en-us', 'aiDevelopment.management.rename', 'Rename'),
('en-us', 'aiDevelopment.management.move', 'Move to group'),
('en-us', 'aiDevelopment.management.archive', 'Archive'),
('en-us', 'aiDevelopment.management.restore', 'Restore'),
('en-us', 'aiDevelopment.management.delete', 'Delete'),
('en-us', 'aiDevelopment.management.archived', 'Archived'),
('en-us', 'aiDevelopment.management.active', 'Back to conversations'),
('en-us', 'aiDevelopment.management.unread', 'Unread'),
('en-us', 'aiDevelopment.management.markRead', 'Mark as read'),
('en-us', 'aiDevelopment.management.markUnread', 'Mark as unread'),
('en-us', 'aiDevelopment.management.actions', 'Conversation actions'),
('en-us', 'aiDevelopment.management.title', 'Conversation title'),
('en-us', 'aiDevelopment.management.confirm', 'Confirm'),
('en-us', 'aiDevelopment.management.cancel', 'Cancel'),
('en-us', 'aiDevelopment.management.required', 'Name cannot be empty'),
('en-us', 'aiDevelopment.management.deleteGroupConfirm', 'Deleting this group will archive all its conversations. Continue?'),
('en-us', 'aiDevelopment.management.deleteConfirm', 'Delete this conversation? This cannot be undone.'),
('en-us', 'aiDevelopment.management.failed', 'Conversation operation failed. Please retry.'),
('en-us', 'aiDevelopment.management.syncFailed', 'Messages or read status could not be synchronized. Reopen the conversation.'),
('en-us', 'aiDevelopment.pagination.more', 'Load more'),
('en-us', 'aiDevelopment.pagination.older', 'Load older messages'),
('en-us', 'aiDevelopment.pagination.search', 'Search conversations'),
('en-us', 'aiDevelopment.pagination.unreadFilter', 'Read status'),
('en-us', 'aiDevelopment.pagination.allReadStates', 'All read states'),
('en-us', 'aiDevelopment.pagination.groupFilter', 'Filter by group'),
('en-us', 'aiDevelopment.pagination.allGroups', 'All groups'),
('en-us', 'aiDevelopment.newConversation', 'New'),
('en-us', 'aiDevelopment.unnamedConversation', 'Untitled conversation'),
('en-us', 'aiDevelopment.noConversations', 'No conversations'),
('en-us', 'aiDevelopment.selectConversation', 'Select or create a conversation'),
('en-us', 'aiDevelopment.stop', 'Stop'),
('en-us', 'aiDevelopment.send', 'Send'),
('en-us', 'aiDevelopment.promptPlaceholder', 'Describe what to analyze or change. High-risk operations pause according to the approval mode.'),
('en-us', 'aiDevelopment.newConversationTitle', 'New AI conversation'),
('en-us', 'aiDevelopment.taskContext', 'Task context'),
('en-us', 'aiDevelopment.taskAndPermissions', 'Task and permissions'),
('en-us', 'aiDevelopment.taskOverview', 'Task overview'),
('en-us', 'aiDevelopment.riskAndApproval', 'Risks and approvals'),
('en-us', 'aiDevelopment.stage', 'Stage'),
('en-us', 'aiDevelopment.status', 'Status'),
('en-us', 'aiDevelopment.test', 'Tests'),
('en-us', 'aiDevelopment.risk', 'Risk'),
('en-us', 'aiDevelopment.noPendingRisk', 'No risks awaiting approval'),
('en-us', 'aiDevelopment.noActiveTask', 'No active task'),
('en-us', 'aiDevelopment.toolLog', 'Tool log'),
('en-us', 'aiDevelopment.messages.empty', 'Start a new AI conversation'),
('en-us', 'aiDevelopment.messages.roles.system', 'System'),
('en-us', 'aiDevelopment.messages.roles.user', 'You'),
('en-us', 'aiDevelopment.messages.roles.assistant', 'AI Assistant'),
('en-us', 'aiDevelopment.messages.roles.tool', 'Tool'),
('en-us', 'aiDevelopment.approvalModes.request', 'Request approval'),
('en-us', 'aiDevelopment.approvalModes.agent', 'Approve for me'),
('en-us', 'aiDevelopment.approvalModes.fullAccess', 'Full access'),
('en-us', 'aiDevelopment.approvalModes.requestBoundary', 'Ask for approval before each dangerous tool execution.'),
('en-us', 'aiDevelopment.approvalModes.agentBoundary', 'Allow the agent to approve only within granted capabilities.'),
('en-us', 'aiDevelopment.approvalModes.fullAccessBoundary', 'Allow high-risk operations, while final ChangeSet application still requires confirmation.'),
('en-us', 'aiDevelopment.approvalModes.missingCapability', '403: missing development:ai:full-access capability'),
('en-us', 'aiDevelopment.approvalModes.unavailable', '403: full access is unavailable'),
('en-us', 'aiDevelopment.approval.required', 'Approval required'),
('en-us', 'aiDevelopment.approval.defaultRisk', 'This operation requires manual confirmation'),
('en-us', 'aiDevelopment.approval.details', 'Risk details and impact'),
('en-us', 'aiDevelopment.approval.feedbackPlaceholder', 'Optional feedback when rejecting'),
('en-us', 'aiDevelopment.approval.allowOnce', 'Allow once'),
('en-us', 'aiDevelopment.approval.allowSession', 'Allow for session operation'),
('en-us', 'aiDevelopment.approval.reject', 'Reject'),
('en-us', 'aiDevelopment.changeSet.entity', 'ChangeSet'),
('en-us', 'aiDevelopment.changeSet.title', 'ChangeSet / Diff'),
('en-us', 'aiDevelopment.changeSet.test', 'Tests: {status}'),
('en-us', 'aiDevelopment.changeSet.security', 'Security: {status}'),
('en-us', 'aiDevelopment.changeSet.fileSelectionOnly', 'Select whole files; hunk selection is unavailable'),
('en-us', 'aiDevelopment.changeSet.conflictBlocked', 'Blocked by conflicts. Deselect conflicting files or regenerate the ChangeSet.'),
('en-us', 'aiDevelopment.changeSet.previewRequired', 'Preview before applying. Final application always requires confirmation.'),
('en-us', 'aiDevelopment.changeSet.close', 'Close'),
('en-us', 'aiDevelopment.changeSet.preview', 'Preview'),
('en-us', 'aiDevelopment.changeSet.confirmApply', 'Confirm and apply'),
('en-us', 'aiDevelopment.changeSet.applyConfirm', 'The selected files will be applied to the workspace. Confirm again.'),
('en-us', 'aiDevelopment.changeSet.applyConfirmTitle', 'Final application confirmation'),
('en-us', 'aiDevelopment.changeSet.applyConfirmButton', 'Apply'),
('en-us', 'aiDevelopment.changeSet.applied', 'ChangeSet applied'),
('en-us', 'aiDevelopment.diff.binary', 'Binary files cannot display a text diff'),
('en-us', 'aiDevelopment.diff.omitted', 'Content omitted because the file is binary or exceeds the display limit'),
('en-us', 'aiDevelopment.diff.missing', 'The backend did not return diff content; only file status and hashes are shown.'),
('en-us', 'aiDevelopment.profiles.title', 'Configuration profiles'),
('en-us', 'aiDevelopment.profiles.create', 'Create profile'),
('en-us', 'aiDevelopment.profiles.general', 'Profile settings'),
('en-us', 'aiDevelopment.profiles.name', 'Name (save to rename)'),
('en-us', 'aiDevelopment.profiles.enabled', 'Enabled'),
('en-us', 'aiDevelopment.profiles.copy', 'Copy'),
('en-us', 'aiDevelopment.profiles.default', 'Set default'),
('en-us', 'aiDevelopment.profiles.copyHint', 'Copies exclude credentials and default status. Deleting the default does not select another profile.'),
('en-us', 'aiDevelopment.profiles.protocolHint', 'Only openai-chat (OpenAI Chat Completions compatible) is supported. Provider is an identifier, not support for other protocols.'),
('en-us', 'aiDevelopment.profiles.keyHint', 'Leave blank to keep the saved key'),
('en-us', 'aiDevelopment.profiles.hasKey', 'Key saved (never displayed)'),
('en-us', 'aiDevelopment.profiles.noKey', 'No saved key'),
('en-us', 'aiDevelopment.profiles.clearKey', 'Clear key on save'),
('en-us', 'aiDevelopment.profiles.models', 'Models'),
('en-us', 'aiDevelopment.profiles.fetchModels', 'Fetch saved profile models'),
('en-us', 'aiDevelopment.profiles.modelsHint', 'Uses saved URL and credentials, not unsaved edits. Search, select or enter an ID; capabilities are not inferred.'),
('en-us', 'aiDevelopment.profiles.favorites', 'Favorite models'),
('en-us', 'aiDevelopment.profiles.limits', 'Context and runtime limits'),
('en-us', 'aiDevelopment.profiles.context_window', 'Context window (blank: unspecified)'),
('en-us', 'aiDevelopment.profiles.max_input_tokens', 'Max input tokens (blank: unspecified)'),
('en-us', 'aiDevelopment.profiles.max_output_tokens', 'Max output tokens (blank: unspecified)'),
('en-us', 'aiDevelopment.profiles.max_iterations', 'Max iterations'),
('en-us', 'aiDevelopment.profiles.connect_timeout', 'Connect timeout (seconds)'),
('en-us', 'aiDevelopment.profiles.request_timeout', 'Request timeout (seconds)'),
('en-us', 'aiDevelopment.profiles.max_retries', 'Max retries'),
('en-us', 'aiDevelopment.profiles.stream_usage', 'Stream usage'),
('en-us', 'aiDevelopment.profiles.unsupported', 'Unsupported capabilities'),
('en-us', 'aiDevelopment.profiles.disabled', 'Disabled'),
('en-us', 'aiDevelopment.profiles.unsupportedHint', 'Fallback is not implemented; reasoning capabilities are unverified. Non-default execution is rejected. Saving disables fallback and clears reasoning.'),
('en-us', 'aiDevelopment.profiles.save', 'Save profile'),
('en-us', 'aiDevelopment.profiles.saved', 'Profile saved'),
('en-us', 'aiDevelopment.profiles.testHint', 'Temporary connection test only: saved credentials and token/stream parameters are not tested. Re-enter a test key; blank explicitly tests without a key, never with the global key. Keys are not stored in the browser.'),
('en-us', 'aiDevelopment.profiles.inherit', 'Use current default profile'),
('en-us', 'aiDevelopment.profiles.selectionHint', 'New conversations inherit the default at creation. Changing the default does not modify existing conversations or frozen tasks.'),
('en-us', 'aiDevelopment.profiles.invalid', 'Check model, URL, budgets and timeout ranges'),
('en-us', 'aiDevelopment.profiles.emptyModels', 'Empty model catalog; model IDs can still be entered manually'),
('en-us', 'aiDevelopment.providerSettings.title', 'Provider settings'),
('en-us', 'aiDevelopment.providerSettings.securityNotice', 'The API key is sent only for this connection test. It is never displayed or stored in the browser.'),
('en-us', 'aiDevelopment.providerSettings.apiKeyPlaceholder', 'Send only; never display'),
('en-us', 'aiDevelopment.providerSettings.configured', 'Configured: {masked}'),
('en-us', 'aiDevelopment.providerSettings.connectTimeout', 'Connection timeout'),
('en-us', 'aiDevelopment.providerSettings.requestTimeout', 'Request timeout'),
('en-us', 'aiDevelopment.providerSettings.testConnection', 'Test connection'),
('en-us', 'aiDevelopment.providerSettings.testSuccess', 'Provider connection test succeeded'),
('en-us', 'aiDevelopment.toolCalls.viewStdout', 'View stdout'),
('en-us', 'aiDevelopment.toolCalls.viewStderr', 'View stderr'),
('en-us', 'aiDevelopment.toolCalls.stdout', 'stdout'),
('en-us', 'aiDevelopment.toolCalls.stderr', 'stderr'),
('en-us', 'aiDevelopment.statuses.running', 'Running'),
('en-us', 'aiDevelopment.statuses.paused', 'Paused'),
('en-us', 'aiDevelopment.statuses.succeeded', 'Succeeded'),
('en-us', 'aiDevelopment.statuses.failed', 'Failed'),
('en-us', 'aiDevelopment.statuses.cancelled', 'Cancelled'),
('en-us', 'aiDevelopment.statuses.pending', 'Pending'),
('en-us', 'aiDevelopment.statuses.reviewing', 'Reviewing'),
('en-us', 'aiDevelopment.statuses.applying', 'Applying'),
('en-us', 'aiDevelopment.statuses.proposed', 'Proposed'),
('en-us', 'aiDevelopment.statuses.completed', 'Completed'),
('en-us', 'aiDevelopment.statuses.recovery_required', 'Recovery required'),
('en-us', 'aiDevelopment.statuses.approved', 'Approved'),
('en-us', 'aiDevelopment.statuses.rejected', 'Rejected'),
('en-us', 'aiDevelopment.statuses.awaiting_approval', 'Awaiting approval'),
('en-us', 'aiDevelopment.statuses.denied', 'Denied'),
('en-us', 'aiDevelopment.statuses.unknown', 'Unknown'),
('en-us', 'aiDevelopment.statuses.passed', 'Passed'),
('en-us', 'aiDevelopment.enums.statuses.running', 'Running'),
('en-us', 'aiDevelopment.enums.statuses.paused', 'Paused'),
('en-us', 'aiDevelopment.enums.statuses.succeeded', 'Succeeded'),
('en-us', 'aiDevelopment.enums.statuses.failed', 'Failed'),
('en-us', 'aiDevelopment.enums.statuses.cancelled', 'Cancelled'),
('en-us', 'aiDevelopment.enums.statuses.pending', 'Pending'),
('en-us', 'aiDevelopment.enums.statuses.reviewing', 'Reviewing'),
('en-us', 'aiDevelopment.enums.statuses.applying', 'Applying'),
('en-us', 'aiDevelopment.enums.statuses.proposed', 'Proposed'),
('en-us', 'aiDevelopment.enums.statuses.completed', 'Completed'),
('en-us', 'aiDevelopment.enums.statuses.recovery_required', 'Recovery required'),
('en-us', 'aiDevelopment.enums.statuses.approved', 'Approved'),
('en-us', 'aiDevelopment.enums.statuses.rejected', 'Rejected'),
('en-us', 'aiDevelopment.enums.statuses.awaiting_approval', 'Awaiting approval'),
('en-us', 'aiDevelopment.enums.statuses.denied', 'Denied'),
('en-us', 'aiDevelopment.enums.statuses.unknown', 'Unknown'),
('en-us', 'aiDevelopment.enums.statuses.passed', 'Passed'),
('en-us', 'aiDevelopment.enums.riskLevels.low', 'Low risk'),
('en-us', 'aiDevelopment.enums.riskLevels.medium', 'Medium risk'),
('en-us', 'aiDevelopment.enums.riskLevels.high', 'High risk'),
('en-us', 'aiDevelopment.enums.riskLevels.critical', 'Critical risk'),
('en-us', 'aiDevelopment.enums.operations.apply_workspace', 'Apply to workspace'),
('en-us', 'aiDevelopment.enums.operations.write_workspace', 'Write to workspace'),
('en-us', 'aiDevelopment.enums.operations.read_workspace', 'Read workspace'),
('en-us', 'aiDevelopment.enums.operations.run_command', 'Run command'),
('en-us', 'aiDevelopment.enums.fileStatuses.create', 'Create'),
('en-us', 'aiDevelopment.enums.fileStatuses.update', 'Update'),
('en-us', 'aiDevelopment.enums.fileStatuses.auto-merged', 'Auto-merged'),
('en-us', 'aiDevelopment.enums.fileStatuses.delete', 'Delete'),
('en-us', 'aiDevelopment.enums.fileStatuses.keep-local', 'Keep local'),
('en-us', 'aiDevelopment.enums.fileStatuses.conflict', 'Text conflict'),
('en-us', 'aiDevelopment.enums.fileStatuses.binary-conflict', 'Binary conflict'),
('en-us', 'aiDevelopment.enums.fileStatuses.conflict-no-base', 'Conflict without base'),
('en-us', 'aiDevelopment.enums.taskStages.planning', 'Planning'),
('en-us', 'aiDevelopment.enums.taskStages.execution', 'Execution'),
('en-us', 'aiDevelopment.enums.taskStages.review', 'Review'),
('en-us', 'aiDevelopment.enums.taskStages.applying', 'Applying'),
('en-us', 'aiDevelopment.enums.taskStages.completed', 'Completed'),
('en-us', 'aiDevelopment.enums.taskTypes.chat', 'Chat'),
('en-us', 'aiDevelopment.enums.taskTypes.crud', 'CRUD'),
('en-us', 'aiDevelopment.enums.taskTypes.code_change', 'Code change'),
('en-us', 'aiDevelopment.enums.taskTypes.fix', 'Fix'),
('en-us', 'aiDevelopment.enums.taskTypes.test', 'Test'),
('en-us', 'aiDevelopment.enums.taskTypes.migration', 'Migration'),
('en-us', 'aiDevelopment.enums.changeSetStatuses.proposed', 'Proposed'),
('en-us', 'aiDevelopment.enums.changeSetStatuses.applying', 'Applying'),
('en-us', 'aiDevelopment.enums.changeSetStatuses.completed', 'Completed'),
('en-us', 'aiDevelopment.enums.changeSetStatuses.failed', 'Failed'),
('en-us', 'aiDevelopment.enums.changeSetStatuses.recovery_required', 'Recovery required'),
('en-us', 'aiDevelopment.errors.approvalModeUpdate', 'Could not update the approval mode. Check your permissions and try again.'),
('en-us', 'aiDevelopment.errors.applyUnavailable', 'Final application approval is missing or has not been granted'),
('en-us', 'aiDevelopment.errors.generic', 'The operation failed. Please try again later.'),
('en-us', 'layout.menuSearch', 'Menu search'),
('en-us', 'layout.refresh', 'Refresh'),
('en-us', 'layout.fullscreen', 'Fullscreen'),
('en-us', 'layout.exitFullscreen', 'Exit fullscreen'),
('en-us', 'layout.toggleTheme', 'Toggle theme'),
('en-us', 'layout.language', 'Language'),
('en-us', 'layout.layoutSetting', 'Layout'),
('en-us', 'layout.notLoggedIn', 'Not logged in'),
('en-us', 'layout.guest', 'Guest'),
('en-us', 'layout.welcomeBack', 'Welcome back'),
('en-us', 'layout.profile', 'Profile'),
('en-us', 'layout.layoutSettings', 'Layout settings'),
('en-us', 'layout.logout', 'Sign out'),
('en-us', 'layout.logoutConfirm', 'Sign out now?'),
('en-us', 'layout.tip', 'Notice'),
('en-us', 'layout.localeSwitchedZh', 'Switched to Simplified Chinese'),
('en-us', 'layout.localeSwitchedEn', 'Switched to English'),
('en-us', 'layout.langZh', '简体中文'),
('en-us', 'layout.langEn', 'English'),
('en-us', 'layout.railExpandLabels', 'Show labels'),
('en-us', 'layout.railCollapseLabels', 'Hide labels'),
('en-us', 'tabs.scrollLeft', 'Scroll tabs left'),
('en-us', 'tabs.scrollRight', 'Scroll tabs right'),
('en-us', 'tabs.more', 'More'),
('en-us', 'tabs.refreshCurrent', 'Refresh current'),
('en-us', 'tabs.closeOthers', 'Close others'),
('en-us', 'tabs.closeLeft', 'Close left'),
('en-us', 'tabs.closeRight', 'Close right'),
('en-us', 'tabs.closeAll', 'Close all'),
('en-us', 'tabs.refresh', 'Refresh'),
('en-us', 'tabs.close', 'Close'),
('en-us', 'setting.title', 'Layout settings'),
('en-us', 'setting.presetTheme', 'Theme presets'),
('en-us', 'setting.layoutMode', 'Layout mode'),
('en-us', 'setting.themeMode', 'Color mode'),
('en-us', 'setting.primaryColor', 'Primary color'),
('en-us', 'setting.sidebarStyle', 'Sidebar style'),
('en-us', 'setting.uiDisplay', 'Display'),
('en-us', 'setting.uiCustomize', 'Customization'),
('en-us', 'setting.specialMode', 'Special modes'),
('en-us', 'setting.showTabs', 'Tabs'),
('en-us', 'setting.breadcrumb', 'Breadcrumb'),
('en-us', 'setting.fixedHeader', 'Fixed header'),
('en-us', 'setting.showLogo', 'Show logo'),
('en-us', 'setting.showFooter', 'Show footer'),
('en-us', 'setting.sidebarWidth', 'Sidebar width'),
('en-us', 'setting.tabStyle', 'Tab style'),
('en-us', 'setting.pageTransition', 'Page transition'),
('en-us', 'setting.customRadius', 'Corner radius'),
('en-us', 'setting.watermark', 'Watermark'),
('en-us', 'setting.watermarkText', 'Watermark text'),
('en-us', 'setting.watermarkPlaceholder', 'Watermark text'),
('en-us', 'setting.grayMode', 'Grayscale'),
('en-us', 'setting.weakMode', 'Color weakness'),
('en-us', 'setting.copyConfig', 'Copy config'),
('en-us', 'setting.resetDefault', 'Reset defaults'),
('en-us', 'setting.copySuccess', 'Copied to clipboard'),
('en-us', 'setting.copyFail', 'Copy failed'),
('en-us', 'setting.resetSuccess', 'Defaults restored'),
('en-us', 'setting.tabStyleDefault', 'Default'),
('en-us', 'setting.tabStyleCard', 'Card'),
('en-us', 'setting.tabStyleMinimal', 'Minimal'),
('en-us', 'setting.tabStylePill', 'Pill'),
('en-us', 'setting.transitionFade', 'Fade'),
('en-us', 'setting.transitionFadeSlide', 'Slide from left'),
('en-us', 'setting.transitionSlideLeft', 'Slide left'),
('en-us', 'setting.transitionFadeScale', 'Scale'),
('en-us', 'setting.transitionZoomIn', 'Zoom in'),
('en-us', 'setting.transitionNone', 'None'),
('en-us', 'setting.radius0', '0 (square)'),
('en-us', 'setting.radius025', '0.25'),
('en-us', 'setting.radius05', '0.5'),
('en-us', 'setting.radius075', '0.75'),
('en-us', 'setting.radius1', '1 (default)'),
('en-us', 'setting.radius125', '1.25'),
('en-us', 'setting.radius15', '1.5'),
('en-us', 'setting.radius2', '2'),
('en-us', 'setting.themeLight', 'Light'),
('en-us', 'setting.themeDark', 'Dark'),
('en-us', 'setting.themeAuto', 'System'),
('en-us', 'setting.layoutVertical', 'Side menu'),
('en-us', 'setting.layoutHorizontal', 'Top menu'),
('en-us', 'setting.layoutMix', 'Mixed'),
('en-us', 'setting.layoutColumns', 'Dual column'),
('en-us', 'setting.menuThemeDark', 'Dark'),
('en-us', 'setting.menuThemeLight', 'Light'),
('en-us', 'setting.menuThemeFresh', 'Fresh'),
('en-us', 'setting.preset.elegant.label', 'Elegant'),
('en-us', 'setting.preset.elegant.desc', 'Light + fresh blue'),
('en-us', 'setting.preset.fresh.label', 'Fresh'),
('en-us', 'setting.preset.fresh.desc', 'Light + cyan'),
('en-us', 'setting.preset.classic.label', 'Classic'),
('en-us', 'setting.preset.classic.desc', 'Dark sidebar + blue'),
('en-us', 'setting.preset.minimal.label', 'Minimal'),
('en-us', 'setting.preset.minimal.desc', 'Light + slate'),
('en-us', 'setting.preset.vibrant.label', 'Vibrant'),
('en-us', 'setting.preset.vibrant.desc', 'Fresh gradient + purple'),
('en-us', 'setting.preset.sunset.label', 'Sunset'),
('en-us', 'setting.preset.sunset.desc', 'Light + orange'),
('en-us', 'setting.preset.midnight.label', 'Midnight'),
('en-us', 'setting.preset.midnight.desc', 'Dark + indigo'),
('en-us', 'common.fetchPermissionFailed', 'Failed to load permissions. Please sign in again.'),
('en-us', 'common.confirm', 'OK'),
('en-us', 'common.cancel', 'Cancel'),
('en-us', 'table.reset', 'Reset'),
('en-us', 'table.search', 'Search'),
('en-us', 'table.density', 'Density'),
('en-us', 'table.densitySmall', 'Compact'),
('en-us', 'table.densityDefault', 'Default'),
('en-us', 'table.densityLarge', 'Comfortable'),
('en-us', 'table.columnSetting', 'Columns'),
('en-us', 'table.columnSettingDisabledTip', 'Pass column-options to enable column visibility'),
('en-us', 'table.columnOrderTip', 'Column order follows configuration; checkboxes show or hide columns.'),
('en-us', 'table.displaySetting', 'Table display'),
('en-us', 'table.stripe', 'Striped rows'),
('en-us', 'table.border', 'Border'),
('en-us', 'table.headerBg', 'Header background'),
('en-us', 'formDesigner.title', 'Form Designer'),
('en-us', 'formDesigner.backToList', 'Back to list'),
('en-us', 'formDesigner.subtitle', 'Drag controls onto the canvas, edit properties on the right, and preview guarded migrations before saving created tables'),
('en-us', 'formDesigner.undo', 'Undo'),
('en-us', 'formDesigner.redo', 'Redo'),
('en-us', 'formDesigner.editMode', 'Edit'),
('en-us', 'formDesigner.desktopPreview', 'Desktop preview'),
('en-us', 'formDesigner.mobilePreview', 'Mobile preview'),
('en-us', 'formDesigner.advancedJson', 'Advanced JSON'),
('en-us', 'formDesigner.exportSchema', 'Export Schema'),
('en-us', 'formDesigner.versionHistory', 'Version history'),
('en-us', 'formDesigner.reInfer', 'Infer again'),
('en-us', 'formDesigner.migrationPreview', 'Migration preview'),
('en-us', 'formDesigner.saveDraft', 'Save draft'),
('en-us', 'formDesigner.saveConflict.title', 'Review save conflict'),
('en-us', 'formDesigner.saveConflict.notice', 'Saving is paused. Both JSON documents are complete and read-only. Cancel keeps local edits and saving paused. Review again after further edits.'),
('en-us', 'formDesigner.saveConflict.hash', 'Reviewed server version hash: '),
('en-us', 'formDesigner.saveConflict.local', 'Local draft (review snapshot)'),
('en-us', 'formDesigner.saveConflict.server', 'Server version'),
('en-us', 'formDesigner.saveConflict.localJson', 'Complete local draft JSON'),
('en-us', 'formDesigner.saveConflict.serverJson', 'Complete server JSON'),
('en-us', 'formDesigner.saveConflict.risk', 'Using the server version discards unsaved local edits. Using the local snapshot replaces the reviewed server version. Both require confirmation; overwriting is rejected if the server changes again.'),
('en-us', 'formDesigner.saveConflict.review', 'Review again'),
('en-us', 'formDesigner.saveConflict.cancel', 'Cancel, keep local'),
('en-us', 'formDesigner.saveConflict.useServer', 'Discard local, use server'),
('en-us', 'formDesigner.saveConflict.useLocal', 'Overwrite with reviewed local'),
('en-us', 'formDesigner.publish', 'Publish'),
('en-us', 'formDesigner.unsaved', 'Unsaved'),
('en-us', 'formDesigner.saving', 'Saving'),
('en-us', 'formDesigner.saveFailed', 'Save failed'),
('en-us', 'formDesigner.saved', 'Saved'),
('en-us', 'formDesigner.basicInfo', 'Basic information'),
('en-us', 'formDesigner.formName', 'Form name'),
('en-us', 'formDesigner.formKey', 'Form key'),
('en-us', 'formDesigner.source', 'Source'),
('en-us', 'formDesigner.boundTable', 'Bound table'),
('en-us', 'formDesigner.namePlaceholder', 'e.g. Event registration'),
('en-us', 'formDesigner.keyPlaceholder', 'e.g. activity_form'),
('en-us', 'formDesigner.tablePlaceholder', 'e.g. fun_activity'),
('en-us', 'formDesigner.keyTip', 'Used in API and data page URLs. Start with a lowercase letter and use only lowercase letters, numbers, and underscores.'),
('en-us', 'formDesigner.createTable', 'Create new table'),
('en-us', 'formDesigner.adoptTable', 'Adopt existing table'),
('en-us', 'formDesigner.nameRequired', 'Enter a form name'),
('en-us', 'formDesigner.keyInvalid', 'Enter a valid form key'),
('en-us', 'formDesigner.tableInvalid', 'Enter a valid bound table name'),
('en-us', 'formDesigner.saveSuccess', 'Saved successfully'),
('en-us', 'formDesigner.saveError', 'Save failed. Try again.'),
('en-us', 'formDesigner.debugPanel', 'Debug panel'),
('en-us', 'formDesigner.nodes', 'Nodes'),
('en-us', 'formDesigner.fields', 'Fields'),
('en-us', 'formDesigner.containers', 'Containers'),
('en-us', 'formDesigner.maxDepth', 'Maximum depth'),
('en-us', 'formDesigner.debugValues', 'Current preview values'),
('en-us', 'formDesigner.debugConditions', 'Condition matches'),
('en-us', 'formDesigner.debugActions', 'Action trace'),
('en-us', 'formDesigner.debugDataSources', 'Data source status'),
('en-us', 'formDesigner.debugValidation', 'Validation results'),
('en-us', 'systemDept.title', 'Departments'),
('en-us', 'systemDept.subtitle', 'Maintain org structure and contacts'),
('en-us', 'systemDept.name', 'Department name'),
('en-us', 'systemDept.namePlaceholder', 'Enter department name'),
('en-us', 'systemDept.status', 'Status'),
('en-us', 'systemDept.pleaseSelect', 'Please select'),
('en-us', 'systemDept.enabled', 'Enabled'),
('en-us', 'systemDept.disabled', 'Disabled'),
('en-us', 'systemDept.add', 'Add'),
('en-us', 'systemDept.batchDelete', 'Batch delete'),
('en-us', 'systemDept.collapse', 'Collapse'),
('en-us', 'systemDept.expand', 'Expand'),
('en-us', 'systemDept.colLeader', 'Owner'),
('en-us', 'systemDept.colPhone', 'Phone'),
('en-us', 'systemDept.colEmail', 'Email'),
('en-us', 'systemDept.colSort', 'Sort'),
('en-us', 'systemDept.colActions', 'Actions'),
('en-us', 'systemDept.addChild', 'Add child'),
('en-us', 'systemDept.edit', 'Edit'),
('en-us', 'systemDept.delete', 'Delete'),
('en-us', 'systemDept.hasChildrenWarn', 'This department has children. Delete them first.'),
('en-us', 'systemDept.deleteConfirm', 'Delete department {name}?'),
('en-us', 'systemDept.selectAtLeastOne', 'Select at least one item'),
('en-us', 'systemDept.batchDeleteConfirm', '{n} selected; after deduping, {m} top-level node(s) (with descendants) will be removed. Continue?'),
('en-us', 'systemDept.dialogAdd', 'Add department'),
('en-us', 'systemDept.dialogEdit', 'Edit department'),
('en-us', 'systemDept.parentDept', 'Parent'),
('en-us', 'systemDept.parentPlaceholder', 'Leave empty for top-level'),
('en-us', 'systemDept.sort', 'Sort'),
('en-us', 'systemDept.leader', 'Owner'),
('en-us', 'systemDept.leaderPlaceholder', 'Owner name'),
('en-us', 'systemDept.phone', 'Phone'),
('en-us', 'systemDept.phonePlaceholder', 'Phone number'),
('en-us', 'systemDept.email', 'Email'),
('en-us', 'systemDept.emailPlaceholder', 'Email address'),
('en-us', 'systemDept.emailInvalid', 'Invalid email format'),
('en-us', 'enterpriseApplications.title', 'Enterprise Applications'),
('en-us', 'enterpriseApplications.subtitle', 'Manage enterprise apps, runtime data, domains, and access scope'),
('en-us', 'business.status.lifecycle.draft.label', 'Draft'),
('en-us', 'business.status.lifecycle.draft.description', 'The module is being edited and has not been published.'),
('en-us', 'business.status.lifecycle.published.label', 'Formally published'),
('en-us', 'business.status.lifecycle.published.description', 'Generated code is committed and the module is available.'),
('en-us', 'business.status.lifecycle.dynamic_published.label', 'Dynamically published'),
('en-us', 'business.status.lifecycle.dynamic_published.description', 'The module is published through the dynamic runtime.'),
('en-us', 'business.status.lifecycle.disabled.label', 'Disabled'),
('en-us', 'business.status.lifecycle.disabled.description', 'The module is disabled and unavailable.'),
('en-us', 'business.status.generation.idle.label', 'Not generated'),
('en-us', 'business.status.generation.idle.description', 'No formal generation plan has been created.'),
('en-us', 'business.status.generation.planned.label', 'Planned'),
('en-us', 'business.status.generation.planned.description', 'The generation plan is ready to run.'),
('en-us', 'business.status.generation.running.label', 'Generating'),
('en-us', 'business.status.generation.running.description', 'Files are being written and resources applied.'),
('en-us', 'business.status.generation.completed.label', 'Completed'),
('en-us', 'business.status.generation.completed.description', 'Files and resources were committed successfully.'),
('en-us', 'business.status.generation.failed.label', 'Failed'),
('en-us', 'business.status.generation.failed.description', 'Generation did not complete; review the safe error and recovery status.'),
('en-us', 'business.status.generation.conflict.label', 'Conflict'),
('en-us', 'business.status.generation.conflict.description', 'Local changes conflict with generated remote content.'),
('en-us', 'business.status.generation.superseded.label', 'Superseded'),
('en-us', 'business.status.generation.superseded.description', 'A newer generation plan replaced this plan.'),
('en-us', 'business.status.recovery.none.label', 'Not required'),
('en-us', 'business.status.recovery.none.description', 'There is no pending recovery operation.'),
('en-us', 'business.status.recovery.recovering.label', 'Recovering'),
('en-us', 'business.status.recovery.recovering.description', 'The generation transaction is being recovered deterministically.'),
('en-us', 'business.status.recovery.rolled_back.label', 'Rolled back'),
('en-us', 'business.status.recovery.rolled_back.description', 'Incomplete generation changes were safely rolled back.'),
('en-us', 'business.status.recovery.recovered_completed.label', 'Completed after recovery'),
('en-us', 'business.status.recovery.recovered_completed.description', 'Recovery confirmed the generation commit and converged successfully.'),
('en-us', 'business.status.recovery.recovery_required.label', 'Recovery required'),
('en-us', 'business.status.recovery.recovery_required.description', 'An authorized user must recover the generation transaction.'),
('en-us', 'business.status.file.create.label', 'Create'),
('en-us', 'business.status.file.create.description', 'A new generated file will be created.'),
('en-us', 'business.status.file.update.label', 'Update'),
('en-us', 'business.status.file.update.description', 'An existing generated file will be updated.'),
('en-us', 'business.status.file.auto-merged.label', 'Auto-merged'),
('en-us', 'business.status.file.auto-merged.description', 'Local and remote changes were merged automatically.'),
('en-us', 'business.status.file.delete.label', 'Delete'),
('en-us', 'business.status.file.delete.description', 'A file no longer generated by the definition will be removed.'),
('en-us', 'business.status.file.keep-local.label', 'Keep local'),
('en-us', 'business.status.file.keep-local.description', 'The local file will remain unchanged.'),
('en-us', 'business.status.file.conflict.label', 'Text conflict'),
('en-us', 'business.status.file.conflict.description', 'Base, Local, and Remote content require manual comparison.'),
('en-us', 'business.status.file.binary-conflict.label', 'Binary conflict'),
('en-us', 'business.status.file.binary-conflict.description', 'The binary file cannot be merged automatically.'),
('en-us', 'business.status.file.conflict-no-base.label', 'Conflict without base'),
('en-us', 'business.status.file.conflict-no-base.description', 'A trusted Base is unavailable, so an automatic merge is unsafe.'),
('en-us', 'business.loading', 'Loading business data'),
('en-us', 'business.loadError', 'Failed to load business data'),
('en-us', 'business.empty', 'No business data'),
('en-us', 'business.retry', 'Retry'),
('en-us', 'business.summary', 'Summary'),
('en-us', 'business.statusTitle', 'Status'),
('en-us', 'business.hashes', 'Hashes'),
('en-us', 'business.files', 'Files'),
('en-us', 'business.recovery', 'Recovery'),
('en-us', 'business.result', 'Result'),
('en-us', 'business.safeError', 'Safe error'),
('en-us', 'business.conflicts', 'Conflicts'),
('en-us', 'business.base', 'Base'),
('en-us', 'business.local', 'Local'),
('en-us', 'business.remote', 'Remote'),
('en-us', 'business.advancedJson', 'Advanced: raw JSON'),
('en-us', 'business.copy', 'Copy'),
('en-us', 'business.recover', 'Recover generation'),
('en-us', 'business.noFiles', 'No file changes'),
('en-us', 'login.brandTitle1', 'Enterprise-grade'),
('en-us', 'login.brandTitle2', 'admin, reimagined'),
('en-us', 'login.brandDesc', 'Vue 3.5 · Element Plus · Tailwind CSS · TypeScript
RBAC, dynamic routes, dark mode, layouts'),
('en-us', 'login.feat1', 'Themes & layouts in one click'),
('en-us', 'login.feat2', 'Full RBAC'),
('en-us', 'login.feat3', 'Global mock & real API'),
('en-us', 'login.feat4', 'Templates for faster delivery'),
('en-us', 'login.welcome', 'Welcome back'),
('en-us', 'login.welcomeTitle', 'Welcome back'),
('en-us', 'login.sub', 'Sign in with your account'),
('en-us', 'login.usernamePh', 'Username / email'),
('en-us', 'login.passwordPh', 'Password'),
('en-us', 'login.captchaPh', 'Captcha'),
('en-us', 'login.remember', 'Remember me'),
('en-us', 'login.forgot', 'Forgot password?'),
('en-us', 'login.submit', 'Sign in'),
('en-us', 'login.defaultAccount', 'Default: admin / 123456'),
('en-us', 'login.rulesUsername', 'Username is required'),
('en-us', 'login.rulesPassword', 'Password is required'),
('en-us', 'login.rulesCaptcha', 'Captcha is required'),
('en-us', 'login.captchaWrong', 'Invalid captcha');
