-- 028 删除 legacy int 时间列：datetime 三件套（created_at/updated_at/deleted_at）已完成切换与回填，
-- 旧 create_time/update_time/delete_time 不再被任何运行时代码读写，此处统一删除。
-- 约束：forward-only；每个操作均由 information_schema 守卫，重复执行自动跳过；
-- 含 create_time 的旧时间索引先删除再以 created_at 重建，保证时间范围查询索引不失效。
SET @schema_name = DATABASE();

-- 时间索引重建：先删旧索引，再以 created_at 建立同语义新索引。
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND INDEX_NAME='idx_admin_log_admin_time'),'ALTER TABLE `fun_admin_log` DROP INDEX `idx_admin_log_admin_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND INDEX_NAME='idx_admin_log_admin_time'),'ALTER TABLE `fun_admin_log` ADD INDEX `idx_admin_log_admin_time` (`admin_id`,`created_at`)','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND INDEX_NAME='idx_admin_log_app_time'),'ALTER TABLE `fun_admin_log` DROP INDEX `idx_admin_log_app_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND INDEX_NAME='idx_admin_log_app_time'),'ALTER TABLE `fun_admin_log` ADD INDEX `idx_admin_log_app_time` (`app_name`,`created_at`)','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND INDEX_NAME='idx_admin_log_create_time'),'ALTER TABLE `fun_admin_log` DROP INDEX `idx_admin_log_create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND INDEX_NAME='idx_admin_log_created_at'),'ALTER TABLE `fun_admin_log` ADD INDEX `idx_admin_log_created_at` (`created_at`)','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND INDEX_NAME='idx_admin_log_source_time'),'ALTER TABLE `fun_admin_log` DROP INDEX `idx_admin_log_source_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND INDEX_NAME='idx_admin_log_source_time'),'ALTER TABLE `fun_admin_log` ADD INDEX `idx_admin_log_source_time` (`source_type`,`source_name`,`created_at`)','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND INDEX_NAME='idx_admin_log_status_time'),'ALTER TABLE `fun_admin_log` DROP INDEX `idx_admin_log_status_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND INDEX_NAME='idx_admin_log_status_time'),'ALTER TABLE `fun_admin_log` ADD INDEX `idx_admin_log_status_time` (`status`,`created_at`)','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_operation' AND INDEX_NAME='idx_plugin_operation_name_time'),'ALTER TABLE `fun_plugin_operation` DROP INDEX `idx_plugin_operation_name_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_operation' AND INDEX_NAME='idx_plugin_operation_name_time'),'ALTER TABLE `fun_plugin_operation` ADD INDEX `idx_plugin_operation_name_time` (`plugin_name`,`created_at`)','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_version_history' AND INDEX_NAME='idx_plugin_version_name_time'),'ALTER TABLE `fun_plugin_version_history` DROP INDEX `idx_plugin_version_name_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_version_history' AND INDEX_NAME='idx_plugin_version_name_time'),'ALTER TABLE `fun_plugin_version_history` ADD INDEX `idx_plugin_version_name_time` (`plugin_name`,`created_at`)','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

-- 逐表删除 legacy 时间列。
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_admin` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_admin` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_admin` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_admin_log` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_admin_log` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_log' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_admin_log` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_menu' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_admin_menu` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_admin_menu' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_admin_menu` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_attach` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_attach` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_attach` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach_group' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_attach_group` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach_group' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_attach_group` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_attach_group' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_attach_group` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_auth_group` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_auth_group` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_auth_group` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group_department' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_auth_group_department` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_auth_group_inherit' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_auth_group_inherit` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_blacklist' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_blacklist` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_blacklist' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_blacklist` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_blacklist' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_blacklist` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_config` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_config` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_config` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config_group' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_config_group` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config_group' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_config_group` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_config_group' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_config_group` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_department' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_department` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_department' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_department` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_department' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_department` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_item' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_dict_item` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_item' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_dict_item` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_item' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_dict_item` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_type' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_dict_type` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_type' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_dict_type` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_dict_type' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_dict_type` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_field_type' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_field_type` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_field_verify' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_field_verify` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_languages' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_languages` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_languages' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_languages` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_languages' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_languages` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_member` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_member` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_member` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_group' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_member_group` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_group' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_member_group` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_group' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_member_group` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_group_relation' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_member_group_relation` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_level' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_member_level` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_level' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_member_level` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_member_level' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_member_level` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_permission' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_permission` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_permission' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_permission` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_plugin` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_plugin` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_plugin` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_operation' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_plugin_operation` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_operation' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_plugin_operation` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_version_history' AND COLUMN_NAME='create_time'),'ALTER TABLE `fun_plugin_version_history` DROP COLUMN `create_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_plugin_version_history' AND COLUMN_NAME='update_time'),'ALTER TABLE `fun_plugin_version_history` DROP COLUMN `update_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_provinces' AND COLUMN_NAME='delete_time'),'ALTER TABLE `fun_provinces` DROP COLUMN `delete_time`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
