-- 插件资源注册表 M7 收敛：统一 plugin_name/version/source_path/target_path/sha256/created_at/updated_at 正式字段。
SET @schema_name = DATABASE();
SET @table_name = 'fun_plugin_resource';

SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME=@table_name AND COLUMN_NAME='plugin') AND NOT EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME=@table_name AND COLUMN_NAME='plugin_name'),'ALTER TABLE `fun_plugin_resource` CHANGE COLUMN `plugin` `plugin_name` varchar(100) NOT NULL','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME=@table_name AND COLUMN_NAME='updated_at'),'ALTER TABLE `fun_plugin_resource` ADD COLUMN `updated_at` datetime NULL AFTER `created_at`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME=@table_name AND COLUMN_NAME='create_time') AND NOT EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME=@table_name AND COLUMN_NAME='created_at'),'ALTER TABLE `fun_plugin_resource` CHANGE COLUMN `create_time` `created_at` datetime NOT NULL','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME=@table_name AND COLUMN_NAME='create_time'),'UPDATE `fun_plugin_resource` SET `created_at`=COALESCE(`created_at`,`create_time`)','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
-- M7 不删除 legacy 列或旧索引；仅在不存在时补充正式索引，清理由 M8 maintenance 执行。
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME=@table_name AND INDEX_NAME='uk_plugin_resource_target_path'),'ALTER TABLE `fun_plugin_resource` ADD UNIQUE KEY `uk_plugin_resource_target_path` (`target_path`)','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME=@table_name AND INDEX_NAME='idx_plugin_resource_owner'),'ALTER TABLE `fun_plugin_resource` ADD KEY `idx_plugin_resource_owner` (`plugin_name`,`version`)','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
