-- 092 AI durable events, SSE nonces, and queue storage; forward-only.
SET @schema_name=DATABASE();
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_ai_task_event'),'CREATE TABLE `fun_ai_task_event` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`task_id` bigint unsigned NOT NULL,`sequence` bigint unsigned NOT NULL,`type` varchar(64) NOT NULL,`payload` json NOT NULL,`created_at` datetime NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `uk_ai_task_event_sequence` (`task_id`,`sequence`),KEY `idx_ai_task_event_cursor` (`task_id`,`id`),CONSTRAINT `fk_ai_task_event_task` FOREIGN KEY (`task_id`) REFERENCES `fun_ai_task` (`id`) ON DELETE CASCADE ON UPDATE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_ai_stream_nonce'),'CREATE TABLE `fun_ai_stream_nonce` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`nonce_hash` char(64) NOT NULL,`expires_at` datetime NOT NULL,`consumed_at` datetime NOT NULL,`created_at` datetime NOT NULL,PRIMARY KEY (`id`),UNIQUE KEY `uk_ai_stream_nonce` (`nonce_hash`),KEY `idx_ai_stream_nonce_expiry` (`expires_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_jobs'),'CREATE TABLE `fun_jobs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`queue` varchar(255) NOT NULL,`payload` longtext NOT NULL,`attempts` tinyint unsigned NOT NULL DEFAULT 0,`reserved_at` int unsigned NULL,`available_at` int unsigned NOT NULL,`created_at` int unsigned NOT NULL,PRIMARY KEY (`id`),KEY `idx_jobs_queue_reserved` (`queue`,`reserved_at`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.TABLES WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_failed_jobs'),'CREATE TABLE `fun_failed_jobs` (`id` bigint unsigned NOT NULL AUTO_INCREMENT,`connection` text NOT NULL,`queue` text NOT NULL,`payload` longtext NOT NULL,`exception` longtext NOT NULL,`fail_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY (`id`)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ai_group_id=(SELECT `id` FROM `fun_permission` WHERE `source_type`='admin_web' AND `source_name`='ai_development' AND `resource_type`='group' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `fun_permission` (`pid`,`app_name`,`code`,`obj`,`act`,`name`,`resource_type`,`status`,`is_public`,`source_type`,`source_name`,`created_at`,`updated_at`,`sort_order`,`deleted_at`) VALUES
(@ai_group_id,'console','console/development.ai:conversationCreate','console/development.ai','conversationCreate',CONVERT(X'E5889BE5BBBAE4BC9AE8AF9D' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),80,NULL),
(@ai_group_id,'console','console/development.ai:conversationRead','console/development.ai','conversationRead',CONVERT(X'E69FA5E79C8BE4BC9AE8AF9D' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),81,NULL),
(@ai_group_id,'console','console/development.ai:conversationUpdate','console/development.ai','conversationUpdate',CONVERT(X'E69BB4E696B0E4BC9AE8AF9D' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),82,NULL),
(@ai_group_id,'console','console/development.ai:conversationDelete','console/development.ai','conversationDelete',CONVERT(X'E588A0E999A4E4BC9AE8AF9D' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),83,NULL),
(@ai_group_id,'console','console/development.ai:messageIndex','console/development.ai','messageIndex',CONVERT(X'E6B688E681AFE58897E8A1A8' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),84,NULL),
(@ai_group_id,'console','console/development.ai:taskCancel','console/development.ai','taskCancel',CONVERT(X'E58F96E6B688E4BBBBE58AA1' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),85,NULL),
(@ai_group_id,'console','console/development.ai:eventTicket','console/development.ai','eventTicket',CONVERT(X'E4BA8BE4BBB6E7A5A8E68DAE' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),86,NULL),
(@ai_group_id,'console','console/development.ai:eventStream','console/development.ai','eventStream',CONVERT(X'E4BA8BE4BBB6E6B581' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),87,NULL),
(@ai_group_id,'console','console/development.ai:settingsRead','console/development.ai','settingsRead',CONVERT(X'E69FA5E79C8BE9858DE7BDAE' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),88,NULL),
(@ai_group_id,'console','console/development.ai:settingsTest','console/development.ai','settingsTest',CONVERT(X'E6B58BE8AF95E9858DE7BDAE' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),89,NULL);
