-- 094 AI agent sandbox runtime fields and phase-three action permissions; forward-only.
SET @schema_name=DATABASE();
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_ai_task' AND COLUMN_NAME='workspace_path'),'ALTER TABLE `fun_ai_task` ADD COLUMN `workspace_path` varchar(1024) NULL AFTER `container_task_id`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_ai_task' AND COLUMN_NAME='sandbox_status'),'ALTER TABLE `fun_ai_task` ADD COLUMN `sandbox_status` enum(\'pending\',\'created\',\'running\',\'cleaned\',\'failed\') NOT NULL DEFAULT \'pending\' AFTER `workspace_path`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_ai_task' AND COLUMN_NAME='cleanup_at'),'ALTER TABLE `fun_ai_task` ADD COLUMN `cleanup_at` datetime NULL AFTER `completed_at`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(NOT EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_ai_task' AND INDEX_NAME='idx_ai_task_sandbox_status'),'ALTER TABLE `fun_ai_task` ADD KEY `idx_ai_task_sandbox_status` (`sandbox_status`,`updated_at`)','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @ai_group_id=(SELECT `id` FROM `fun_permission` WHERE `source_type`='admin_web' AND `source_name`='ai_development' AND `resource_type`='group' ORDER BY `id` LIMIT 1);
INSERT IGNORE INTO `fun_permission` (`pid`,`app_name`,`code`,`obj`,`act`,`name`,`resource_type`,`status`,`is_public`,`source_type`,`source_name`,`created_at`,`updated_at`,`sort_order`,`deleted_at`) VALUES
(@ai_group_id,'console','console/development.ai:approvalIndex','console/development.ai','approvalIndex',CONVERT(X'E5AEA1E689B9E5BE85E58A9E' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),90,NULL),
(@ai_group_id,'console','console/development.ai:approvalDecide','console/development.ai','approvalDecide',CONVERT(X'E5AEA1E689B9E586B3E7AD96' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),91,NULL),
(@ai_group_id,'console','console/development.ai:taskToolCalls','console/development.ai','taskToolCalls',CONVERT(X'E5B7A5E585B7E8B083E794A8' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),92,NULL),
(@ai_group_id,'console','console/development.ai:toolCallLog','console/development.ai','toolCallLog',CONVERT(X'E5B7A5E585B7E697A5E5BF97' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),93,NULL),
(@ai_group_id,'console','console/development.ai:sandboxStatus','console/development.ai','sandboxStatus',CONVERT(X'E6B299E7AEB1E78AB6E68081' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),94,NULL),
(@ai_group_id,'console','console/development.ai:sandboxCleanup','console/development.ai','sandboxCleanup',CONVERT(X'E6B299E7AEB1E6B885E79086' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),95,NULL);
