-- 112 启用 091 已登记的 AI Admin Web 菜单，并补齐阶段五页面权限；forward-only、幂等。
SET @ai_group_id=(SELECT `id` FROM `fun_permission` WHERE `source_type`='admin_web' AND `source_name`='ai_development' AND `resource_type`='group' ORDER BY `id` LIMIT 1);
SET @ai_view_id=(SELECT `id` FROM `fun_permission` WHERE `code`='console/development.ai:conversationindex' ORDER BY `id` LIMIT 1);
UPDATE `fun_admin_menu` SET `pid`=COALESCE((SELECT `id` FROM (SELECT `id` FROM `fun_admin_menu` WHERE `source_type`='admin_web' AND `source_name`='development_tools' ORDER BY `id` LIMIT 1) development_menu),0),`permission_id`=@ai_view_id,`app_name`='console',`name`=CONVERT(X'E699BAE883BDE5BC80E58F91E58AA9E6898B' USING utf8mb4),`href`='/development/ai',`query`='component=development/ai/index&name=AiDevelopment&type=C&permission=development:ai:view',`target`='_self',`icon`='i-ep-cpu',`status`=1,`updated_at`=NOW(),`sort_order`=30,`deleted_at`=NULL WHERE `source_type`='admin_web' AND `source_name`='ai_development' AND `href`='/development/ai';
INSERT IGNORE INTO `fun_permission` (`pid`,`app_name`,`code`,`obj`,`act`,`name`,`resource_type`,`status`,`is_public`,`source_type`,`source_name`,`created_at`,`updated_at`,`sort_order`,`deleted_at`) VALUES
(@ai_group_id,'console','development:ai:full-access','development/ai','full-access',CONVERT(X'E5AE8CE585A8E8AEBFE997AEE69D83E99990' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),180,NULL),
(@ai_group_id,'console','development:ai:changesetpreview','development/ai','changesetpreview',CONVERT(X'E9A284E8A788E58F98E69BB4E99B86' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),190,NULL),
(@ai_group_id,'console','development:ai:changesetapply','development/ai','changesetapply',CONVERT(X'E5BA94E794A8E58F98E69BB4E99B86' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),200,NULL),
(@ai_group_id,'console','console/development.ai:taskread','console/development.ai','taskread',CONVERT(X'E4BBBBE58AA1E8AFA6E68385' USING utf8mb4),'route',1,0,'admin_web','ai_development',NOW(),NOW(),201,NULL);
