-- 113 OIDC Phase 7 阻断修复：授权会话关联与 backchannel 投递租约；forward-only、幂等。
SET @schema_name=DATABASE();

SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_oauth_authorization' AND COLUMN_NAME='oidc_session_id'),'DO 0','ALTER TABLE `fun_oauth_authorization` ADD COLUMN `oidc_session_id` bigint unsigned NULL AFTER `session_id`'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_oauth_authorization' AND COLUMN_NAME='client_session_id'),'DO 0','ALTER TABLE `fun_oauth_authorization` ADD COLUMN `client_session_id` bigint unsigned NULL AFTER `oidc_session_id`'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_oauth_authorization' AND INDEX_NAME='idx_oauth_authorization_oidc_session'),'DO 0','ALTER TABLE `fun_oauth_authorization` ADD KEY `idx_oauth_authorization_oidc_session` (`tenant_id`,`oidc_session_id`,`client_session_id`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @column_type=(SELECT COLUMN_TYPE FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_oauth_authorization' AND COLUMN_NAME='status' LIMIT 1);
SET @sql=IF(@column_type LIKE '%revoked%','DO 0','ALTER TABLE `fun_oauth_authorization` MODIFY COLUMN `status` enum(''pending'',''approved'',''denied'',''completed'',''expired'',''revoked'') NOT NULL DEFAULT ''pending'''); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_oidc_client_session' AND INDEX_NAME='idx_oidc_client_session_op_fk'),'DO 0','ALTER TABLE `fun_oidc_client_session` ADD KEY `idx_oidc_client_session_op_fk` (`tenant_id`,`oidc_session_id`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_oidc_client_session' AND INDEX_NAME='idx_oidc_client_session_client_fk'),'DO 0','ALTER TABLE `fun_oidc_client_session` ADD KEY `idx_oidc_client_session_client_fk` (`tenant_id`,`client_id`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_oidc_client_session' AND INDEX_NAME='uk_oidc_client_session_binding'),'ALTER TABLE `fun_oidc_client_session` DROP INDEX `uk_oidc_client_session_binding`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_oidc_client_session' AND INDEX_NAME='idx_oidc_client_session_binding'),'DO 0','ALTER TABLE `fun_oidc_client_session` ADD KEY `idx_oidc_client_session_binding` (`tenant_id`,`oidc_session_id`,`client_id`,`status`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;

SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_backchannel_logout_delivery' AND COLUMN_NAME='worker_id'),'DO 0','ALTER TABLE `fun_backchannel_logout_delivery` ADD COLUMN `worker_id` varchar(128) NULL AFTER `locked_at`'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_backchannel_logout_delivery' AND COLUMN_NAME='lock_token'),'DO 0','ALTER TABLE `fun_backchannel_logout_delivery` ADD COLUMN `lock_token` char(64) NULL AFTER `worker_id`'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.COLUMNS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_backchannel_logout_delivery' AND COLUMN_NAME='lease_expires_at'),'DO 0','ALTER TABLE `fun_backchannel_logout_delivery` ADD COLUMN `lease_expires_at` datetime NULL AFTER `lock_token`'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_backchannel_logout_delivery' AND INDEX_NAME='uk_backchannel_logout_delivery_session'),'ALTER TABLE `fun_backchannel_logout_delivery` DROP INDEX `uk_backchannel_logout_delivery_session`','DO 0'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_backchannel_logout_delivery' AND INDEX_NAME='idx_backchannel_logout_delivery_session'),'DO 0','ALTER TABLE `fun_backchannel_logout_delivery` ADD KEY `idx_backchannel_logout_delivery_session` (`tenant_id`,`client_session_id`,`oidc_session_id`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @sql=IF(EXISTS(SELECT 1 FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=@schema_name AND TABLE_NAME='fun_backchannel_logout_delivery' AND INDEX_NAME='idx_backchannel_logout_delivery_claim'),'DO 0','ALTER TABLE `fun_backchannel_logout_delivery` ADD KEY `idx_backchannel_logout_delivery_claim` (`status`,`next_attempt_at`,`lease_expires_at`,`id`)'); PREPARE stmt FROM @sql; EXECUTE stmt; DEALLOCATE PREPARE stmt;
