<?php
/**
 * funadmin
 * ============================================================================
 * 版权所有 2018-2027 funadmin，并保留所有权利。
 * 网站地址: https://www.funadmin.com
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/8/26
 */
namespace addons\bbs\backend\controller;
use app\common\controller\AddonsBackend;
use think\facade\Request;
use addons\bbs\common\model\BbsComment as CommentModel;

class Comment extends AddonsBackend
{

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        if ($this->request->isPost()) {
            $keys = $this->request->post('keys', '', 'trim');
            $page = $this->request->post('page') ? $this->request->post('page') : 1;
            $list = CommentModel::where('content', 'like', '%' . $keys . '%')
                ->paginate(['list_rows' => $this->pageSize, 'page' => $page])
                ->toArray();

            return $result = ['code' => 0, 'msg' => lang('get info success'), 'data' => $list['data'], 'count' => $list['total']];
        }

        return view();

    }


    public function delete()
    {
        $ids = $this->request->post('ids');
        if ($ids) {
            $model = new CommentModel();
            $res = $model->del($ids);
            $this->success(lang('operation success'));
        } else {
            $this->error(lang('delete fail'));

        }
    }

    public function state()
    {
        $id = $this->request->post('id');
        $post = $this->request->post();
        if ($id and isset($post['field'])) {
            $model = new CommentModel();
            $res = $model->state($post);
            $this->success(lang('operation success'));

        } else {
            $this->error(lang('edit fail'));

        }


    }
}