<?php
/**
 * SpeedAdmin
 * ============================================================================
 * 版权所有 2018-2027 SpeedAdmin，并保留所有权利。
 * 网站地址: https://www.SpeedAdmin.cn
 * ----------------------------------------------------------------------------
 * 采用最新Thinkphp6实现
 * ============================================================================
 * Author: yuege
 * Date: 2019/8/2
 */
namespace app\backend\controller\ucenter;

use app\common\controller\Backend;
use app\common\traits\Curd;
use think\exception\ValidateException;
use think\facade\Request;
use think\facade\View;
use app\common\model\UserLevel;
use app\backend\model\UserGroup;
use app\backend\model\User as UserModel;
use think\App;
class User extends Backend{

    use Curd;

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function __construct(App $app)
    {
        parent::__construct($app);
        $this->modelClass =  new UserModel();
    }

    public function index(){
        if ($this->request->isAjax()) {
            list($this->page, $this->pageSize,$sort,$where) = $this->buildParames();
            $count = $this->modelClass->with('group')
                ->where($where)
                ->count();
            $list =$this->modelClass
                ->with('userGroup')
                ->with('userLevel')
                ->where($where)
                ->order($sort)
                ->page( $this->page,$this->pageSize)
                ->select();
             $result = ['code' => 0, 'msg' => lang('get info success'), 'data' => $list, 'count' => $count];
             return json($result);
        }
        return view();

    }

    public function add(){
        if ($this->request->isPost()) {
            $data = $this->request->post();
            $rule = [
                'username|用户名'   => 'require|unique:user',
            ];
            try{
                $this->validate($data, $rule);
            }catch (\ValidateException $e){
                $this->error($e->getMessage());
            }
            $save =$this->modelClass->save($data);
            if ($save) {
                $this->success(lang('add success'),url('index'));
            } else {
                $this->error(lang('add fail'));
            }
        }
        $userLevel = UserLevel::where('status',1)->select();
        $userGroup = UserGroup::where('status',1)->select();

        $view = [
            'formData' => '',
            'title' => lang('Add'),
            'userLevel'=>$userLevel,
            'userGroup'=>$userGroup,
        ];
        View::assign($view);
        return view();
    }

    public function edit($id){
        if ($this->request->isPost()) {
            $list  = $this->modelClass->find($id);
            empty($list) && $this->error(lang('Data is not exist'));
            $data = $this->request->post();
            $rule = [
                'username|用户名'   => 'require',
                'group_id|用户组别'   => 'require',
                'level_id|用户级别'   => 'require',
            ];
            try{
                $this->validate($data, $rule);
            }catch (\ValidateException $e){
                $this->error($e->getMessage());
            }
            $res = $list->save($data);
            if ($res) {
                $this->success(lang('Edit success'), url('index'));
            } else {
                $this->error(lang('Edit fail'));
            }
        }
        $list = UserModel::find(Request::get('id'));
        $userLevel = UserLevel::where('status',1)->select();
        $userGroup = UserGroup::where('status',1)->select();
        $view = [
            'formData' => $list,
            'title' => lang('Edit'),
            'userLevel'=>$userLevel,
            'userGroup'=>$userGroup,

        ];
        View::assign($view);
        return view('add');

    }

    /**
     * 修改
     */
    public function modify(){
        $data = $this->request->post();
        $id = input('id');
        $field = input('field');
        if($id){
            $model = new UserModel();
            $res =$model->state($data);
            $this->success(lang('Edit success'));

        }else{
            $this->error(lang('Invalid data'));
        }
    }




}