<?php
namespace app\backend\controller\ucenter;

use app\backend\model\UserLevel as UserLevelModel;
use app\common\controller\Backend;
use app\common\traits\Curd;
use think\facade\Request;
use think\App;
class UserLevel extends Backend{

    use Curd;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
    public function __construct(App $app)
    {
        parent::__construct($app);
        $this->modelClass = new UserLevelModel();
    }

    /**---------------用户等级--------------------**/

    public function add(){
        if ($this->request->isPost()) {
            $post = $this->request->post();
            $rule = 'UserLevel';
            try{
                $this->validate($post, $rule);
            }catch (\ValidateException $e){
                $this->error($e->getMessage());
            }
            try {
                $save = $this->modelClass->save($post);
            } catch (\Exception $e) {
                $this->error(lang('Save failed'));
            }
            $save ? $this->success(lang('Save success')) : $this->error(lang('Save failed'));
        }
        $view = [
            'formData' => '',
            'title' => lang('Add'),
        ];
        return view('',$view);
    }




}