<template>
  <PageWrapper :title="t('crud.test.page.title', 'test')">
<SchemaTablePage ref="buttonTable" class="min-w-0 flex-1" storage-key="generated-test" :schema="tableSchema" :query="query" :rows="list" :total="total" :loading="loading" :lock="buttonLock" :context="{ values: {}, permissions: buttonUser.permissions, handlers: {} }" @refresh="refreshButtonHost" @sort-change="({ prop, order }) => { query.sort = prop ?? ''; query.order = order === 'descending' ? 'desc' : 'asc'; loadData(); }" @selection-change="handleSelectionChange">      <template #search><SearchForm :model="query" :loading="loading" @search="onSearch" @reset="onReset"></SearchForm></template>
<template #toolbar><ListButtonBar :buttons="toolbarButtons" :handlers="buttonHandlers" :allowed="toolbarButtonAllowed" :lock="buttonLock" :refresh="refreshButtonHost" :context="buttonContext('toolbar')" :context-version="buttonContextVersion" :permission-check="buttonPermission" :clear-selection="clearButtonSelection" :close="closeButtonHost" /><input ref="fileInput" class="hidden" type="file" accept=".csv,text/csv" @change="importCsv" /></template><template #id="scope"><span>{{ presentField('id', scope.row) }}</span></template><template #field1="scope"><span>{{ presentField('field1', scope.row) }}</span></template><template #field2="scope"><span>{{ presentField('field2', scope.row) }}</span></template><template #field3="scope"><span>{{ presentField('field3', scope.row) }}</span></template><template #actions="scope"><ListButtonBar :buttons="rowButtons" :handlers="buttonHandlers" :allowed="buttonAllowed" :row="scope.row" :values="buttonValues(scope.row)" :fields="Object.keys(buttonFieldMap)" :lock="buttonLock" :refresh="refreshButtonHost" :context="buttonContext('row', scope.row)" :context-version="buttonContextVersion" :permission-check="buttonPermission" :clear-selection="clearButtonSelection" :close="closeButtonHost" link /></template></SchemaTablePage><TestForm :lock="buttonLock" v-model="dialogVisible" :row="current" @success="refreshAfterSave" /><TestDetail v-model="drawerVisible" :row="current" />
  </PageWrapper>
</template>
<script setup lang="ts">
import { computed, onBeforeUnmount, ref, reactive, watch } from 'vue';
import { ElMessage } from 'element-plus';
import { useI18n } from 'vue-i18n';
import { useCrud } from '@/composables/useCrud';
import { downloadCsv, parseCsv, readFileAsText, toCsv, type CsvColumn } from '@/utils/csv';
import ListButtonBar from '@/views/form/components/ListButtonBar.vue';
import { resolveListButtons, buildListFieldMap } from '@/views/form/schema/listButtons';
import { provideListButtonAdapter, listButtonAdapterAllowed, listActionKey, type ListButtonHandlers } from '@/views/form/runtime/listButtonHost';
import type { ListButtonContext } from '@/views/form/runtime/listButtonExecutor';
import type { FormListConfiguration, FormListButton } from '@/views/form/schema/types';
import { useUserStore } from '@/store/modules/user';
import SchemaTablePage from '@/components/DataTable/SchemaTablePage.vue';
import type { PageSchema } from '@/components/DataTable/pageSchema';
import { formatFieldValue, resolveFieldOptions } from '@/views/form/runtime/fieldPresentation';
import { useSuppliedFieldOptions } from '@/views/form/runtime/fieldPresentation';
import { testApi, type TestModel, type TestModelPayload, type TestModelQuery } from './api';
import TestForm from './components/TestForm.vue';
import TestDetail from './components/TestDetail.vue';
const { loading, list, total, query, loadData, onSearch, onReset, selection, onSelectionChange, onBatchDelete, current, dialogVisible, onAdd, onEdit, drawerVisible, onOpenDrawer } = useCrud<TestModel, TestModelQuery, TestModel['id']>({ api: { list: testApi.list, removeMany: testApi.removeMany }, initialQuery: () => ({ page: 1, pageSize: 20, recycled: 0 }), rowKey: 'id', pagination: true });
const { t } = useI18n();
const presentationValues = (values: Record<string, unknown>) => ({ "id": values["id"], "field_1": values["field1"], "field_2": values["field2"], "field_3": values["field3"], "created_at": values["createdAt"], "updated_at": values["updatedAt"], "deleted_at": values["deletedAt"] });
const fieldOptions = useSuppliedFieldOptions(() => list.value.map(row => presentationValues({ ...row })));
const presentationSources: Record<string, string> = {};
void fieldOptions.load("test", [{"id":"id","field":"id","dataSource":{"kind":"static","options":[]}},{"id":"field1","field":"field_1","dataSource":{"kind":"static","options":[]}},{"id":"field2","field":"field_2","dataSource":{"kind":"static","mode":"static","options":[{"label":"张三","value":1},{"label":"李四","value":2}]}},{"id":"field3","field":"field_3","dataSource":{"kind":"static","mode":"static","options":[{"label":"选项一","value":1},{"label":"选项二","value":2}]}}]);
const filterNodes = [] as import('@/views/form/runtime/fieldPresentation').PresentationNode[];
const filterOptions = useSuppliedFieldOptions(() => presentationValues(query as Record<string, unknown>));
void filterOptions.load("test", filterNodes);
const fieldPresentations = { "id": { node: {"id":"id","field":"id","dataSource":{"kind":"static","options":[]}}, formatter: "" }, "field1": { node: {"id":"field1","field":"field_1","dataSource":{"kind":"static","options":[]}}, formatter: "" }, "field2": { node: {"id":"field2","field":"field_2","dataSource":{"kind":"static","mode":"static","options":[{"label":"张三","value":1},{"label":"李四","value":2}]}}, formatter: "" }, "field3": { node: {"id":"field3","field":"field_3","dataSource":{"kind":"static","mode":"static","options":[{"label":"选项一","value":1},{"label":"选项二","value":2}]}}, formatter: "" } };
const presentField = (field: keyof typeof fieldPresentations, row: Record<string, unknown>) => { const values = presentationValues(row); const item = fieldPresentations[field]; return fieldOptions.placeholder(field, values) || formatFieldValue(row[field], resolveFieldOptions(item.node, fieldOptions.forContext(values)), item.formatter, 'published'); };
const listConfig = {} as FormListConfiguration;
const buttonUser = useUserStore();
const buttonLock = reactive({ busy: false });
let hostActive = true;
onBeforeUnmount(() => { hostActive = false; });
async function refreshAfterSave() { if (!hostActive) return; try { await refreshButtonHost(); } catch { if (hostActive) ElMessage.warning(t('crud.test.message.refreshFailed', '操作已成功，但列表刷新失败，请手动刷新，不要重复提交')); } }
const buttonAdapter = undefined;
const buttonFieldMap = buildListFieldMap(["id","field_1","field_2","field_3","created_at","updated_at","deleted_at"], 'camel');
const buttonSelection = ref<TestModel[]>([]);
const buttonContextVersion = ref(0);
const buttonTable = ref<{ clearSelection: () => void }>();
const clearButtonSelection = () => { buttonSelection.value = []; buttonTable.value?.clearSelection(); buttonContextVersion.value++; };
const buttonFilter = () => Object.fromEntries(([] as unknown[][]).filter((entry): entry is [string, string | number] => typeof entry[0] === 'string' && (typeof entry[1] === 'string' || typeof entry[1] === 'number') && entry[1] !== ''));
const buttonContext = (location: 'row' | 'toolbar', row?: Record<string, unknown>): ListButtonContext => ({ formKey: '', schemaHash: '', location, filter: buttonFilter(), ids: (row ? [row] : buttonSelection.value).map(record => record['id'] as string | number) });
const closeButtonHost = () => { dialogVisible.value = false; drawerVisible.value = false;  };
const buttonValues = (row: Record<string, unknown>) => Object.fromEntries(Object.entries(buttonFieldMap).map(([field, alias]) => [field, row[alias]]));
function resolveButtonRow(row?: Record<string, unknown>): TestModel { const current = list.value.find(item => item.id === row?.['id']); if (!current) throw new Error(t('crud.test.message.contextExpired', '记录上下文已失效')); return current; }
const buttonActionLabels = computed<Record<string, string>>(() => ({ 'normal': t('crud.test.action.normalList', '正常列表'), 'recycle': t('crud.test.action.recycleBin', '回收站'), 'create': t('crud.test.action.create', '新增'), 'batchDelete': t('crud.test.action.batchDestroy', '移入回收站'), 'import': t('crud.test.action.import', 'CSV 导入'), 'export': t('crud.test.action.export', 'CSV 导出'), 'edit': t('crud.test.action.edit', '编辑'), 'detail': t('crud.test.action.detail', '详情'), 'delete': t('crud.test.action.destroy', '删除'), 'restore': t('crud.test.action.restore', '恢复'), 'destroy': t('crud.test.action.forceDestroy', '永久删除') }));
const buttonBatchLabels = computed<Record<string, string>>(() => ({ 'restoreselected': t('crud.test.action.batchRestore', '批量恢复'), 'destroyselected': t('crud.test.action.batchForceDestroy', '批量永久删除') }));
const localizeButtons = (buttons: FormListButton[]): FormListButton[] => buttons.map(button => { const key = listActionKey(button); const label = buttonBatchLabels.value[button.id] ?? buttonActionLabels.value[key] ?? button.label; let interaction = button.interaction; if (interaction?.type === 'confirm') { interaction = { ...interaction, message: button.id === 'destroyselected' ? t('crud.test.message.batchForceDestroyConfirm', '确认永久删除选中记录？此操作不可恢复。') : t('crud.test.message.destroyConfirm', { label }, { default: '确认{label}？此操作可能不可恢复。' }) }; } return { ...button, label, interaction }; });
const buttonHandlers: ListButtonHandlers = { refresh: () => loadData(), normal: () => switchMode(false), recycle: () => switchMode(true), create: () => onAdd(), batchDelete: async () => { await testApi.removeMany(selectedIds()); await refreshAfterSave(); }, import: () => fileInput.value?.click(), export: () => exportRows(), edit: row => onEdit(resolveButtonRow(row)), detail: row => onOpenDrawer(resolveButtonRow(row)), delete: row => removeRow(resolveButtonRow(row)), restore: row => row ? restoreRow(resolveButtonRow(row)) : restoreSelected(), destroy: row => row ? forceDeleteRow(resolveButtonRow(row)) : forceDeleteSelected() }
const buttonPermission = (code: string) => buttonUser.permissions.some(value => value === '*' || value === '*:*:*' || value === code);
const toolbarButtonAllowed = (button: FormListButton) => buttonAllowed(button, true) && (!['restore', 'destroy'].includes(listActionKey(button)) || buttonSelection.value.length > 0);
const buttonAllowed = (button: FormListButton, toolbar = false) => { const key = listActionKey(button); const suffix: Record<string, string> = { edit: 'update', refresh: 'list', recycle: 'list', normal: 'list', batchDelete: 'batch-delete', destroy: 'destroy' }; if (button.permission && !buttonPermission(button.permission)) return false; if (['registered', 'navigate', 'external', 'copy', 'download'].includes(button.action.type)) return !recycled.value && listButtonAdapterAllowed(buttonAdapter, buttonPermission, buttonContext('toolbar'));  const permissionSuffix = toolbar && ['restore', 'destroy'].includes(key) ? 'batch-' + key : (suffix[key] ?? key); if (!buttonPermission("example:test" + ':' + permissionSuffix)) return false; if (['restore', 'destroy'].includes(key)) return recycled.value; if (['create', 'edit', 'detail', 'delete', 'batchDelete'].includes(key)) return !recycled.value; return true; };
const toolbarButtons = computed(() => localizeButtons(resolveListButtons(listConfig, 'toolbar', [{"id":"normal","label":"正常列表","action":{"type":"builtin","key":"normal"},"color":"primary","plain":true,"placement":"inline","order":10},{"id":"recycle","label":"回收站","action":{"type":"builtin","key":"recycle"},"color":"warning","plain":true,"placement":"inline","order":20},{"id":"create","label":"新增","action":{"type":"builtin","key":"create"},"color":"primary","plain":true,"icon":"plus","placement":"inline","order":30},{"id":"batchdelete","label":"移入回收站","action":{"type":"builtin","key":"batchDelete"},"color":"danger","plain":true,"icon":"delete","selection":{"min":1},"placement":"inline","order":40,"interaction":{"type":"confirm","message":"确认移入回收站？此操作可能不可恢复。"}},{"id":"import","label":"CSV 导入","action":{"type":"builtin","key":"import"},"color":"success","plain":true,"icon":"upload","placement":"inline","order":50},{"id":"export","label":"CSV 导出","action":{"type":"builtin","key":"export"},"color":"default","plain":true,"icon":"download","placement":"inline","order":60},{"id":"restoreselected","label":"批量恢复","action":{"type":"builtin","key":"restore"}},{"id":"destroyselected","label":"批量永久删除","action":{"type":"builtin","key":"destroy"},"interaction":{"type":"confirm","message":"确认永久删除选中记录？此操作不可恢复。"}}] as FormListButton[]).map(button => { const key = listActionKey(button); if (key === 'batchDelete') return { ...button, selection: { ...button.selection, min: Math.max(1, button.selection?.min ?? 0) } }; if (['normal', 'recycle'].includes(key)) return { ...button, color: (key === 'normal' ? (!recycled.value ? 'primary' : 'info') : (recycled.value ? 'warning' : 'info')) as FormListButton['color'] }; return button; })));
const rowButtons = computed(() => localizeButtons(resolveListButtons(listConfig, 'row', [{"id":"edit","label":"编辑","action":{"type":"builtin","key":"edit"}},{"id":"detail","label":"详情","action":{"type":"builtin","key":"detail"}},{"id":"delete","label":"删除","action":{"type":"builtin","key":"delete"},"interaction":{"type":"confirm","message":"确认删除？此操作可能不可恢复。"}},{"id":"restore","label":"恢复","action":{"type":"builtin","key":"restore"}},{"id":"destroy","label":"永久删除","action":{"type":"builtin","key":"destroy"},"interaction":{"type":"confirm","message":"确认永久删除？此操作可能不可恢复。"}}] as FormListButton[])));
const hasRowButtons = computed(() => rowButtons.value.some(button => !button.hidden && buttonAllowed(button)));
const refreshButtonHost = async () => { clearButtonSelection(); await loadData(); };
watch(query, clearButtonSelection, { deep: true, flush: 'sync' });
watch(list, clearButtonSelection);
const handleSelectionChange = (rows: TestModel[]) => { buttonSelection.value = rows; buttonContextVersion.value++; onSelectionChange(rows); };
watch(query, () => onSelectionChange([]), { deep: true, flush: 'sync' });
const columnLabels = computed<Record<string, string>>(() => ({ 'id': t('crud.test.field.id', 'ID'), 'field1': t('crud.test.field.field_1', '单行输入'), 'field2': t('crud.test.field.field_2', '提及输入'), 'field3': t('crud.test.field.field_3', '虚拟化选择') }));
const tableSchema = computed<PageSchema>(() => ({ ...{"pageSchemaVersion":1,"key":"test","primaryKey":"id","search":[],"toolbar":[],"rowActions":[],"list":{"tools":{}},"pagination":{"pageSize":20,"pageSizes":[10,20,50,100],"enabled":true}}, columns: [...(toolbarButtons.value.some(button => button.action.type === 'registered') || true ? [{ key: 'selection', label: '', type: 'selection' as const, width: 48 }] : []), ...[{"key":"id","prop":"id","slot":"id","label":"ID","sortable":true},{"key":"field1","prop":"field1","slot":"field1","label":"单行输入"},{"key":"field2","prop":"field2","slot":"field2","label":"提及输入"},{"key":"field3","prop":"field3","slot":"field3","label":"虚拟化选择"}].map(column => ({ ...column, label: columnLabels.value[column.key] ?? column.label })), ...(hasRowButtons.value ? [{ key: 'actions', label: t('crud.test.action.column', '操作'), slot: 'actions' }] : [])] } as PageSchema));
const recycled = computed(() => query.recycled === 1);
const selectedIds = () => selection.value.map(row => row.id);
const fileInput = ref<HTMLInputElement>();
const csvLabels = computed<Record<string, string>>(() => ({ 'field1': t('crud.test.field.field_1', '单行输入'), 'field2': t('crud.test.field.field_2', '提及输入'), 'field3': t('crud.test.field.field_3', '虚拟化选择') }));
const csvColumns = computed(() => [{"key":"field1","label":"单行输入"},{"key":"field2","label":"提及输入"},{"key":"field3","label":"虚拟化选择"}].map(column => ({ ...column, label: csvLabels.value[column.key] ?? column.label })) as CsvColumn<TestModelPayload>[]);
function switchMode(value: boolean) { query.recycled = value ? 1 : 0; query.page = 1; void loadData(); }
async function removeRow(row: TestModel) { await testApi.remove(row.id); await refreshAfterSave(); }
async function restoreRow(row: TestModel) { await testApi.restore(row.id); await refreshAfterSave(); }
async function forceDeleteRow(row: TestModel) { await testApi.forceDelete(row.id); await refreshAfterSave(); }
async function restoreSelected() { await testApi.restoreMany(selectedIds()); await refreshAfterSave(); }
async function forceDeleteSelected() { await testApi.forceDeleteMany(selectedIds()); await refreshAfterSave(); }
async function importCsv(event: Event) { const input = event.target as HTMLInputElement; const file = input.files?.[0]; input.value = ''; if (!file || buttonLock.busy || !buttonPermission("example:test" + ':import')) return; buttonLock.busy = true; try { const version = buttonContextVersion.value; const rows = parseCsv<TestModelPayload>(await readFileAsText(file), csvColumns.value); if (version !== buttonContextVersion.value || !buttonPermission("example:test" + ':import')) return; await testApi.importRows(rows); await refreshAfterSave(); } finally { buttonLock.busy = false; } }
async function exportRows() { const rows = await testApi.exportRows(query); downloadCsv('test-export', toCsv(rows, csvColumns.value as CsvColumn<TestModel>[])); }
</script>
