<?php
namespace app\backend\controller\auth;
use app\backend\model\AuthGroup as AuthGroupModel ;
use think\facade\Config;
use think\facade\Session;
use think\facade\View;

class AuthGroup extends \app\common\controller\Backend
{
    /*-----------------------用户组管理----------------------*/
    use \app\common\traits\Curd;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function __construct(\think\App $app)
    {
        parent::__construct($app);
        $this->modelClass = new AuthGroupModel();
    }

    // 用户组添加
    public function add()
    {
        if ($this->request->isPost()) {
            $data = $this->request->post();
            try {
                $this->validate($data, 'AuthGroup');
            } catch (\Exception $e) {
                $this->error($e->getMessage());
            }
            $result =  $this->modelClass->save($data);
            if ($result) {
                $this->success(lang('Add success'), url('sys.Auth/group'));
            } else {
                $this->error(lang('Add Failed'));
            }

        } else {
            $view = [
                'formData' => null
            ];
            View::assign($view);
            return view('add');
        }
    }

    // 用户组修改
    public function edit()
    {
        if ($this->request->isPost()) {
            $data = $this->request->post();
            if($data['id']==1){
                $this->error(lang('SupperAdmin cannot edit'));
            }
            try{
                $this->validate($data, 'AuthGroup');
            }catch (\ValidateException $e){
                $this->error($e->getMessage());
            }
            $list = $this->modelClass->find($data['id']);
            $res = $list->save($data);
            if($res){
                $this->success(lang('edit success'), url('sys.Auth/group'));
            }else{
                $this->error(lang('edit fail'));
            }

        } else {
            $id = $this->request->param('id');
            $list = $this->modelClass->find(['id' => $id]);
            $view = [
                'formData' => $list,
                'title' => lang('edit')
            ];
            View::assign($view);
            return view();
        }
    }

    // 用户组状态修改
    public function modify()
    {
        if ($this->request->isPost()) {
            $id = $this->request->param('id');
            if($id==1){
                $this->error(lang('SuperGroup Cannot Edit'));
            }
            $list = $this->modelClass->find($id);
            $list->status = $list['status'] == 1 ? 0 : 1;
//            if($this->uid==3){
//                $this->error(lang('test data cannot edit'));
//            }
            $list->save();
            $this->success(lang('edit success'));

        }
    }




}