<?php

namespace app\install\controller;

use app\common\traits\Jump;
use think\App;
use app\BaseController;
use app\backend\model\Admin;
use app\common\service\MigrationService;
use think\facade\Db;

class Index extends BaseController
{
    use Jump;
    //开发模式
    protected $app_debug = false;

    protected $config;
    //错误信息
    protected $msg = '';
    //安装文件
    protected $lockFile;
    //数据库
    protected $databaseConfigFile;
    protected $envFile;
    //模版
    protected $envTpl;
    /**
     * 安装期间按文件名顺序执行 database/migrations。
     * 仅面向空数据库执行只向前 migration，不加载历史升级 SQL。
     */
    protected $sqlFileDir = '';
    //mysql版本
    protected $mysqlVersion = '5.7';
    //database模板
    protected $databaseTpl = '';

    public function __construct(App $app)
    {
        parent::__construct($app); // TODO: Change the autogenerated stub
        $this->databaseConfigFile = config_path() . "database.php";
        $this->envFile = root_path() . ".env";
        $this->lockFile = public_path() . "install.lock";
        $this->databaseTpl = app_path() . "view/tpl/database.tpl";
        $this->envTpl = app_path() . "view/tpl/env.example";
        $this->sqlFileDir = root_path() . 'database' . DIRECTORY_SEPARATOR . 'migrations';
        $this->config = [
            'siteName' => "FunAdmin",
            'siteVersion' => config('app.version'),
            'tablePrefix' => "fun_",
            'runtimePath' => runtime_path(),
            'lockFile' => $this->lockFile,
        ];
        set_time_limit(0);
    }

    public function index()
    {
        $route = file_exists($this->lockFile) ? 'login' : 'install';
        return redirect('/admin-web/#/' . $route);
    }

    /**
     * 返回 Vue 安装向导所需的运行环境检查结果。
     */
    public function step2()
    {
        if (file_exists($this->lockFile)) {
            $this->result(['installed' => true], 200, '系统已安装', 'json');
        }
        $uploadLimit = $this->sizeToBytes((string) ini_get('upload_max_filesize'));
        $checks = [
            $this->environmentCheck('os', '操作系统', '不限', php_uname('s'), true, true),
            $this->environmentCheck('php', 'PHP 版本', '>= 8.1.0', PHP_VERSION, version_compare(PHP_VERSION, '8.1.0', '>='), true),
            $this->environmentCheck('php_int', 'PHP 架构', '64 位', PHP_INT_SIZE === 8 ? '64 位' : '32 位', PHP_INT_SIZE === 8, true),
            $this->environmentCheck('json', 'JSON 扩展', '支持', $this->supportLabel(extension_loaded('json')), extension_loaded('json'), true),
            $this->environmentCheck('session', 'Session', '支持', $this->supportLabel(function_exists('session_start')), function_exists('session_start'), true),
            $this->environmentCheck('pdo', 'PDO 扩展', '支持', $this->supportLabel(extension_loaded('PDO')), extension_loaded('PDO'), true),
            $this->environmentCheck('pdo_mysql', 'PDO MySQL 驱动', '支持', $this->supportLabel(extension_loaded('pdo_mysql')), extension_loaded('pdo_mysql'), true),
            $this->environmentCheck('mysqli', 'MySQLi 扩展', '支持', $this->supportLabel(extension_loaded('mysqli')), extension_loaded('mysqli'), true),
            $this->environmentCheck('openssl', 'OpenSSL 扩展', '支持', $this->supportLabel(extension_loaded('openssl')), extension_loaded('openssl'), true),
            $this->environmentCheck('curl', 'CURL 扩展', '支持', $this->supportLabel(function_exists('curl_exec')), function_exists('curl_exec'), true),
            $this->environmentCheck('fileinfo', 'Fileinfo 扩展', '支持', $this->supportLabel(extension_loaded('fileinfo')), extension_loaded('fileinfo'), true),
            $this->environmentCheck('image', '图像扩展', 'GD 或 Imagick', $this->imageDriverLabel(), function_exists('gd_info') || class_exists('Imagick'), true),
            $this->environmentCheck('freetype', 'FreeType', '支持', $this->supportLabel(function_exists('imageftbbox')), function_exists('imageftbbox'), false),
            $this->environmentCheck('zip', 'ZIP 扩展', '支持', $this->supportLabel(extension_loaded('zip')), extension_loaded('zip'), false),
            $this->environmentCheck('upload', '文件上传限制', '>= 10 MB', (string) ini_get('upload_max_filesize'), $uploadLimit >= 10 * 1024 * 1024, false),
            $this->environmentCheck('runtime', 'runtime 目录', '可写', $this->writableLabel(runtime_path()), $this->isWritable(runtime_path()), true),
            $this->environmentCheck('public', 'public 目录', '可写', $this->writableLabel(public_path()), $this->isWritable(public_path()), true),
            $this->environmentCheck('config', '数据库配置', '可写', $this->writableLabel($this->databaseConfigFile), $this->isWritable($this->databaseConfigFile), true),
            $this->environmentCheck('env', '.env 配置', '可写', $this->writableLabel($this->envFile), $this->isWritable($this->envFile), true),
            $this->environmentCheck('migrations', '数据库迁移', '目录可读且包含 SQL', $this->migrationStatus(), $this->hasMigrations(), true),
        ];

        $this->result([
            'installed' => file_exists($this->lockFile),
            'siteName' => $this->config['siteName'],
            'siteVersion' => $this->config['siteVersion'],
            'checks' => $checks,
        ], 200, '环境检测完成', 'json');
    }

    public function step3()
    {
        if (!request()->isPost()) {
            $this->error('请求方法不正确');
        }
        if (request()->isPost()) {
            //执行安装

            $this->app_debug = request()->post('app_debug')? true : false;
            $db['host'] = request()->post('hostname') ? request()->post('hostname') : '127.0.0.1';
            $db['port'] = request()->post('port') ?: '3306';
            //判断是否在主机头后面加上了端口号
            $hostData = explode(":", $db['host']);
            if (isset($hostData) && $hostData && is_array($hostData) && count($hostData) > 1) {
                $db['host'] = $hostData[0];
                $db['port'] = $hostData[1];
            }
            //mysql的账户相关
            $db['username'] = request()->post('username') ?: 'root';
            $db['password'] = request()->post('password') ?: 'root';
            $db['database'] = request()->post('database') ?: 'funadmin';
            $db['prefix'] = request()->post('prefix');
            $admin['username'] = request()->post('adminUserName') ?: 'admin';
            $admin['password'] = request()->post('adminPassword') ?: '123456';
            $admin['repassword'] = request()->post('rePassword') ?: '123456';
            $admin['email'] = request()->post('email') ?: 'admin@admin.com';
            if (file_exists($this->lockFile)) {
                $this->error('当前版本已经安装了，如果需要重新安装请先删除install.lock');
            }
            //php 版本
            if (version_compare(PHP_VERSION, '8.1.0', '<')) {
                $this->error('当前 PHP 版本 ' . PHP_VERSION . ' 过低，请使用 PHP 8.1.0 以上版本');
            }
            if (!extension_loaded('PDO') || !extension_loaded('mysqli')) {
                $this->error('当前未开启 PDO 或 MySQLi，无法进行安装');
            }
            if (!$this->hasMigrations()) {
                $this->error('数据库迁移文件不存在，无法进行安装');
            }
            //判断两次输入是否一致
            if ($admin['password'] != $admin['repassword']) {
                $this->error('两次输入密码不一致！');
            }
            if (!preg_match('/^[0-9a-z_$]{6,16}$/i', $admin['password'])) {
                $this->error('密码必须6-16位,不能有中文和空格');
            }
            if (!preg_match('/[a-z]/i', $admin['password']) || !preg_match('/\d/', $admin['password'])) {
                $this->error('管理员密码必须同时包含字母和数字');
            }
            if (!preg_match('/^[a-zA-Z0-9_]+$/', $db['database'])) {
                $this->error('数据库名只能包含字母、数字和下划线');
            }
            if ($db['prefix'] !== '' && !preg_match('/^[a-zA-Z][a-zA-Z0-9_]*_$/', $db['prefix'])) {
                $this->error('数据表前缀必须以字母开头、下划线结尾');
            }
            if (strlen($admin['email']) > 60) {
                $this->error('管理员邮箱不能超过60个字符');
            }
            if (!filter_var($admin['email'], FILTER_VALIDATE_EMAIL)) {
                $this->error('管理员邮箱格式不正确');
            }
            if (!preg_match("/^\w+$/", $admin['username'])) {
                $this->error('用户名只能输入字母、数字、下划线！');
            }
            if (strlen($admin['username']) < 3 || strlen($admin['username']) > 12) {
                $this->error('用户名请输入3~12位字符！');
            }
            if(!preg_match('/^[0-9a-z_$]{6,16}$/i', $admin['password']) || strlen($admin['password']) < 5 || strlen($admin['password']) > 16){
                $this->error('管理员密码必须6-16位,且必须包含字母和数字,不能有中文和空格');
            }

            // 连接数据库
            try {
                $link = new \mysqli($db['host'], $db['username'], $db['password'], '', (int) $db['port']);
            } catch (\mysqli_sql_exception $exception) {
                $this->error('数据库连接失败：' . $exception->getMessage());
            }
            $link->query("SET NAMES 'utf8mb4'");
//            需要超管
//            $link->query('set global wait_timeout=2147480');
//            $link->query("set global interactive_timeout=2147480");
//            $link->query("set global max_allowed_packet=104857600");
            //版本
            if (version_compare($link->server_info, $this->mysqlVersion, '<')) {
                $this->error("MySQL数据库版本不能低于{$this->mysqlVersion},请将您的MySQL升级到{$this->mysqlVersion}及以上");
            }
            try {
                // 创建数据库并选中
                $create_sql = 'CREATE DATABASE IF NOT EXISTS `' . $db['database'] . '` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;';
                if (!$link->query($create_sql)) {
                    $this->error('创建数据库失败');
                }
            }catch (\Exception $e){
                $this->error($e->getMessage());
            }
            $link->select_db($db['database']);
            // 写入数据库
            $config = config('database');
            $config['default'] = 'mysql';
            $config['connections']['mysql'] = [
                'type'      => 'mysql',
                'hostname'  => $db['host'],
                'database'  => $db['database'],
                'username'  => $db['username'],
                'password'  => $db['password'],
                'hostport'  => $db['port'],
                'params'    => [],
                'charset'   => 'utf8mb4',
                'prefix'    => $db['prefix'],
                'fields_cache' => false
            ];
            config($config, 'database');
            //替换数据库相关配置
            $putDatabase = str_replace(
                ['%hostname%', '%database%', '%username%', '%password%', '%port%', '%prefix%'],
                [$db['host'],$db['database'], $db['username'], $db['password'], $db['port'], $db['prefix']],
                file_get_contents($this->databaseTpl));
            $putConfig = @file_put_contents($this->databaseConfigFile, $putDatabase);
            if (!$putConfig) {
                $this->error('安装失败、请确定database.php是否有写入权限');
            }
            $envUpdates = [
                'APP_DEBUG' => $this->app_debug ? 'true' : 'false',
                'DB_DRIVER' => 'mysql',
                'DB_TYPE' => 'mysql',
                'DB_HOST' => $db['host'],
                'DB_NAME' => $db['database'],
                'DB_USER' => $db['username'],
                'DB_PASS' => $db['password'],
                'DB_PORT' => $db['port'],
                'DB_CHARSET' => 'utf8mb4',
                'DB_PREFIX' => $db['prefix'],
            ];
            // 已存在 .env 时合并更新，保留 JWT 等自定义键；全新安装才按模板写入
            if (is_file($this->envFile)) {
                $putEnv = $this->mergeEnv((string) file_get_contents($this->envFile), $envUpdates);
            } else {
                $putEnv = str_replace(
                    ['%debug%','%hostname%', '%database%', '%username%', '%password%', '%port%', '%prefix%'],
                    [$envUpdates['APP_DEBUG'], $db['host'], $db['database'], $db['username'], $db['password'], $db['port'], $db['prefix']],
                    file_get_contents($this->envTpl));
            }
            $putConfig = @file_put_contents($this->envFile, $putEnv);
            if (!$putConfig) {
                $this->error('安装失败、请确定 .env 是否有写入权限');
            }
            try {
                $instance = Db::connect();
                $instance->execute("SELECT 1");     //如果是【数据】增删改查直接运行
                MigrationService::instance()->runDirectory($this->sqlFileDir, 'core');
                $password = password($admin['password']);
                Admin::where('id', 1)->update(['email' => $admin['email'], 'username' => $admin['username'], 'password' => $password]);
            } catch (\PDOException $e) {
                $this->error($e->getMessage());
            }catch(\Exception $e){
                $this->error($e->getMessage());
            }
            if (!@touch($this->lockFile)) {
                $this->error('安装完成但无法创建 install.lock，请检查 public 目录权限');
            }
            $adminUser = [
                'username' => $admin['username'],
                'password' => $admin['password'],
                'backend' => '/admin-web/#/login',
            ];
            session('admin_install', $adminUser);
            $this->result($adminUser, 200, '安装成功', 'json');
        }
    }

    public function step4()
    {
        $admin = session('admin_install');
        if (!$admin) {
            $this->error('安装信息不存在');
        }
        if (request()->isPost()) {
            session('admin_install', null);
        }
        $this->result($admin, 200, '安装完成', 'json');
    }

    private function environmentCheck(string $key, string $label, string $requiredValue, string $currentValue, bool $passed, bool $required): array
    {
        return compact('key', 'label', 'requiredValue', 'currentValue', 'passed', 'required');
    }

    private function isWritable(string $file): bool
    {
        return file_exists($file) ? is_writable($file) : is_writable(dirname($file));
    }

    private function writableLabel(string $file): string
    {
        return $this->isWritable($file) ? '可写' : '不可写';
    }

    /**
     * 合并更新 .env：仅替换已有键的值，缺失键追加，其余行原样保留。
     */
    private function mergeEnv(string $content, array $updates): string
    {
        $lines = preg_split('/\R/', $content) ?: [];
        $found = [];
        foreach ($lines as $i => $line) {
            if (preg_match('/^\s*([A-Z][A-Z0-9_]*)\s*=/', $line, $m) && array_key_exists($m[1], $updates)) {
                $lines[$i] = $m[1] . ' = ' . $updates[$m[1]];
                $found[$m[1]] = true;
            }
        }
        foreach ($updates as $key => $value) {
            if (!isset($found[$key])) {
                $lines[] = $key . ' = ' . $value;
            }
        }
        return implode("\n", $lines);
    }

    private function supportLabel(bool $supported): string
    {
        return $supported ? '支持' : '未安装';
    }

    private function imageDriverLabel(): string
    {
        if (class_exists('Imagick')) {
            return 'Imagick';
        }
        return function_exists('gd_info') ? 'GD' : '未安装';
    }

    private function sizeToBytes(string $value): int
    {
        $value = trim($value);
        if ($value === '') {
            return 0;
        }
        $unit = strtolower(substr($value, -1));
        $size = (float) $value;
        return match ($unit) {
            'g' => (int) ($size * 1024 * 1024 * 1024),
            'm' => (int) ($size * 1024 * 1024),
            'k' => (int) ($size * 1024),
            default => (int) $size,
        };
    }

    private function migrationFiles(): array
    {
        if (!is_dir($this->sqlFileDir) || !is_readable($this->sqlFileDir)) {
            return [];
        }
        return glob($this->sqlFileDir . DIRECTORY_SEPARATOR . '*.sql') ?: [];
    }

    private function hasMigrations(): bool
    {
        $files = $this->migrationFiles();
        foreach ($files as $file) {
            if (!is_readable($file)) {
                return false;
            }
        }
        return count($files) > 0;
    }

    private function migrationStatus(): string
    {
        if (!is_dir($this->sqlFileDir)) {
            return '目录不存在';
        }
        if (!is_readable($this->sqlFileDir)) {
            return '目录不可读';
        }
        $files = $this->migrationFiles();
        foreach ($files as $file) {
            if (!is_readable($file)) {
                return basename($file) . ' 不可读';
            }
        }
        return $files ? count($files) . ' 个迁移文件' : '无迁移文件';
    }
}
